In [8]:
import polars as pl

# Configure Polars so Jupyter shows ALL columns and a controlled
# number of rows. This prevents truncation and keeps rendering fast.

pl.Config.set_tbl_cols(-1)   # show all columns, no matter how many
pl.Config.set_tbl_rows(150)   # show only 10 rows in the HTML output

# Load the unified tract-quarter feature dataset
df = pl.read_parquet("../../data/processed/feature_engineering/tract_quarter_features.parquet")

acs_cols = [
    col for col in df.columns
    if (
        col in [
            # Raw ACS fields
            "population_total", "population_male", "population_female",
            "male_65_66", "male_67_69", "male_70_74", "male_75_79",
            "male_80_84", "male_85_plus",
            "female_65_66", "female_67_69", "female_70_74", "female_75_79",
            "female_80_84", "female_85_plus",
            "male_under_5", "female_under_5",
            "median_age",
            "disability_under_18", "disability_18_64", "disability_65_plus",
            "edu_high_school", "edu_bachelors", "edu_masters",
            "edu_professional", "edu_doctorate",
            "poverty_universe", "poverty_below",
            "median_household_income", "labor_force",
            "labor_force_civilian", "unemployment_civilian",
            "housing_units", "housing_occupied", "housing_vacant",
            "median_home_value", "median_gross_rent",
            "race_universe", "race_white", "race_black",
            "race_american_indian", "race_asian",
            "race_pacific_islander", "race_hispanic", "race_other",
            "language_universe",
            "limited_english_5_17", "limited_english_18_64",
            "limited_english_65_plus",
            "no_english_5_17", "no_english_18_64", "no_english_65_plus",
            "vehicle_universe", "vehicle_none",
            "housing_structure_universe",
            "housing_1_unit", "housing_2_unit", "housing_3_4_unit",
            "housing_5_9_unit", "housing_10_19_unit",
            "housing_20_49_unit", "housing_50_plus_unit",
            "housing_mobile_home",

            # Engineered totals
            "population_65_plus", "population_under_5",
            "disability_total", "edu_total",
            "limited_english_total", "no_english_total",

            # Engineered ratios
            "pct_male", "pct_female", "sex_ratio",
            "pct_65_plus", "pct_under_5",
            "pct_disability",
            "pct_high_school", "pct_bachelors", "pct_grad_degree",
            "pct_poverty", "pct_unemployment",
            "pct_housing_occupied", "pct_housing_vacant",
            "pct_white", "pct_black", "pct_asian", "pct_hispanic",
            "pct_american_indian", "pct_pacific_islander", "pct_race_other",
            "pct_limited_english", "pct_no_english",
            "pct_vehicle_none",
            "pct_single_family", "pct_small_multi_family",
            "pct_large_multi_family", "pct_mobile_home",
        ]
    )
]

In [2]:
df.select(acs_cols).describe()

shape: (9, 97)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ sta ┆ pop ┆ pop ┆ pop ┆ mal ┆ mal ┆ mal ┆ mal ┆ mal ┆ mal ┆ fem ┆ fem ┆ fem ┆ fem ┆ fem ┆ fem ┆ mal ┆ fem ┆ med ┆ dis ┆ dis ┆ dis ┆ edu ┆ edu ┆ edu ┆ edu ┆ edu ┆ pov ┆ pov ┆ med ┆ lab ┆ lab ┆ une ┆ hou ┆ hou ┆ hou ┆ med ┆ med ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ lan ┆ lim ┆ lim ┆ lim ┆ no_ ┆ no_ ┆ no_ ┆ veh ┆ veh ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ pop ┆ pop ┆ dis ┆ edu ┆ lim ┆ no_ ┆ pct ┆ pct ┆ sex ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct │
│ tis ┆ ula ┆ ula ┆ ula ┆ e_6 ┆ e_6 ┆ e_7 ┆ e_7 ┆ e_8 ┆ e_8 ┆ ale ┆ ale ┆ ale ┆ ale ┆ ale ┆ ale ┆ e_u ┆ ale ┆ ian ┆ abi ┆ abi ┆ abi ┆ _hi ┆ _ba ┆ _ma ┆ _pr ┆ _do ┆ ert ┆ ert ┆ ian ┆ or_ ┆ or_ ┆ mpl ┆ sin ┆ sin ┆ sin ┆ ian ┆ ian ┆ e_u ┆ e_w ┆ e_b ┆ e_a ┆ e_a ┆ e_p ┆ e_h ┆ e_o ┆ gua ┆ ite ┆ ite ┆ ite ┆ eng ┆ eng ┆ eng ┆ icl ┆ icl ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ ula ┆ ula ┆ abi ┆ _to ┆ ite ┆ eng ┆ _ma ┆ _fe ┆ _ra ┆ _65 ┆ _un ┆ _di ┆ _hi ┆ _ba ┆ _gr ┆ _po ┆ _un ┆ _ho ┆ _ho ┆ _wh ┆ _bl ┆ _as ┆ _hi ┆ _am ┆ _pa ┆ _ra ┆ _li ┆ _no ┆ _ve ┆ _si ┆ _sm ┆ _la ┆ _mo │
│ tic ┆ tio ┆ tio ┆ tio ┆ 5_6 ┆ 7_6 ┆ 0_7 ┆ 5_7 ┆ 0_8 ┆ 5_p ┆ _65 ┆ _67 ┆ _70 ┆ _75 ┆ _80 ┆ _85 ┆ nde ┆ _un ┆ _ag ┆ lit ┆ lit ┆ lit ┆ gh_ ┆ che ┆ ste ┆ ofe ┆ cto ┆ y_u ┆ y_b ┆ _ho ┆ for ┆ for ┆ oym ┆ g_u ┆ g_o ┆ g_v ┆ _ho ┆ _gr ┆ niv ┆ hit ┆ lac ┆ mer ┆ sia ┆ aci ┆ isp ┆ the ┆ ge_ ┆ d_e ┆ d_e ┆ d_e ┆ lis ┆ lis ┆ lis ┆ e_u ┆ e_n ┆ g_s ┆ g_1 ┆ g_2 ┆ g_3 ┆ g_5 ┆ g_1 ┆ g_2 ┆ g_5 ┆ g_m ┆ tio ┆ tio ┆ lit ┆ tal ┆ d_e ┆ lis ┆ le  ┆ mal ┆ tio ┆ _pl ┆ der ┆ sab ┆ gh_ ┆ che ┆ ad_ ┆ ver ┆ emp ┆ usi ┆ usi ┆ ite ┆ ack ┆ ian ┆ spa ┆ eri ┆ cif ┆ ce_ ┆ mit ┆ _en ┆ hic ┆ ngl ┆ all ┆ rge ┆ bil │
│ --- ┆ n_t ┆ n_m ┆ n_f ┆ 6   ┆ 9   ┆ 4   ┆ 9   ┆ 4   ┆ lus ┆ _66 ┆ _69 ┆ _74 ┆ _79 ┆ _84 ┆ _pl ┆ r_5 ┆ der ┆ e   ┆ y_u ┆ y_1 ┆ y_6 ┆ sch ┆ lor ┆ rs  ┆ ssi ┆ rat ┆ niv ┆ elo ┆ use ┆ ce  ┆ ce_ ┆ ent ┆ nit ┆ ccu ┆ aca ┆ me_ ┆ oss ┆ ers ┆ e   ┆ k   ┆ ica ┆ n   ┆ fic ┆ ani ┆ r   ┆ uni ┆ ngl ┆ ngl ┆ ngl ┆ h_5 ┆ h_1 ┆ h_6 ┆ niv ┆ one ┆ tru ┆ _un ┆ _un ┆ _4_ ┆ _9_ ┆ 0_1 ┆ 0_4 ┆ 0_p ┆ obi ┆ n_6 ┆ n_u ┆ y_t ┆ --- ┆ ngl ┆ h_t ┆ --- ┆ e   ┆ --- ┆ us  ┆ _5  ┆ ili ┆ sch ┆ lor ┆ deg ┆ ty  ┆ loy ┆ ng_ ┆ ng_ ┆ --- ┆ --- ┆ --- ┆ nic ┆ can ┆ ic_ ┆ oth ┆ ed_ ┆ gli ┆ le_ ┆ e_f ┆ _mu ┆ _mu ┆ e_h │
│ str ┆ ota ┆ ale ┆ ema ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ us  ┆ --- ┆ _5  ┆ --- ┆ nde ┆ 8_6 ┆ 5_p ┆ ool ┆ s   ┆ --- ┆ ona ┆ e   ┆ ers ┆ w   ┆ hol ┆ --- ┆ civ ┆ _ci ┆ s   ┆ pie ┆ nt  ┆ val ┆ _re ┆ e   ┆ --- ┆ --- ┆ n_i ┆ --- ┆ _is ┆ c   ┆ --- ┆ ver ┆ ish ┆ ish ┆ ish ┆ _17 ┆ 8_6 ┆ 5_p ┆ ers ┆ --- ┆ ctu ┆ it  ┆ it  ┆ uni ┆ uni ┆ 9_u ┆ 9_u ┆ lus ┆ le_ ┆ 5_p ┆ nde ┆ ota ┆ f64 ┆ ish ┆ ota ┆ f64 ┆ --- ┆ f64 ┆ --- ┆ --- ┆ ty  ┆ ool ┆ s   ┆ ree ┆ --- ┆ men ┆ occ ┆ vac ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ _in ┆ isl ┆ er  ┆ eng ┆ sh  ┆ non ┆ ami ┆ lti ┆ lti ┆ ome │
│     ┆ l   ┆ --- ┆ le  ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ f64 ┆ --- ┆ f64 ┆ r_1 ┆ 4   ┆ lus ┆ --- ┆ --- ┆ f64 ┆ l   ┆ --- ┆ e   ┆ --- ┆ d_i ┆ f64 ┆ ili ┆ vil ┆ --- ┆ d   ┆ --- ┆ ue  ┆ nt  ┆ --- ┆ f64 ┆ f64 ┆ ndi ┆ f64 ┆ lan ┆ --- ┆ f64 ┆ se  ┆ _5_ ┆ _18 ┆ _65 ┆ --- ┆ 4   ┆ lus ┆ e   ┆ f64 ┆ re_ ┆ --- ┆ --- ┆ t   ┆ t   ┆ nit ┆ nit ┆ _un ┆ hom ┆ lus ┆ r_5 ┆ l   ┆     ┆ _to ┆ l   ┆     ┆ f64 ┆     ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆ t   ┆ upi ┆ ant ┆     ┆     ┆     ┆ f64 ┆ dia ┆ and ┆ --- ┆ lis ┆ --- ┆ e   ┆ ly  ┆ _fa ┆ _fa ┆ --- │
│     ┆ --- ┆ f64 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆     ┆ 8   ┆ --- ┆ --- ┆ f64 ┆ f64 ┆     ┆ --- ┆ f64 ┆ --- ┆ f64 ┆ nco ┆     ┆ an  ┆ ian ┆ f64 ┆ --- ┆ f64 ┆ --- ┆ --- ┆ f64 ┆     ┆     ┆ an  ┆     ┆ der ┆ f64 ┆     ┆ --- ┆ 17  ┆ _64 ┆ _pl ┆ f64 ┆ --- ┆ --- ┆ --- ┆     ┆ uni ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ it  ┆ e   ┆ --- ┆ --- ┆ --- ┆     ┆ tal ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆ --- ┆ ed  ┆ --- ┆     ┆     ┆     ┆     ┆ n   ┆ er  ┆ f64 ┆ h   ┆ f64 ┆ --- ┆ --- ┆ mil ┆ mil ┆ f64 │
│     ┆ f64 ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ f64 ┆ f64 ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆     ┆ me  ┆     ┆ --- ┆ --- ┆     ┆ f64 ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆ --- ┆     ┆ --- ┆     ┆     ┆ f64 ┆ --- ┆ --- ┆ us  ┆     ┆ f64 ┆ f64 ┆ f64 ┆     ┆ ver ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆     ┆ --- ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ f64 ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ f64 ┆ f64 ┆ y   ┆ y   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ se  ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆ f64 ┆     ┆     ┆     ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ cou ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 104 ┆ 103 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 ┆ 105 │
│ nt  ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 82. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 48. ┆ 92. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. ┆ 89. │
│     ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│ nul ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 7.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 141 ┆ 197 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│ l_c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .0  ┆ .0  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ oun ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ mea ┆ 389 ┆ 195 ┆ 194 ┆ 50. ┆ 66. ┆ 96. ┆ 57. ┆ 35. ┆ 29. ┆ 50. ┆ 71. ┆ 100 ┆ 65. ┆ 45. ┆ 52. ┆ 106 ┆ 101 ┆ 41. ┆ 22. ┆ 180 ┆ 179 ┆ 701 ┆ 594 ┆ 222 ┆ 46. ┆ 38. ┆ 380 ┆ 397 ┆ 788 ┆ 206 ┆ 206 ┆ 66. ┆ 182 ┆ 163 ┆ 196 ┆ 265 ┆ 108 ┆ 389 ┆ 306 ┆ 228 ┆ 21. ┆ 113 ┆ 0.9 ┆ 309 ┆ 13. ┆ 368 ┆ 0.1 ┆ 1.0 ┆ 0.1 ┆ 0.0 ┆ 0.1 ┆ 0.0 ┆ 163 ┆ 102 ┆ 182 ┆ 79. ┆ 106 ┆ 63. ┆ 89. ┆ 67. ┆ 74. ┆ 77. ┆ 56. ┆ 723 ┆ 208 ┆ 382 ┆ 160 ┆ 1.3 ┆ 0.2 ┆ 0.5 ┆ 0.4 ┆ 1.0 ┆ 0.1 ┆ 0.0 ┆ 0.0 ┆ 0.4 ┆ 0.3 ┆ 0.1 ┆ 0.1 ┆ 0.0 ┆ 0.8 ┆ 0.1 ┆ 0.7 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.1 ┆ 0.1 ┆ 0.0 │
│ n   ┆ 5.9 ┆ 1.2 ┆ 4.7 ┆ 200 ┆ 528 ┆ 740 ┆ 844 ┆ 574 ┆ 971 ┆ 973 ┆ 537 ┆ .57 ┆ 411 ┆ 636 ┆ 094 ┆ .63 ┆ .78 ┆ 343 ┆ 242 ┆ .85 ┆ .70 ┆ .09 ┆ .77 ┆ .97 ┆ 802 ┆ 003 ┆ 8.8 ┆ .97 ┆ 50. ┆ 6.3 ┆ 3.8 ┆ 843 ┆ 9.6 ┆ 3.1 ┆ .58 ┆ 226 ┆ 8.3 ┆ 5.9 ┆ 6.1 ┆ .33 ┆ 393 ┆ .91 ┆ 409 ┆ .40 ┆ 459 ┆ 7.5 ┆ 553 ┆ 213 ┆ 560 ┆ 424 ┆ 100 ┆ 495 ┆ 3.1 ┆ .83 ┆ 9.6 ┆ 603 ┆ .38 ┆ 876 ┆ 146 ┆ 344 ┆ 148 ┆ 424 ┆ 045 ┆ .08 ┆ .41 ┆ .79 ┆ 3.6 ┆ 327 ┆ 020 ┆ 005 ┆ 994 ┆ 149 ┆ 891 ┆ 533 ┆ 994 ┆ 745 ┆ 483 ┆ 771 ┆ 157 ┆ 357 ┆ 961 ┆ 038 ┆ 676 ┆ 738 ┆ 281 ┆ 815 ┆ 074 ┆ 002 ┆ 034 ┆ 004 ┆ 000 ┆ 693 ┆ 411 ┆ 530 ┆ 171 ┆ 286 │
│     ┆ 696 ┆ 505 ┆ 191 ┆ 302 ┆ 662 ┆ 58  ┆ 65  ┆ 086 ┆ 574 ┆ 557 ┆ 445 ┆ 399 ┆ 465 ┆ 321 ┆ 815 ┆ 547 ┆ 364 ┆ 632 ┆ 705 ┆ 145 ┆ 148 ┆ 217 ┆ 505 ┆ 006 ┆ 153 ┆ 305 ┆ 279 ┆ 742 ┆ 117 ┆ 428 ┆ 109 ┆ 611 ┆ 959 ┆ 132 ┆ 268 ┆ .78 ┆ 613 ┆ 696 ┆ 240 ┆ 818 ┆ 994 ┆ 897 ┆ 76  ┆ 957 ┆ 911 ┆ 505 ┆ 5   ┆ 43  ┆ 11  ┆ 02  ┆ 2   ┆ 8   ┆ 132 ┆ 681 ┆ 959 ┆ 834 ┆ 851 ┆ 287 ┆ 662 ┆ 131 ┆ 267 ┆ 969 ┆ 613 ┆ 744 ┆ 911 ┆ 563 ┆ 427 ┆ 04  ┆ 02  ┆ 66  ┆ 34  ┆ 94  ┆ 79  ┆ 39  ┆ 6   ┆ 16  ┆ 74  ┆ 1   ┆ 25  ┆ 56  ┆ 91  ┆ 09  ┆ 86  ┆ 94  ┆ 44  ┆ 47  ┆ 84  ┆ 27  ┆ 92  ┆ 09  ┆ 63  ┆ 81  ┆ 94  ┆ 06  ┆ 9   ┆ 2   │
│     ┆ 86  ┆ 43  ┆ 43  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆ 1   ┆ 3   ┆     ┆     ┆     ┆ 3   ┆ 1   ┆     ┆ 3   ┆     ┆     ┆ 35  ┆ 9   ┆ 188 ┆ 09  ┆ 36  ┆     ┆ 11  ┆ 31  ┆     ┆ 125 ┆ 28  ┆ 86  ┆ 91  ┆ 1   ┆     ┆ 3   ┆     ┆ 6   ┆     ┆ 71  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 31  ┆ 2   ┆ 11  ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆ 4   ┆ 7   ┆ 42  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ std ┆ 153 ┆ 787 ┆ 777 ┆ 37. ┆ 48. ┆ 63. ┆ 44. ┆ 31. ┆ 32. ┆ 40. ┆ 50. ┆ 64. ┆ 46. ┆ 39. ┆ 52. ┆ 73. ┆ 72. ┆ 7.9 ┆ 28. ┆ 112 ┆ 111 ┆ 354 ┆ 400 ┆ 181 ┆ 61. ┆ 56. ┆ 151 ┆ 336 ┆ 270 ┆ 900 ┆ 899 ┆ 55. ┆ 674 ┆ 633 ┆ 328 ┆ 110 ┆ 298 ┆ 153 ┆ 155 ┆ 528 ┆ 101 ┆ 177 ┆ 6.3 ┆ 435 ┆ 30. ┆ 145 ┆ 2.3 ┆ 7.3 ┆ 2.2 ┆ 1.2 ┆ 1.7 ┆ 1.1 ┆ 633 ┆ 111 ┆ 674 ┆ 95. ┆ 131 ┆ 77. ┆ 122 ┆ 92. ┆ 126 ┆ 173 ┆ 98. ┆ 348 ┆ 125 ┆ 203 ┆ 748 ┆ 8.5 ┆ 2.5 ┆ 0.0 ┆ 0.0 ┆ 0.1 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.0 ┆ 0.1 ┆ 0.1 ┆ 0.2 ┆ 0.1 ┆ 0.0 ┆ 0.1 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.1 ┆ 0.1 ┆ 0.0 │
│     ┆ 3.1 ┆ .22 ┆ .47 ┆ 845 ┆ 582 ┆ 217 ┆ 519 ┆ 632 ┆ 892 ┆ 417 ┆ 785 ┆ 950 ┆ 866 ┆ 199 ┆ 814 ┆ 488 ┆ 347 ┆ 555 ┆ 332 ┆ .90 ┆ .54 ┆ .63 ┆ .36 ┆ .52 ┆ 205 ┆ 334 ┆ 1.3 ┆ .08 ┆ 23. ┆ .80 ┆ .97 ┆ 197 ┆ .79 ┆ .92 ┆ .93 ┆ 904 ┆ .51 ┆ 3.1 ┆ 9.0 ┆ .30 ┆ .70 ┆ .54 ┆ 971 ┆ .31 ┆ 269 ┆ 3.3 ┆ 479 ┆ 590 ┆ 490 ┆ 097 ┆ 675 ┆ 039 ┆ .92 ┆ .50 ┆ .79 ┆ 231 ┆ .65 ┆ 031 ┆ .56 ┆ 791 ┆ .25 ┆ .63 ┆ 373 ┆ .07 ┆ .66 ┆ .32 ┆ .58 ┆ 619 ┆ 807 ┆ 392 ┆ 392 ┆ 646 ┆ 729 ┆ 259 ┆ 440 ┆ 935 ┆ 183 ┆ 041 ┆ 019 ┆ 324 ┆ 265 ┆ 265 ┆ 348 ┆ 815 ┆ 423 ┆ 140 ┆ 468 ┆ 016 ┆ 086 ┆ 030 ┆ 009 ┆ 808 ┆ 429 ┆ 398 ┆ 544 ┆ 474 │
│     ┆ 464 ┆ 750 ┆ 750 ┆ 617 ┆ 336 ┆ 434 ┆ 291 ┆ 328 ┆ 399 ┆ 86  ┆ 744 ┆ 147 ┆ 962 ┆ 526 ┆ 788 ┆ 447 ┆ 785 ┆ 25  ┆ 619 ┆ 153 ┆ 468 ┆ 669 ┆ 266 ┆ 333 ┆ 921 ┆ 627 ┆ 541 ┆ 057 ┆ 900 ┆ 640 ┆ 510 ┆ 296 ┆ 998 ┆ 200 ┆ 042 ┆ .64 ┆ 864 ┆ 464 ┆ 619 ┆ 355 ┆ 199 ┆ 669 ┆ 78  ┆ 045 ┆ 449 ┆ 746 ┆ 34  ┆ 85  ┆ 87  ┆ 69  ┆ 35  ┆ 21  ┆ 200 ┆ 887 ┆ 998 ┆ 276 ┆ 776 ┆ 986 ┆ 417 ┆ 762 ┆ 818 ┆ 652 ┆ 619 ┆ 738 ┆ 873 ┆ 726 ┆ 426 ┆ 97  ┆ 5   ┆ 72  ┆ 72  ┆ 14  ┆ 33  ┆ 35  ┆ 85  ┆ 79  ┆ 91  ┆ 09  ┆ 33  ┆ 43  ┆ 98  ┆ 98  ┆ 33  ┆ 19  ┆ 53  ┆ 15  ┆ 09  ┆ 58  ┆ 42  ┆ 63  ┆ 09  ┆ 37  ┆ 44  ┆ 61  ┆ 3   ┆ 8   │
│     ┆ 04  ┆ 1   ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆ 3   ┆ 1   ┆ 6   ┆ 9   ┆     ┆     ┆ 71  ┆     ┆ 391 ┆ 5   ┆ 6   ┆     ┆ 6   ┆ 3   ┆ 3   ┆ 843 ┆ 6   ┆ 04  ┆ 26  ┆ 6   ┆ 2   ┆ 8   ┆     ┆ 9   ┆     ┆ 58  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆ 1   ┆ 6   ┆     ┆ 6   ┆     ┆ 1   ┆     ┆ 4   ┆ 4   ┆     ┆ 2   ┆ 2   ┆ 6   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ min ┆ 648 ┆ 308 ┆ 340 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 19. ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 93. ┆ 7.0 ┆ 101 ┆ 26. ┆ 26. ┆ 0.0 ┆ 11. ┆ 11. ┆ 0.0 ┆ 390 ┆ 408 ┆ 648 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 646 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 11. ┆ 0.0 ┆ 11. ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 17. ┆ 0.0 ┆ 0.0 ┆ 0.3 ┆ 0.2 ┆ 0.4 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.2 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│     ┆ .0  ┆ .0  ┆ .0  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 14. ┆ 0   ┆ 0   ┆     ┆ 0   ┆ 0   ┆     ┆ 00. ┆ .0  ┆ .0  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .0  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆ 201 ┆ 828 ┆ 708 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 025 ┆     ┆ 881 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 87  ┆ 05  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 71  ┆     ┆ 56  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 25% ┆ 274 ┆ 136 ┆ 135 ┆ 24. ┆ 31. ┆ 50. ┆ 27. ┆ 13. ┆ 8.0 ┆ 23. ┆ 36. ┆ 54. ┆ 33. ┆ 19. ┆ 15. ┆ 51. ┆ 50. ┆ 36. ┆ 0.0 ┆ 97. ┆ 97. ┆ 442 ┆ 305 ┆ 92. ┆ 10. ┆ 5.0 ┆ 267 ┆ 186 ┆ 612 ┆ 142 ┆ 142 ┆ 29. ┆ 134 ┆ 116 ┆ 52. ┆ 185 ┆ 890 ┆ 274 ┆ 199 ┆ 7.0 ┆ 0.0 ┆ 7.0 ┆ 0.0 ┆ 80. ┆ 0.0 ┆ 260 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 116 ┆ 33. ┆ 134 ┆ 16. ┆ 20. ┆ 9.0 ┆ 9.0 ┆ 4.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 466 ┆ 116 ┆ 237 ┆ 106 ┆ 0.0 ┆ 0.0 ┆ 0.4 ┆ 0.4 ┆ 0.9 ┆ 0.1 ┆ 0.0 ┆ 0.0 ┆ 0.3 ┆ 0.2 ┆ 0.1 ┆ 0.0 ┆ 0.0 ┆ 0.8 ┆ 0.0 ┆ 0.7 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 │
│     ┆ 6.0 ┆ 2.0 ┆ 1.0 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆     ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 299 ┆     ┆ 0   ┆ 0   ┆ .0  ┆ .0  ┆ 0   ┆ 0   ┆     ┆ 7.0 ┆ .0  ┆ 05. ┆ 4.0 ┆ 3.0 ┆ 0   ┆ 4.0 ┆ 6.0 ┆ 0   ┆ 600 ┆ .0  ┆ 6.0 ┆ 1.0 ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 3.0 ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6.0 ┆ 0   ┆ 4.0 ┆ 0   ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆ .0  ┆ .0  ┆ .0  ┆ 4.0 ┆     ┆     ┆ 783 ┆ 765 ┆ 168 ┆ 445 ┆ 370 ┆ 703 ┆ 407 ┆ 595 ┆ 028 ┆ 522 ┆ 158 ┆ 868 ┆ 318 ┆ 344 ┆ 018 ┆ 020 ┆ 221 ┆     ┆     ┆     ┆     ┆     ┆ 231 ┆ 100 ┆ 432 ┆ 136 ┆     │

In [3]:
corrs = df.select([
    pl.corr("reliability_index", col).alias(col)
    for col in acs_cols
])
corrs

shape: (1, 96)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ pop ┆ pop ┆ pop ┆ mal ┆ mal ┆ mal ┆ mal ┆ mal ┆ mal ┆ fem ┆ fem ┆ fem ┆ fem ┆ fem ┆ fem ┆ mal ┆ fem ┆ med ┆ dis ┆ dis ┆ dis ┆ edu ┆ edu ┆ edu ┆ edu ┆ edu ┆ pov ┆ pov ┆ med ┆ lab ┆ lab ┆ une ┆ hou ┆ hou ┆ hou ┆ med ┆ med ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ lan ┆ lim ┆ lim ┆ lim ┆ no_ ┆ no_ ┆ no_ ┆ veh ┆ veh ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ pop ┆ pop ┆ dis ┆ edu ┆ lim ┆ no_ ┆ pct ┆ pct ┆ sex ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct │
│ ula ┆ ula ┆ ula ┆ e_6 ┆ e_6 ┆ e_7 ┆ e_7 ┆ e_8 ┆ e_8 ┆ ale ┆ ale ┆ ale ┆ ale ┆ ale ┆ ale ┆ e_u ┆ ale ┆ ian ┆ abi ┆ abi ┆ abi ┆ _hi ┆ _ba ┆ _ma ┆ _pr ┆ _do ┆ ert ┆ ert ┆ ian ┆ or_ ┆ or_ ┆ mpl ┆ sin ┆ sin ┆ sin ┆ ian ┆ ian ┆ e_u ┆ e_w ┆ e_b ┆ e_a ┆ e_a ┆ e_p ┆ e_h ┆ e_o ┆ gua ┆ ite ┆ ite ┆ ite ┆ eng ┆ eng ┆ eng ┆ icl ┆ icl ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ ula ┆ ula ┆ abi ┆ _to ┆ ite ┆ eng ┆ _ma ┆ _fe ┆ _ra ┆ _65 ┆ _un ┆ _di ┆ _hi ┆ _ba ┆ _gr ┆ _po ┆ _un ┆ _ho ┆ _ho ┆ _wh ┆ _bl ┆ _as ┆ _hi ┆ _am ┆ _pa ┆ _ra ┆ _li ┆ _no ┆ _ve ┆ _si ┆ _sm ┆ _la ┆ _mo │
│ tio ┆ tio ┆ tio ┆ 5_6 ┆ 7_6 ┆ 0_7 ┆ 5_7 ┆ 0_8 ┆ 5_p ┆ _65 ┆ _67 ┆ _70 ┆ _75 ┆ _80 ┆ _85 ┆ nde ┆ _un ┆ _ag ┆ lit ┆ lit ┆ lit ┆ gh_ ┆ che ┆ ste ┆ ofe ┆ cto ┆ y_u ┆ y_b ┆ _ho ┆ for ┆ for ┆ oym ┆ g_u ┆ g_o ┆ g_v ┆ _ho ┆ _gr ┆ niv ┆ hit ┆ lac ┆ mer ┆ sia ┆ aci ┆ isp ┆ the ┆ ge_ ┆ d_e ┆ d_e ┆ d_e ┆ lis ┆ lis ┆ lis ┆ e_u ┆ e_n ┆ g_s ┆ g_1 ┆ g_2 ┆ g_3 ┆ g_5 ┆ g_1 ┆ g_2 ┆ g_5 ┆ g_m ┆ tio ┆ tio ┆ lit ┆ tal ┆ d_e ┆ lis ┆ le  ┆ mal ┆ tio ┆ _pl ┆ der ┆ sab ┆ gh_ ┆ che ┆ ad_ ┆ ver ┆ emp ┆ usi ┆ usi ┆ ite ┆ ack ┆ ian ┆ spa ┆ eri ┆ cif ┆ ce_ ┆ mit ┆ _en ┆ hic ┆ ngl ┆ all ┆ rge ┆ bil │
│ n_t ┆ n_m ┆ n_f ┆ 6   ┆ 9   ┆ 4   ┆ 9   ┆ 4   ┆ lus ┆ _66 ┆ _69 ┆ _74 ┆ _79 ┆ _84 ┆ _pl ┆ r_5 ┆ der ┆ e   ┆ y_u ┆ y_1 ┆ y_6 ┆ sch ┆ lor ┆ rs  ┆ ssi ┆ rat ┆ niv ┆ elo ┆ use ┆ ce  ┆ ce_ ┆ ent ┆ nit ┆ ccu ┆ aca ┆ me_ ┆ oss ┆ ers ┆ e   ┆ k   ┆ ica ┆ n   ┆ fic ┆ ani ┆ r   ┆ uni ┆ ngl ┆ ngl ┆ ngl ┆ h_5 ┆ h_1 ┆ h_6 ┆ niv ┆ one ┆ tru ┆ _un ┆ _un ┆ _4_ ┆ _9_ ┆ 0_1 ┆ 0_4 ┆ 0_p ┆ obi ┆ n_6 ┆ n_u ┆ y_t ┆ --- ┆ ngl ┆ h_t ┆ --- ┆ e   ┆ --- ┆ us  ┆ _5  ┆ ili ┆ sch ┆ lor ┆ deg ┆ ty  ┆ loy ┆ ng_ ┆ ng_ ┆ --- ┆ --- ┆ --- ┆ nic ┆ can ┆ ic_ ┆ oth ┆ ed_ ┆ gli ┆ le_ ┆ e_f ┆ _mu ┆ _mu ┆ e_h │
│ ota ┆ ale ┆ ema ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ us  ┆ --- ┆ _5  ┆ --- ┆ nde ┆ 8_6 ┆ 5_p ┆ ool ┆ s   ┆ --- ┆ ona ┆ e   ┆ ers ┆ w   ┆ hol ┆ --- ┆ civ ┆ _ci ┆ s   ┆ pie ┆ nt  ┆ val ┆ _re ┆ e   ┆ --- ┆ --- ┆ n_i ┆ --- ┆ _is ┆ c   ┆ --- ┆ ver ┆ ish ┆ ish ┆ ish ┆ _17 ┆ 8_6 ┆ 5_p ┆ ers ┆ --- ┆ ctu ┆ it  ┆ it  ┆ uni ┆ uni ┆ 9_u ┆ 9_u ┆ lus ┆ le_ ┆ 5_p ┆ nde ┆ ota ┆ f64 ┆ ish ┆ ota ┆ f64 ┆ --- ┆ f64 ┆ --- ┆ --- ┆ ty  ┆ ool ┆ s   ┆ ree ┆ --- ┆ men ┆ occ ┆ vac ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ _in ┆ isl ┆ er  ┆ eng ┆ sh  ┆ non ┆ ami ┆ lti ┆ lti ┆ ome │
│ l   ┆ --- ┆ le  ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ f64 ┆ --- ┆ f64 ┆ r_1 ┆ 4   ┆ lus ┆ --- ┆ --- ┆ f64 ┆ l   ┆ --- ┆ e   ┆ --- ┆ d_i ┆ f64 ┆ ili ┆ vil ┆ --- ┆ d   ┆ --- ┆ ue  ┆ nt  ┆ --- ┆ f64 ┆ f64 ┆ ndi ┆ f64 ┆ lan ┆ --- ┆ f64 ┆ se  ┆ _5_ ┆ _18 ┆ _65 ┆ --- ┆ 4   ┆ lus ┆ e   ┆ f64 ┆ re_ ┆ --- ┆ --- ┆ t   ┆ t   ┆ nit ┆ nit ┆ _un ┆ hom ┆ lus ┆ r_5 ┆ l   ┆     ┆ _to ┆ l   ┆     ┆ f64 ┆     ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆ t   ┆ upi ┆ ant ┆     ┆     ┆     ┆ f64 ┆ dia ┆ and ┆ --- ┆ lis ┆ --- ┆ e   ┆ ly  ┆ _fa ┆ _fa ┆ --- │
│ --- ┆ f64 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆     ┆ 8   ┆ --- ┆ --- ┆ f64 ┆ f64 ┆     ┆ --- ┆ f64 ┆ --- ┆ f64 ┆ nco ┆     ┆ an  ┆ ian ┆ f64 ┆ --- ┆ f64 ┆ --- ┆ --- ┆ f64 ┆     ┆     ┆ an  ┆     ┆ der ┆ f64 ┆     ┆ --- ┆ 17  ┆ _64 ┆ _pl ┆ f64 ┆ --- ┆ --- ┆ --- ┆     ┆ uni ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ it  ┆ e   ┆ --- ┆ --- ┆ --- ┆     ┆ tal ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆ --- ┆ ed  ┆ --- ┆     ┆     ┆     ┆     ┆ n   ┆ er  ┆ f64 ┆ h   ┆ f64 ┆ --- ┆ --- ┆ mil ┆ mil ┆ f64 │
│ f64 ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ f64 ┆ f64 ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆     ┆ me  ┆     ┆ --- ┆ --- ┆     ┆ f64 ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆ --- ┆     ┆ --- ┆     ┆     ┆ f64 ┆ --- ┆ --- ┆ us  ┆     ┆ f64 ┆ f64 ┆ f64 ┆     ┆ ver ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆     ┆ --- ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ f64 ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ f64 ┆ f64 ┆ y   ┆ y   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ se  ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆ f64 ┆     ┆     ┆     ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 0.1 ┆ 0.1 ┆ 0.1 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.2 ┆ 0.3 ┆ 0.2 ┆ 0.2 ┆ 0.1 ┆ 0.1 ┆ 0.0 ┆ 0.1 ┆ 0.1 ┆ 0.1 ┆ 0.0 ┆ 0.1 ┆ -0. ┆ 0.1 ┆ 0.3 ┆ 0.1 ┆ -0. ┆ 0.0 ┆ -0. ┆ 0.2 ┆ 0.0 ┆ 0.2 ┆ 0.0 ┆ 0.1 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ -0. ┆ 0.1 ┆ 0.2 ┆ 0.0 ┆ 0.1 ┆ 0.2 ┆ 0.2 ┆ 0.1 ┆ 0.1 ┆ 0.2 ┆ 0.2 ┆ -0. ┆ -0. ┆ 0.0 ┆ -0. ┆ 0.1 ┆ 0.0 ┆ 0.0 ┆ -0. ┆ 0.1 ┆ -0. ┆ -0. ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.3 ┆ 0.3 ┆ 0.1 ┆ 0.0 ┆ 0.3 ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.2 ┆ 0.2 ┆ -0. ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.1 ┆ 0.1 ┆ 0.3 ┆ 0.2 ┆ -0. │
│ 217 ┆ 012 ┆ 376 ┆ 098 ┆ 089 ┆ 122 ┆ 112 ┆ 069 ┆ 042 ┆ 036 ┆ 061 ┆ 049 ┆ 070 ┆ 044 ┆ 243 ┆ 604 ┆ 488 ┆ 327 ┆ 041 ┆ 037 ┆ 106 ┆ 226 ┆ 766 ┆ 003 ┆ 372 ┆ 914 ┆ 184 ┆ 382 ┆ 875 ┆ 844 ┆ 843 ┆ 126 ┆ 241 ┆ 497 ┆ 239 ┆ 848 ┆ 229 ┆ 217 ┆ 004 ┆ 683 ┆ 093 ┆ 616 ┆ 293 ┆ 378 ┆ 389 ┆ 229 ┆ 423 ┆ 417 ┆ 032 ┆ 631 ┆ 340 ┆ 018 ┆ 497 ┆ 158 ┆ 241 ┆ 782 ┆ 816 ┆ 168 ┆ 127 ┆ 375 ┆ 599 ┆ 880 ┆ 307 ┆ 103 ┆ 634 ┆ 085 ┆ 546 ┆ 483 ┆ 449 ┆ 106 ┆ 068 ┆ 097 ┆ 315 ┆ 127 ┆ 249 ┆ 380 ┆ 217 ┆ 418 ┆ 250 ┆ 315 ┆ 021 ┆ 302 ┆ 221 ┆ 744 ┆ 662 ┆ 548 ┆ 094 ┆ 167 ┆ 081 ┆ 484 ┆ 515 ┆ 738 ┆ 805 ┆ 230 ┆ 985 ┆ 358 │
│ 48  ┆ 12  ┆     ┆ 282 ┆ 324 ┆ 716 ┆ 12  ┆ 334 ┆ 165 ┆ 273 ┆ 535 ┆ 124 ┆ 42  ┆ 492 ┆ 58  ┆ 77  ┆ 05  ┆ 756 ┆ 755 ┆ 297 ┆ 759 ┆ 815 ┆ 57  ┆ 91  ┆ 01  ┆ 61  ┆ 25  ┆ 94  ┆ 15  ┆ 88  ┆ 94  ┆ 96  ┆ 79  ┆ 64  ┆ 024 ┆ 1   ┆ 85  ┆ 48  ┆ 077 ┆ 67  ┆ 216 ┆ 18  ┆ 05  ┆ 35  ┆ 77  ┆ 43  ┆ 63  ┆ 85  ┆ 93  ┆ 78  ┆ 23  ┆ 743 ┆ 64  ┆ 25  ┆ 79  ┆ 16  ┆ 7   ┆ 15  ┆ 31  ┆ 8   ┆ 94  ┆ 48  ┆ 432 ┆ 219 ┆ 63  ┆ 096 ┆ 81  ┆ 96  ┆     ┆ 89  ┆ 9   ┆ 8   ┆ 853 ┆ 15  ┆ 235 ┆ 678 ┆ 93  ┆ 88  ┆ 67  ┆ 67  ┆ 17  ┆ 117 ┆ 572 ┆ 92  ┆ 87  ┆ 11  ┆ 498 ┆ 89  ┆ 56  ┆ 99  ┆ 83  ┆ 16  ┆ 08  ┆ 85  ┆ 35  ┆ 876 │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [9]:
acs_corr_matrix = df.select(acs_cols).corr()


acs_corr_matrix

shape: (96, 96)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ pop ┆ pop ┆ pop ┆ mal ┆ mal ┆ mal ┆ mal ┆ mal ┆ mal ┆ fem ┆ fem ┆ fem ┆ fem ┆ fem ┆ fem ┆ mal ┆ fem ┆ med ┆ dis ┆ dis ┆ dis ┆ edu ┆ edu ┆ edu ┆ edu ┆ edu ┆ pov ┆ pov ┆ med ┆ lab ┆ lab ┆ une ┆ hou ┆ hou ┆ hou ┆ med ┆ med ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ lan ┆ lim ┆ lim ┆ lim ┆ no_ ┆ no_ ┆ no_ ┆ veh ┆ veh ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ pop ┆ pop ┆ dis ┆ edu ┆ lim ┆ no_ ┆ pct ┆ pct ┆ sex ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct │
│ ula ┆ ula ┆ ula ┆ e_6 ┆ e_6 ┆ e_7 ┆ e_7 ┆ e_8 ┆ e_8 ┆ ale ┆ ale ┆ ale ┆ ale ┆ ale ┆ ale ┆ e_u ┆ ale ┆ ian ┆ abi ┆ abi ┆ abi ┆ _hi ┆ _ba ┆ _ma ┆ _pr ┆ _do ┆ ert ┆ ert ┆ ian ┆ or_ ┆ or_ ┆ mpl ┆ sin ┆ sin ┆ sin ┆ ian ┆ ian ┆ e_u ┆ e_w ┆ e_b ┆ e_a ┆ e_a ┆ e_p ┆ e_h ┆ e_o ┆ gua ┆ ite ┆ ite ┆ ite ┆ eng ┆ eng ┆ eng ┆ icl ┆ icl ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ ula ┆ ula ┆ abi ┆ _to ┆ ite ┆ eng ┆ _ma ┆ _fe ┆ _ra ┆ _65 ┆ _un ┆ _di ┆ _hi ┆ _ba ┆ _gr ┆ _po ┆ _un ┆ _ho ┆ _ho ┆ _wh ┆ _bl ┆ _as ┆ _hi ┆ _am ┆ _pa ┆ _ra ┆ _li ┆ _no ┆ _ve ┆ _si ┆ _sm ┆ _la ┆ _mo │
│ tio ┆ tio ┆ tio ┆ 5_6 ┆ 7_6 ┆ 0_7 ┆ 5_7 ┆ 0_8 ┆ 5_p ┆ _65 ┆ _67 ┆ _70 ┆ _75 ┆ _80 ┆ _85 ┆ nde ┆ _un ┆ _ag ┆ lit ┆ lit ┆ lit ┆ gh_ ┆ che ┆ ste ┆ ofe ┆ cto ┆ y_u ┆ y_b ┆ _ho ┆ for ┆ for ┆ oym ┆ g_u ┆ g_o ┆ g_v ┆ _ho ┆ _gr ┆ niv ┆ hit ┆ lac ┆ mer ┆ sia ┆ aci ┆ isp ┆ the ┆ ge_ ┆ d_e ┆ d_e ┆ d_e ┆ lis ┆ lis ┆ lis ┆ e_u ┆ e_n ┆ g_s ┆ g_1 ┆ g_2 ┆ g_3 ┆ g_5 ┆ g_1 ┆ g_2 ┆ g_5 ┆ g_m ┆ tio ┆ tio ┆ lit ┆ tal ┆ d_e ┆ lis ┆ le  ┆ mal ┆ tio ┆ _pl ┆ der ┆ sab ┆ gh_ ┆ che ┆ ad_ ┆ ver ┆ emp ┆ usi ┆ usi ┆ ite ┆ ack ┆ ian ┆ spa ┆ eri ┆ cif ┆ ce_ ┆ mit ┆ _en ┆ hic ┆ ngl ┆ all ┆ rge ┆ bil │
│ n_t ┆ n_m ┆ n_f ┆ 6   ┆ 9   ┆ 4   ┆ 9   ┆ 4   ┆ lus ┆ _66 ┆ _69 ┆ _74 ┆ _79 ┆ _84 ┆ _pl ┆ r_5 ┆ der ┆ e   ┆ y_u ┆ y_1 ┆ y_6 ┆ sch ┆ lor ┆ rs  ┆ ssi ┆ rat ┆ niv ┆ elo ┆ use ┆ ce  ┆ ce_ ┆ ent ┆ nit ┆ ccu ┆ aca ┆ me_ ┆ oss ┆ ers ┆ e   ┆ k   ┆ ica ┆ n   ┆ fic ┆ ani ┆ r   ┆ uni ┆ ngl ┆ ngl ┆ ngl ┆ h_5 ┆ h_1 ┆ h_6 ┆ niv ┆ one ┆ tru ┆ _un ┆ _un ┆ _4_ ┆ _9_ ┆ 0_1 ┆ 0_4 ┆ 0_p ┆ obi ┆ n_6 ┆ n_u ┆ y_t ┆ --- ┆ ngl ┆ h_t ┆ --- ┆ e   ┆ --- ┆ us  ┆ _5  ┆ ili ┆ sch ┆ lor ┆ deg ┆ ty  ┆ loy ┆ ng_ ┆ ng_ ┆ --- ┆ --- ┆ --- ┆ nic ┆ can ┆ ic_ ┆ oth ┆ ed_ ┆ gli ┆ le_ ┆ e_f ┆ _mu ┆ _mu ┆ e_h │
│ ota ┆ ale ┆ ema ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ us  ┆ --- ┆ _5  ┆ --- ┆ nde ┆ 8_6 ┆ 5_p ┆ ool ┆ s   ┆ --- ┆ ona ┆ e   ┆ ers ┆ w   ┆ hol ┆ --- ┆ civ ┆ _ci ┆ s   ┆ pie ┆ nt  ┆ val ┆ _re ┆ e   ┆ --- ┆ --- ┆ n_i ┆ --- ┆ _is ┆ c   ┆ --- ┆ ver ┆ ish ┆ ish ┆ ish ┆ _17 ┆ 8_6 ┆ 5_p ┆ ers ┆ --- ┆ ctu ┆ it  ┆ it  ┆ uni ┆ uni ┆ 9_u ┆ 9_u ┆ lus ┆ le_ ┆ 5_p ┆ nde ┆ ota ┆ f64 ┆ ish ┆ ota ┆ f64 ┆ --- ┆ f64 ┆ --- ┆ --- ┆ ty  ┆ ool ┆ s   ┆ ree ┆ --- ┆ men ┆ occ ┆ vac ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ _in ┆ isl ┆ er  ┆ eng ┆ sh  ┆ non ┆ ami ┆ lti ┆ lti ┆ ome │
│ l   ┆ --- ┆ le  ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ f64 ┆ --- ┆ f64 ┆ r_1 ┆ 4   ┆ lus ┆ --- ┆ --- ┆ f64 ┆ l   ┆ --- ┆ e   ┆ --- ┆ d_i ┆ f64 ┆ ili ┆ vil ┆ --- ┆ d   ┆ --- ┆ ue  ┆ nt  ┆ --- ┆ f64 ┆ f64 ┆ ndi ┆ f64 ┆ lan ┆ --- ┆ f64 ┆ se  ┆ _5_ ┆ _18 ┆ _65 ┆ --- ┆ 4   ┆ lus ┆ e   ┆ f64 ┆ re_ ┆ --- ┆ --- ┆ t   ┆ t   ┆ nit ┆ nit ┆ _un ┆ hom ┆ lus ┆ r_5 ┆ l   ┆     ┆ _to ┆ l   ┆     ┆ f64 ┆     ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ f64 ┆ t   ┆ upi ┆ ant ┆     ┆     ┆     ┆ f64 ┆ dia ┆ and ┆ --- ┆ lis ┆ --- ┆ e   ┆ ly  ┆ _fa ┆ _fa ┆ --- │
│ --- ┆ f64 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆     ┆ 8   ┆ --- ┆ --- ┆ f64 ┆ f64 ┆     ┆ --- ┆ f64 ┆ --- ┆ f64 ┆ nco ┆     ┆ an  ┆ ian ┆ f64 ┆ --- ┆ f64 ┆ --- ┆ --- ┆ f64 ┆     ┆     ┆ an  ┆     ┆ der ┆ f64 ┆     ┆ --- ┆ 17  ┆ _64 ┆ _pl ┆ f64 ┆ --- ┆ --- ┆ --- ┆     ┆ uni ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ it  ┆ e   ┆ --- ┆ --- ┆ --- ┆     ┆ tal ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆     ┆ --- ┆ ed  ┆ --- ┆     ┆     ┆     ┆     ┆ n   ┆ er  ┆ f64 ┆ h   ┆ f64 ┆ --- ┆ --- ┆ mil ┆ mil ┆ f64 │
│ f64 ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ f64 ┆ f64 ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆     ┆ me  ┆     ┆ --- ┆ --- ┆     ┆ f64 ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆ --- ┆     ┆ --- ┆     ┆     ┆ f64 ┆ --- ┆ --- ┆ us  ┆     ┆ f64 ┆ f64 ┆ f64 ┆     ┆ ver ┆     ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆     ┆ --- ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ f64 ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ f64 ┆ f64 ┆ y   ┆ y   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ f64 ┆     ┆     ┆     ┆ f64 ┆ f64 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ se  ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆ f64 ┆     ┆     ┆     ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 1.0 ┆ 0.9 ┆ 0.9 ┆ 0.4 ┆ 0.4 ┆ 0.4 ┆ 0.4 ┆ 0.3 ┆ 0.2 ┆ 0.4 ┆ 0.4 ┆ 0.5 ┆ 0.4 ┆ 0.4 ┆ 0.3 ┆ 0.5 ┆ 0.5 ┆ -0. ┆ 0.3 ┆ 0.5 ┆ 0.5 ┆ 0.6 ┆ 0.7 ┆ 0.5 ┆ 0.3 ┆ 0.2 ┆ 0.9 ┆ 0.2 ┆ NaN ┆ 0.9 ┆ 0.9 ┆ 0.3 ┆ 0.7 ┆ 0.9 ┆ -0. ┆ NaN ┆ NaN ┆ 1.0 ┆ 0.8 ┆ -0. ┆ -0. ┆ 0.3 ┆ 0.0 ┆ 0.2 ┆ 0.1 ┆ 0.9 ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.9 ┆ 0.1 ┆ 0.7 ┆ 0.4 ┆ -0. ┆ 0.2 ┆ 0.3 ┆ 0.2 ┆ 0.2 ┆ 0.1 ┆ 0.0 ┆ 0.6 ┆ 0.6 ┆ 0.6 ┆ 0.8 ┆ 0.0 ┆ -0. ┆ 0.0 ┆ -0. ┆ 0.0 ┆ -0. ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.2 ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.3 ┆ -0. ┆ 0.2 ┆ -0. ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.0 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.2 ┆ -0. ┆ -0. ┆ -0. │
│     ┆ 800 ┆ 795 ┆ 105 ┆ 768 ┆ 717 ┆ 314 ┆ 693 ┆ 925 ┆ 136 ┆ 776 ┆ 265 ┆ 650 ┆ 031 ┆ 586 ┆ 655 ┆ 706 ┆ 099 ┆ 701 ┆ 408 ┆ 277 ┆ 478 ┆ 069 ┆ 731 ┆ 045 ┆ 794 ┆ 819 ┆ 362 ┆     ┆ 541 ┆ 541 ┆ 276 ┆ 873 ┆ 292 ┆ 175 ┆     ┆     ┆     ┆ 688 ┆ 037 ┆ 047 ┆ 333 ┆ 846 ┆ 084 ┆ 705 ┆ 978 ┆ 015 ┆ 216 ┆ 128 ┆ 009 ┆ 011 ┆ 236 ┆ 292 ┆ 133 ┆ 873 ┆ 972 ┆ 012 ┆ 169 ┆ 277 ┆ 970 ┆ 105 ┆ 100 ┆ 534 ┆ 916 ┆ 592 ┆ 414 ┆ 698 ┆ 177 ┆ 002 ┆ 176 ┆ 017 ┆ 091 ┆ 124 ┆ 154 ┆ 069 ┆ 171 ┆ 039 ┆ 873 ┆ 214 ┆ 200 ┆ 946 ┆ 394 ┆ 090 ┆ 214 ┆ 657 ┆ 047 ┆ 108 ┆ 226 ┆ 010 ┆ 038 ┆ 019 ┆ 226 ┆ 464 ┆ 140 ┆ 003 ┆ 078 │
│     ┆ 83  ┆ 75  ┆ 22  ┆ 17  ┆ 72  ┆ 18  ┆ 61  ┆ 66  ┆ 41  ┆ 77  ┆ 04  ┆ 27  ┆ 41  ┆ 72  ┆ 74  ┆ 28  ┆ 61  ┆ 51  ┆ 88  ┆ 6   ┆ 4   ┆ 27  ┆ 01  ┆ 93  ┆ 61  ┆ 38  ┆ 97  ┆     ┆ 91  ┆ 13  ┆ 41  ┆ 75  ┆ 3   ┆ 534 ┆     ┆     ┆     ┆ 14  ┆ 384 ┆ 25  ┆ 77  ┆ 68  ┆ 22  ┆ 45  ┆ 84  ┆ 546 ┆ 42  ┆ 82  ┆ 688 ┆ 559 ┆ 99  ┆ 3   ┆ 45  ┆ 75  ┆ 98  ┆ 078 ┆ 74  ┆ 33  ┆ 99  ┆ 32  ┆ 48  ┆ 12  ┆ 67  ┆ 48  ┆ 45  ┆ 99  ┆ 22  ┆ 321 ┆ 27  ┆ 627 ┆ 29  ┆ 747 ┆ 14  ┆ 484 ┆ 686 ┆ 46  ┆ 07  ┆ 939 ┆ 907 ┆ 97  ┆ 697 ┆ 1   ┆ 001 ┆ 49  ┆ 466 ┆ 179 ┆ 04  ┆ 864 ┆ 26  ┆ 906 ┆ 756 ┆ 31  ┆ 468 ┆ 835 ┆ 318 │
│ 0.9 ┆ 1.0 ┆ 0.9 ┆ 0.4 ┆ 0.4 ┆ 0.4 ┆ 0.4 ┆ 0.3 ┆ 0.2 ┆ 0.4 ┆ 0.4 ┆ 0.4 ┆ 0.4 ┆ 0.3 ┆ 0.3 ┆ 0.5 ┆ 0.5 ┆ -0. ┆ 0.3 ┆ 0.5 ┆ 0.5 ┆ 0.6 ┆ 0.6 ┆ 0.5 ┆ 0.2 ┆ 0.2 ┆ 0.9 ┆ 0.2 ┆ NaN ┆ 0.9 ┆ 0.9 ┆ 0.3 ┆ 0.7 ┆ 0.9 ┆ -0. ┆ NaN ┆ NaN ┆ 0.9 ┆ 0.8 ┆ -0. ┆ -0. ┆ 0.3 ┆ 0.0 ┆ 0.2 ┆ 0.1 ┆ 0.9 ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.9 ┆ 0.0 ┆ 0.7 ┆ 0.4 ┆ -0. ┆ 0.1 ┆ 0.2 ┆ 0.2 ┆ 0.1 ┆ 0.0 ┆ 0.0 ┆ 0.6 ┆ 0.6 ┆ 0.6 ┆ 0.8 ┆ 0.0 ┆ 0.0 ┆ 0.1 ┆ -0. ┆ 0.1 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.1 ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.3 ┆ -0. ┆ 0.2 ┆ -0. ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.0 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.1 ┆ -0. ┆ -0. ┆ -0. │
│ 800 ┆     ┆ 201 ┆ 259 ┆ 870 ┆ 851 ┆ 374 ┆ 658 ┆ 916 ┆ 012 ┆ 578 ┆ 936 ┆ 243 ┆ 683 ┆ 086 ┆ 644 ┆ 185 ┆ 078 ┆ 654 ┆ 428 ┆ 142 ┆ 554 ┆ 863 ┆ 457 ┆ 902 ┆ 725 ┆ 597 ┆ 147 ┆     ┆ 350 ┆ 35  ┆ 055 ┆ 728 ┆ 035 ┆ 155 ┆     ┆     ┆ 800 ┆ 638 ┆ 066 ┆ 034 ┆ 074 ┆ 822 ┆ 044 ┆ 647 ┆ 795 ┆ 018 ┆ 190 ┆ 096 ┆ 002 ┆ 007 ┆ 163 ┆ 035 ┆ 923 ┆ 728 ┆ 448 ┆ 026 ┆ 926 ┆ 910 ┆ 751 ┆ 914 ┆ 944 ┆ 863 ┆ 701 ┆ 286 ┆ 344 ┆ 541 ┆ 139 ┆ 009 ┆ 991 ┆ 199 ┆ 924 ┆ 125 ┆ 006 ┆ 054 ┆ 153 ┆ 910 ┆ 689 ┆ 231 ┆ 212 ┆ 696 ┆ 369 ┆ 301 ┆ 237 ┆ 467 ┆ 047 ┆ 099 ┆ 204 ┆ 011 ┆ 038 ┆ 016 ┆ 242 ┆ 976 ┆ 167 ┆ 024 ┆ 040 │
│ 83  ┆     ┆ 34  ┆ 62  ┆ 46  ┆ 35  ┆ 12  ┆ 79  ┆ 07  ┆ 32  ┆ 35  ┆ 71  ┆ 65  ┆ 89  ┆ 01  ┆ 75  ┆ 91  ┆ 452 ┆ 6   ┆ 42  ┆ 88  ┆ 77  ┆ 11  ┆ 23  ┆ 7   ┆ 5   ┆ 55  ┆ 98  ┆     ┆ 42  ┆     ┆ 78  ┆ 61  ┆ 36  ┆ 792 ┆     ┆     ┆ 83  ┆ 61  ┆ 736 ┆ 257 ┆ 18  ┆ 89  ┆ 67  ┆ 88  ┆ 2   ┆ 067 ┆ 52  ┆ 49  ┆ 063 ┆ 418 ┆ 75  ┆ 36  ┆ 18  ┆ 61  ┆ 03  ┆ 515 ┆ 09  ┆ 79  ┆ 72  ┆ 07  ┆ 47  ┆ 61  ┆ 12  ┆ 47  ┆ 85  ┆ 6   ┆ 56  ┆ 57  ┆ 63  ┆ 163 ┆ 02  ┆ 293 ┆ 217 ┆ 133 ┆ 979 ┆ 97  ┆ 95  ┆ 405 ┆ 009 ┆ 94  ┆ 694 ┆ 31  ┆ 87  ┆ 16  ┆ 673 ┆ 644 ┆ 77  ┆ 52  ┆ 478 ┆ 659 ┆ 749 ┆ 56  ┆ 626 ┆ 778 ┆ 493 │
│ 0.9 ┆ 0.9 ┆ 1.0 ┆ 0.3 ┆ 0.4 ┆ 0.4 ┆ 0.4 ┆ 0.3 ┆ 0.2 ┆ 0.4 ┆ 0.4 ┆ 0.5 ┆ 0.4 ┆ 0.4 ┆ 0.3 ┆ 0.5 ┆ 0.6 ┆ -0. ┆ 0.3 ┆ 0.5 ┆ 0.5 ┆ 0.6 ┆ 0.6 ┆ 0.5 ┆ 0.3 ┆ 0.2 ┆ 0.9 ┆ 0.2 ┆ NaN ┆ 0.9 ┆ 0.9 ┆ 0.3 ┆ 0.7 ┆ 0.9 ┆ -0. ┆ NaN ┆ NaN ┆ 0.9 ┆ 0.8 ┆ -0. ┆ -0. ┆ 0.3 ┆ 0.0 ┆ 0.2 ┆ 0.1 ┆ 0.9 ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.9 ┆ 0.1 ┆ 0.7 ┆ 0.5 ┆ 0.0 ┆ 0.2 ┆ 0.3 ┆ 0.3 ┆ 0.2 ┆ 0.1 ┆ 0.0 ┆ 0.6 ┆ 0.6 ┆ 0.6 ┆ 0.8 ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.1 ┆ -0. ┆ -0. ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.2 ┆ 0.1 ┆ -0. ┆ -0. ┆ 0.4 ┆ -0. ┆ 0.1 ┆ -0. ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.0 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.2 ┆ -0. ┆ 0.0 ┆ -0. │
│ 795 ┆ 201 ┆     ┆ 782 ┆ 471 ┆ 390 ┆ 078 ┆ 578 ┆ 816 ┆ 094 ┆ 783 ┆ 383 ┆ 873 ┆ 219 ┆ 948 ┆ 437 ┆ 001 ┆ 116 ┆ 598 ┆ 169 ┆ 199 ┆ 138 ┆ 991 ┆ 775 ┆ 067 ┆ 751 ┆ 645 ┆ 484 ┆     ┆ 348 ┆ 347 ┆ 366 ┆ 701 ┆ 175 ┆ 188 ┆     ┆     ┆ 795 ┆ 385 ┆ 006 ┆ 058 ┆ 461 ┆ 836 ┆ 039 ┆ 694 ┆ 759 ┆ 012 ┆ 233 ┆ 156 ┆ 017 ┆ 015 ┆ 301 ┆ 175 ┆ 300 ┆ 701 ┆ 302 ┆ 030 ┆ 328 ┆ 515 ┆ 072 ┆ 213 ┆ 213 ┆ 178 ┆ 854 ┆ 634 ┆ 224 ┆ 505 ┆ 208 ┆ 005 ┆ 166 ┆ 669 ┆ 176 ┆ 119 ┆ 366 ┆ 082 ┆ 182 ┆ 086 ┆ 023 ┆ 189 ┆ 181 ┆ 039 ┆ 403 ┆ 791 ┆ 181 ┆ 823 ┆ 045 ┆ 112 ┆ 238 ┆ 009 ┆ 036 ┆ 022 ┆ 201 ┆ 858 ┆ 107 ┆ 175 ┆ 113 │
│ 75  ┆ 34  ┆     ┆ 25  ┆ 06  ┆ 91  ┆ 37  ┆ 94  ┆ 62  ┆ 15  ┆ 8   ┆ 77  ┆ 24  ┆ 64  ┆ 12  ┆ 31  ┆ 54  ┆ 99  ┆ 76  ┆ 55  ┆ 78  ┆ 12  ┆ 07  ┆ 6   ┆ 31  ┆ 15  ┆ 42  ┆ 73  ┆     ┆ 48  ┆ 37  ┆ 81  ┆ 1   ┆ 27  ┆ 399 ┆     ┆     ┆ 75  ┆ 63  ┆ 147 ┆ 489 ┆ 3   ┆ 4   ┆ 67  ┆ 52  ┆ 73  ┆ 363 ┆ 85  ┆ 33  ┆ 016 ┆ 282 ┆ 53  ┆ 27  ┆ 36  ┆ 1   ┆ 66  ┆ 31  ┆ 36  ┆ 44  ┆ 42  ┆ 51  ┆ 78  ┆ 82  ┆ 17  ┆ 73  ┆ 55  ┆ 25  ┆ 16  ┆ 545 ┆ 901 ┆ 01  ┆ 813 ┆ 13  ┆ 9   ┆ 207 ┆ 646 ┆ 78  ┆ 06  ┆ 542 ┆ 512 ┆ 92  ┆ 992 ┆ 39  ┆ 146 ┆ 51  ┆ 33  ┆ 43  ┆ 4   ┆ 759 ┆ 486 ┆ 385 ┆ 359 ┆ 15  ┆ 267 ┆ 25  ┆ 439 │
│ 0.4 ┆ 0.4 ┆ 0.3 ┆ 1.0 ┆ 0.3 ┆ 0.3 ┆ 0.3 ┆ 0.2 ┆ 0.2 ┆ 0.3 ┆ 0.3 ┆ 0.3 ┆ 0.2 ┆ 0.2 ┆ 0.1 ┆ 0.1 ┆ 0.2 ┆ 0.2 ┆ 0.1 ┆ 0.2 ┆ 0.4 ┆ 0.4 ┆ 0.3 ┆ 0.2 ┆ 0.0 ┆ 0.0 ┆ 0.4 ┆ -0. ┆ NaN ┆ 0.3 ┆ 0.3 ┆ 0.0 ┆ 0.4 ┆ 0.4 ┆ 0.1 ┆ NaN ┆ NaN ┆ 0.4 ┆ 0.4 ┆ -0. ┆ 0.0 ┆ -0. ┆ 0.0 ┆ -0. ┆ 0.0 ┆ 0.4 ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.4 ┆ -0. ┆ 0.4 ┆ 0.1 ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.1 ┆ 0.5 ┆ 0.2 ┆ 0.3 ┆ 0.4 ┆ -0. ┆ -0. ┆ 0.1 ┆ -0. ┆ 0.1 ┆ 0.2 ┆ -0. ┆ 0.1 ┆ 0.0 ┆ 0.0 ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ -0. ┆ 0.2 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.1 │
│ 105 ┆ 259 ┆ 782 ┆     ┆ 464 ┆ 228 ┆ 007 ┆ 816 ┆ 110 ┆ 269 ┆ 376 ┆ 466 ┆ 851 ┆ 179 ┆ 686 ┆ 762 ┆ 163 ┆ 841 ┆ 788 ┆ 573 ┆ 116 ┆ 456 ┆ 153 ┆ 021 ┆ 969 ┆ 548 ┆ 281 ┆ 090 ┆     ┆ 656 ┆ 660 ┆ 146 ┆ 441 ┆ 205 ┆ 007 ┆     ┆     ┆ 105 ┆ 640 ┆ 156 ┆ 188 ┆ 030 ┆ 412 ┆ 047 ┆ 430 ┆ 133 ┆ 004 ┆ 041 ┆ 039 ┆ 042 ┆ 026 ┆ 008 ┆ 205 ┆ 108 ┆ 441 ┆ 643 ┆ 142 ┆ 051 ┆ 628 ┆ 127 ┆ 066 ┆ 108 ┆ 877 ┆ 401 ┆ 276 ┆ 936 ┆ 408 ┆ 035 ┆ 020 ┆ 264 ┆ 126 ┆ 104 ┆ 632 ┆ 058 ┆ 335 ┆ 022 ┆ 503 ┆ 061 ┆ 283 ┆ 189 ┆ 276 ┆ 027 ┆ 836 ┆ 217 ┆ 134 ┆ 147 ┆ 032 ┆ 245 ┆ 023 ┆ 052 ┆ 020 ┆ 257 ┆ 231 ┆ 252 ┆ 203 ┆ 125 │
│ 22  ┆ 62  ┆ 25  ┆     ┆ 96  ┆ 52  ┆ 13  ┆ 15  ┆ 74  ┆ 91  ┆ 66  ┆ 4   ┆ 62  ┆ 47  ┆ 33  ┆ 34  ┆ 39  ┆ 86  ┆ 48  ┆ 37  ┆ 37  ┆ 89  ┆ 67  ┆ 16  ┆ 32  ┆ 92  ┆ 36  ┆ 955 ┆     ┆ 07  ┆ 18  ┆ 8   ┆ 24  ┆ 02  ┆ 18  ┆     ┆     ┆ 22  ┆ 15  ┆ 582 ┆ 52  ┆ 059 ┆ 23  ┆ 977 ┆ 94  ┆ 74  ┆ 799 ┆ 279 ┆ 13  ┆ 83  ┆ 577 ┆ 957 ┆ 02  ┆ 865 ┆ 24  ┆ 77  ┆ 083 ┆ 652 ┆ 15  ┆ 91  ┆ 347 ┆ 696 ┆ 72  ┆ 7   ┆ 05  ┆ 36  ┆ 76  ┆ 768 ┆ 026 ┆ 49  ┆ 449 ┆ 69  ┆ 6   ┆ 571 ┆ 23  ┆ 23  ┆ 89  ┆ 434 ┆ 51  ┆ 409 ┆ 28  ┆ 628 ┆ 52  ┆ 364 ┆ 666 ┆ 674 ┆ 107 ┆ 49  ┆ 783 ┆ 556 ┆ 686 ┆ 451 ┆ 74  ┆ 511 ┆ 552 ┆ 18  │
│ 0.4 ┆ 0.4 ┆ 0.4 ┆ 0.3 ┆ 1.0 ┆ 0.4 ┆ 0.3 ┆ 0.3 ┆ 0.2 ┆ 0.3 ┆ 0.4 ┆ 0.4 ┆ 0.3 ┆ 0.2 ┆ 0.2 ┆ 0.1 ┆ 0.2 ┆ 0.3 ┆ 0.1 ┆ 0.2 ┆ 0.4 ┆ 0.4 ┆ 0.3 ┆ 0.3 ┆ 0.1 ┆ 0.1 ┆ 0.4 ┆ -0. ┆ NaN ┆ 0.4 ┆ 0.4 ┆ 0.0 ┆ 0.5 ┆ 0.4 ┆ 0.1 ┆ NaN ┆ NaN ┆ 0.4 ┆ 0.5 ┆ -0. ┆ 0.0 ┆ -0. ┆ -0. ┆ -0. ┆ 0.1 ┆ 0.4 ┆ -0. ┆ 0.0 ┆ -0. ┆ 0.0 ┆ -0. ┆ 0.0 ┆ 0.4 ┆ -0. ┆ 0.5 ┆ 0.1 ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.2 ┆ 0.6 ┆ 0.2 ┆ 0.4 ┆ 0.5 ┆ 0.0 ┆ 0.0 ┆ 0.1 ┆ -0. ┆ 0.1 ┆ 0.3 ┆ -0. ┆ 0.1 ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.3 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.1 │
│ 768 ┆ 870 ┆ 471 ┆ 464 ┆     ┆ 059 ┆ 639 ┆ 080 ┆ 008 ┆ 877 ┆ 722 ┆ 094 ┆ 186 ┆ 959 ┆ 058 ┆ 619 ┆ 083 ┆ 472 ┆ 917 ┆ 679 ┆ 440 ┆ 403 ┆ 873 ┆ 081 ┆ 895 ┆ 128 ┆ 902 ┆ 094 ┆     ┆ 240 ┆ 241 ┆ 314 ┆ 306 ┆ 771 ┆ 690 ┆     ┆     ┆ 768 ┆ 334 ┆ 194 ┆ 142 ┆ 015 ┆ 001 ┆ 036 ┆ 245 ┆ 844 ┆ 010 ┆ 235 ┆ 000 ┆ 254 ┆ 008 ┆ 089 ┆ 771 ┆ 135 ┆ 306 ┆ 928 ┆ 187 ┆ 054 ┆ 520 ┆ 211 ┆ 065 ┆ 095 ┆ 315 ┆ 422 ┆ 146 ┆ 190 ┆ 144 ┆ 174 ┆ 100 ┆ 241 ┆ 124 ┆ 024 ┆ 317 ┆ 131 ┆ 184 ┆ 060 ┆ 843 ┆ 158 ┆ 319 ┆ 206 ┆ 015 ┆ 158 ┆ 272 ┆ 260 ┆ 149 ┆ 165 ┆ 029 ┆ 019 ┆ 122 ┆ 020 ┆ 007 ┆ 305 ┆ 368 ┆ 318 ┆ 215 ┆ 281 │
│ 17  ┆ 46  ┆ 06  ┆ 96  ┆     ┆ 06  ┆ 67  ┆ 05  ┆ 96  ┆ 32  ┆ 02  ┆ 97  ┆ 44  ┆ 36  ┆ 44  ┆ 04  ┆ 4   ┆ 56  ┆ 03  ┆ 01  ┆ 87  ┆ 25  ┆ 08  ┆ 81  ┆ 76  ┆ 21  ┆ 9   ┆ 054 ┆     ┆ 96  ┆ 38  ┆ 53  ┆ 43  ┆ 3   ┆ 79  ┆     ┆     ┆ 17  ┆ 49  ┆ 393 ┆ 75  ┆ 793 ┆ 281 ┆ 49  ┆ 5   ┆ 31  ┆ 237 ┆ 35  ┆ 011 ┆ 3   ┆ 248 ┆ 42  ┆ 3   ┆ 301 ┆ 43  ┆ 07  ┆ 065 ┆ 756 ┆ 07  ┆ 29  ┆ 598 ┆ 379 ┆ 77  ┆ 88  ┆ 2   ┆ 95  ┆ 64  ┆ 18  ┆ 96  ┆ 65  ┆ 165 ┆ 64  ┆ 25  ┆ 385 ┆ 05  ┆ 128 ┆ 59  ┆ 69  ┆ 754 ┆ 834 ┆ 853 ┆ 53  ┆ 46  ┆ 59  ┆ 292 ┆ 972 ┆ 793 ┆ 999 ┆ 54  ┆ 414 ┆ 242 ┆ 367 ┆ 52  ┆ 801 ┆ 406 ┆ 73  │
│ 0.4 ┆ 0.4 ┆ 0.4 ┆ 0.3 ┆ 0.4 ┆ 1.0 ┆ 0.3 ┆ 0.3 ┆ 0.2 ┆ 0.3 ┆ 0.4 ┆ 0.5 ┆ 0.3 ┆ 0.3 ┆ 0.2 ┆ 0.2 ┆ 0.1 ┆ 0.4 ┆ 0.2 ┆ 0.2 ┆ 0.5 ┆ 0.4 ┆ 0.4 ┆ 0.3 ┆ 0.2 ┆ 0.1 ┆ 0.4 ┆ -0. ┆ NaN ┆ 0.4 ┆ 0.4 ┆ 0.0 ┆ 0.5 ┆ 0.4 ┆ 0.1 ┆ NaN ┆ NaN ┆ 0.4 ┆ 0.5 ┆ -0. ┆ 0.0 ┆ -0. ┆ 0.0 ┆ -0. ┆ 0.0 ┆ 0.4 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.4 ┆ -0. ┆ 0.5 ┆ 0.1 ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.2 ┆ 0.7 ┆ 0.2 ┆ 0.4 ┆ 0.5 ┆ -0. ┆ -0. ┆ 0.1 ┆ -0. ┆ 0.1 ┆ 0.4 ┆ -0. ┆ 0.1 ┆ -0. ┆ 0.1 ┆ 0.0 ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.4 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.1 │
│ 717 ┆ 851 ┆ 390 ┆ 228 ┆ 059 ┆     ┆ 962 ┆ 621 ┆ 479 ┆ 710 ┆ 332 ┆ 351 ┆ 634 ┆ 431 ┆ 183 ┆ 059 ┆ 936 ┆ 174 ┆ 198 ┆ 721 ┆ 215 ┆ 476 ┆ 167 ┆ 499 ┆ 313 ┆ 188 ┆ 927 ┆ 152 ┆     ┆ 002 ┆ 006 ┆ 077 ┆ 318 ┆ 874 ┆ 516 ┆     ┆     ┆ 717 ┆ 689 ┆ 236 ┆ 000 ┆ 006 ┆ 063 ┆ 120 ┆ 736 ┆ 776 ┆ 030 ┆ 037 ┆ 007 ┆ 006 ┆ 032 ┆ 455 ┆ 874 ┆ 152 ┆ 318 ┆ 795 ┆ 227 ┆ 078 ┆ 135 ┆ 302 ┆ 060 ┆ 088 ┆ 203 ┆ 072 ┆ 319 ┆ 679 ┆ 476 ┆ 042 ┆ 005 ┆ 360 ┆ 136 ┆ 083 ┆ 283 ┆ 127 ┆ 890 ┆ 111 ┆ 227 ┆ 675 ┆ 371 ┆ 243 ┆ 007 ┆ 079 ┆ 010 ┆ 304 ┆ 133 ┆ 242 ┆ 037 ┆ 006 ┆ 012 ┆ 063 ┆ 020 ┆ 336 ┆ 248 ┆ 381 ┆ 206 ┆ 380 │
│ 72  ┆ 35  ┆ 91  ┆ 52  ┆ 06  ┆     ┆ 32  ┆ 13  ┆ 2   ┆ 9   ┆ 54  ┆ 6   ┆ 06  ┆ 59  ┆ 97  ┆ 44  ┆ 43  ┆ 26  ┆ 48  ┆ 93  ┆ 9   ┆ 51  ┆ 63  ┆ 9   ┆ 35  ┆ 22  ┆ 53  ┆ 102 ┆     ┆ 78  ┆ 82  ┆ 11  ┆ 35  ┆ 18  ┆ 96  ┆     ┆     ┆ 72  ┆ 85  ┆ 417 ┆ 68  ┆ 063 ┆ 01  ┆ 925 ┆ 19  ┆ 13  ┆ 551 ┆ 094 ┆ 513 ┆ 24  ┆ 016 ┆ 15  ┆ 18  ┆ 071 ┆ 35  ┆ 9   ┆ 43  ┆ 764 ┆ 76  ┆ 57  ┆ 682 ┆ 135 ┆ 52  ┆ 66  ┆ 12  ┆ 18  ┆ 93  ┆ 234 ┆ 383 ┆ 91  ┆ 091 ┆ 61  ┆ 73  ┆ 976 ┆ 4   ┆ 375 ┆ 29  ┆ 23  ┆ 757 ┆ 807 ┆ 971 ┆ 71  ┆ 8   ┆ 911 ┆ 836 ┆ 138 ┆ 655 ┆ 096 ┆ 592 ┆ 312 ┆ 83  ┆ 037 ┆ 42  ┆ 324 ┆ 061 ┆ 18  │
│ 0.4 ┆ 0.4 ┆ 0.4 ┆ 0.3 ┆ 0.3 ┆ 0.3 ┆ 1.0 ┆ 0.3 ┆ 0.2 ┆ 0.3 ┆ 0.3 ┆ 0.4 ┆ 0.4 ┆ 0.3 ┆ 0.2 ┆ 0.1 ┆ 0.1 ┆ 0.3 ┆ 0.2 ┆ 0.2 ┆ 0.4 ┆ 0.4 ┆ 0.3 ┆ 0.3 ┆ 0.1 ┆ 0.1 ┆ 0.4 ┆ -0. ┆ NaN ┆ 0.3 ┆ 0.3 ┆ 0.0 ┆ 0.4 ┆ 0.4 ┆ 0.1 ┆ NaN ┆ NaN ┆ 0.4 ┆ 0.4 ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -0. ┆ 0.1 ┆ 0.4 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.4 ┆ -0. ┆ 0.4 ┆ 0.2 ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.2 ┆ 0.6 ┆ 0.1 ┆ 0.4 ┆ 0.4 ┆ -0. ┆ -0. ┆ 0.0 ┆ -0. ┆ 0.0 ┆ 0.3 ┆ -0. ┆ 0.1 ┆ -0. ┆ 0.0 ┆ 0.0 ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ 0.3 ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ -0. ┆ -0. ┆ -0. ┆ 0.0 ┆ -0. ┆ -0. ┆ 0.1 │
│ 314 ┆ 374 ┆ 078 ┆ 007 ┆ 639 ┆ 962 ┆     ┆ 913 ┆ 441 ┆ 070 ┆ 307 ┆ 580 ┆ 936 ┆ 292 ┆ 575 ┆ 679 ┆ 673 ┆ 663 ┆ 208 ┆ 550 ┆ 944 ┆ 121 ┆ 606 ┆ 035 ┆ 879 ┆ 235 ┆ 421 ┆ 105 ┆     ┆ 584 ┆ 581 ┆ 336 ┆ 917 ┆ 388 ┆ 631 ┆     ┆     ┆ 314 ┆ 968 ┆ 154 ┆ 012 ┆ 216 ┆ 169 ┆ 111 ┆ 032 ┆ 382 ┆ 047 ┆ 021 ┆ 012 ┆ 044 ┆ 019 ┆ 504 ┆ 388 ┆ 116 ┆ 917 ┆ 348 ┆ 211 ┆ 061 ┆ 890 ┆ 413 ┆ 051 ┆ 060 ┆ 260 ┆ 540 ┆ 945 ┆ 436 ┆ 864 ┆ 034 ┆ 012 ┆ 947 ┆ 094 ┆ 736 ┆ 962 ┆ 123 ┆ 768 ┆ 067 ┆ 749 ┆ 396 ┆ 310 ┆ 180 ┆ 022 ┆ 221 ┆ 272 ┆ 225 ┆ 102 ┆ 228 ┆ 045 ┆ 003 ┆ 095 ┆ 055 ┆ 024 ┆ 286 ┆ 960 ┆ 311 ┆ 179 ┆ 388 │
│ 18  ┆ 12  ┆ 37  ┆ 13  ┆ 67  ┆ 32  ┆     ┆ 35  ┆ 53  ┆ 35  ┆ 39  ┆ 73  ┆ 56  ┆ 77  ┆ 77  ┆ 76  ┆ 75  ┆ 93  ┆ 13  ┆ 12  ┆ 37  ┆ 98  ┆ 1   ┆ 77  ┆ 43  ┆ 39  ┆ 29  ┆ 853 ┆     ┆ 99  ┆ 08  ┆ 36  ┆ 52  ┆ 03  ┆ 56  ┆     ┆     ┆ 18  ┆ 74  ┆ 383 ┆ 731 ┆ 96  ┆ 4   ┆ 217 ┆ 93  ┆ 72  ┆ 338 ┆ 568 ┆ 277 ┆ 183 ┆ 778 ┆ 95  ┆ 03  ┆ 477 ┆ 52  ┆ 78  ┆ 212 ┆ 687 ┆ 15  ┆ 74  ┆ 63  ┆ 704 ┆ 74  ┆ 12  ┆ 87  ┆ 16  ┆ 17  ┆ 744 ┆ 658 ┆ 83  ┆ 783 ┆ 86  ┆ 45  ┆ 251 ┆ 12  ┆ 117 ┆ 19  ┆     ┆ 656 ┆ 101 ┆ 141 ┆ 41  ┆ 97  ┆ 631 ┆ 412 ┆ 953 ┆ 724 ┆ 212 ┆ 58  ┆ 545 ┆ 866 ┆ 28  ┆ 66  ┆ 628 ┆ 438 ┆ 06  │

In [ ]:
import numpy as np

acs_corr_matrix = df.select(acs_cols).corr()

# Count NaNs per row
nan_counts = [
    (col, sum(v is None or (isinstance(v, float) and np.isnan(v)) for v in acs_corr_matrix[col]))
    for col in acs_corr_matrix.columns
]

nan_counts

[('population_total', np.int64(3)),
 ('population_male', np.int64(3)),
 ('population_female', np.int64(3)),
 ('male_65_66', np.int64(3)),
 ('male_67_69', np.int64(3)),
 ('male_70_74', np.int64(3)),
 ('male_75_79', np.int64(3)),
 ('male_80_84', np.int64(3)),
 ('male_85_plus', np.int64(3)),
 ('female_65_66', np.int64(3)),
 ('female_67_69', np.int64(3)),
 ('female_70_74', np.int64(3)),
 ('female_75_79', np.int64(3)),
 ('female_80_84', np.int64(3)),
 ('female_85_plus', np.int64(3)),
 ('male_under_5', np.int64(3)),
 ('female_under_5', np.int64(3)),
 ('median_age', np.int64(3)),
 ('disability_under_18', np.int64(3)),
 ('disability_18_64', np.int64(3)),
 ('disability_65_plus', np.int64(3)),
 ('edu_high_school', np.int64(3)),
 ('edu_bachelors', np.int64(3)),
 ('edu_masters', np.int64(3)),
 ('edu_professional', np.int64(3)),
 ('edu_doctorate', np.int64(3)),
 ('poverty_universe', np.int64(3)),
 ('poverty_below', np.int64(3)),
 ('median_household_income', np.int64(96)),
 ('labor_force', np.int64(3)),
 ('labor_force_civilian', np.int64(3)),
 ('unemployment_civilian', np.int64(3)),
 ('housing_units', np.int64(3)),
 ('housing_occupied', np.int64(3)),
 ('housing_vacant', np.int64(3)),
 ('median_home_value', np.int64(96)),
 ('median_gross_rent', np.int64(96)),
 ('race_universe', np.int64(3)),
 ('race_white', np.int64(3)),
 ('race_black', np.int64(3)),
 ('race_american_indian', np.int64(3)),
 ('race_asian', np.int64(3)),
 ('race_pacific_islander', np.int64(3)),
 ('race_hispanic', np.int64(3)),
 ('race_other', np.int64(3)),
 ('language_universe', np.int64(3)),
 ('limited_english_5_17', np.int64(3)),
 ('limited_english_18_64', np.int64(3)),
 ('limited_english_65_plus', np.int64(3)),
 ('no_english_5_17', np.int64(3)),
 ('no_english_18_64', np.int64(3)),
 ('no_english_65_plus', np.int64(3)),
 ('vehicle_universe', np.int64(3)),
 ('vehicle_none', np.int64(3)),
 ('housing_structure_universe', np.int64(3)),
 ('housing_1_unit', np.int64(3)),
 ('housing_2_unit', np.int64(3)),
 ('housing_3_4_unit', np.int64(3)),
 ('housing_5_9_unit', np.int64(3)),
 ('housing_10_19_unit', np.int64(3)),
 ('housing_20_49_unit', np.int64(3)),
 ('housing_50_plus_unit', np.int64(3)),
 ('housing_mobile_home', np.int64(3)),
 ('population_65_plus', np.int64(3)),
 ('population_under_5', np.int64(3)),
 ('disability_total', np.int64(3)),
 ('edu_total', np.int64(3)),
 ('limited_english_total', np.int64(3)),
 ('no_english_total', np.int64(3)),
 ('pct_male', np.int64(3)),
 ('pct_female', np.int64(3)),
 ('sex_ratio', np.int64(3)),
 ('pct_65_plus', np.int64(3)),
 ('pct_under_5', np.int64(3)),
 ('pct_disability', np.int64(3)),
 ('pct_high_school', np.int64(3)),
 ('pct_bachelors', np.int64(3)),
 ('pct_grad_degree', np.int64(3)),
 ('pct_poverty', np.int64(3)),
 ('pct_unemployment', np.int64(3)),
 ('pct_housing_occupied', np.int64(3)),
 ('pct_housing_vacant', np.int64(3)),
 ('pct_white', np.int64(3)),
 ('pct_black', np.int64(3)),
 ('pct_asian', np.int64(3)),
 ('pct_hispanic', np.int64(3)),
 ('pct_american_indian', np.int64(3)),
 ('pct_pacific_islander', np.int64(3)),
 ('pct_race_other', np.int64(3)),
 ('pct_limited_english', np.int64(3)),
 ('pct_no_english', np.int64(3)),
 ('pct_vehicle_none', np.int64(3)),
 ('pct_single_family', np.int64(3)),
 ('pct_small_multi_family', np.int64(3)),
 ('pct_large_multi_family', np.int64(3)),
 ('pct_mobile_home', np.int64(3))]

In [18]:
for col in [
    "median_household_income",
    "median_home_value",
    "median_gross_rent",
]:
    print(f"\n=== {col} ===")
    print(
        df
        .group_by(col)
        .count()
        .sort(col)
    )

=== median_household_income ===
shape: (1_456, 2)
┌─────────────────────────┬───────┐
│ median_household_income ┆ count │
│ ---                     ┆ ---   │
│ f32                     ┆ u32   │
╞═════════════════════════╪═══════╡
│ null                    ┆ 7     │
│ 10114.0                 ┆ 7     │
│ 12130.0                 ┆ 7     │
│ 12331.0                 ┆ 7     │
│ 16755.0                 ┆ 7     │
│ 18670.0                 ┆ 7     │
│ 19559.0                 ┆ 7     │
│ 19950.0                 ┆ 2     │
│ 21149.0                 ┆ 7     │
│ 21250.0                 ┆ 7     │
│ 21846.0                 ┆ 7     │
│ 22204.0                 ┆ 7     │
│ 22933.0                 ┆ 7     │
│ 23425.0                 ┆ 7     │
│ 23505.0                 ┆ 7     │
│ 25481.0                 ┆ 7     │
│ 25897.0                 ┆ 7     │
│ 25966.0                 ┆ 7     │
│ 26691.0                 ┆ 7     │
│ 26806.0                 ┆ 5     │
│ 27644.0                 ┆ 7     │
│ 27746.0                 ┆ 7     │
│ 28382.0                 ┆ 7     │
│ 28487.0                 ┆ 7     │
│ 28720.0                 ┆ 6     │
│ 29591.0                 ┆ 7     │
│ 30268.0                 ┆ 5     │
│ 30525.0                 ┆ 7     │
│ 30683.0                 ┆ 7     │
│ 31000.0                 ┆ 6     │
│ 31418.0                 ┆ 7     │
│ 31431.0                 ┆ 7     │
│ 31742.0                 ┆ 7     │
│ 31830.0                 ┆ 7     │
│ 31938.0                 ┆ 7     │
│ 31996.0                 ┆ 7     │
│ 32268.0                 ┆ 7     │
│ 32302.0                 ┆ 7     │
│ 32750.0                 ┆ 7     │
│ 32946.0                 ┆ 7     │
│ 33839.0                 ┆ 5     │
│ 34083.0                 ┆ 7     │
│ 34245.0                 ┆ 7     │
│ 34511.0                 ┆ 7     │
│ 34588.0                 ┆ 7     │
│ 34667.0                 ┆ 6     │
│ 34697.0                 ┆ 7     │
│ 34750.0                 ┆ 5     │
│ 34792.0                 ┆ 7     │
│ 35000.0                 ┆ 7     │
│ 35221.0                 ┆ 7     │
│ 35337.0                 ┆ 7     │
│ 35472.0                 ┆ 7     │
│ 35483.0                 ┆ 7     │
│ 35588.0                 ┆ 7     │
│ 35974.0                 ┆ 7     │
│ 36555.0                 ┆ 7     │
│ 36850.0                 ┆ 7     │
│ 36944.0                 ┆ 7     │
│ 37031.0                 ┆ 7     │
│ 37231.0                 ┆ 7     │
│ 37321.0                 ┆ 7     │
│ 37554.0                 ┆ 7     │
│ 37745.0                 ┆ 7     │
│ 38071.0                 ┆ 7     │
│ 38438.0                 ┆ 7     │
│ 38576.0                 ┆ 7     │
│ 38589.0                 ┆ 7     │
│ 38846.0                 ┆ 7     │
│ 39034.0                 ┆ 7     │
│ 39231.0                 ┆ 7     │
│ 39481.0                 ┆ 7     │
│ 39500.0                 ┆ 7     │
│ 39508.0                 ┆ 7     │
│ 39833.0                 ┆ 7     │
│ …                       ┆ …     │
│ 127895.0                ┆ 7     │
│ 128015.0                ┆ 7     │
│ 128065.0                ┆ 7     │
│ 129238.0                ┆ 7     │
│ 129607.0                ┆ 7     │
│ 129609.0                ┆ 7     │
│ 129900.0                ┆ 7     │
│ 130278.0                ┆ 7     │
│ 130357.0                ┆ 7     │
│ 130406.0                ┆ 7     │
│ 131538.0                ┆ 7     │
│ 131667.0                ┆ 7     │
│ 131681.0                ┆ 7     │
│ 131691.0                ┆ 7     │
│ 131845.0                ┆ 7     │
│ 132411.0                ┆ 7     │
│ 132544.0                ┆ 7     │
│ 132654.0                ┆ 7     │
│ 134083.0                ┆ 7     │
│ 134231.0                ┆ 7     │
│ 134643.0                ┆ 7     │
│ 135222.0                ┆ 7     │
│ 135556.0                ┆ 7     │
│ 135670.0                ┆ 7     │
│ 136023.0                ┆ 7     │
│ 136167.0                ┆ 7     │
│ 136324.0                ┆ 7     │
│ 136923.0                ┆ 7     │
│ 137105.0                ┆ 7     │
│ 137188.0                ┆ 7     │
│ 137630.0                ┆ 7     │
│ 137717.0                ┆ 7     │
│ 138248.0                ┆ 7     │
│ 141013.0                ┆ 7     │
│ 141286.0                ┆ 7     │
│ 141319.0                ┆ 7     │
│ 141932.0                ┆ 7     │
│ 142031.0                ┆ 7     │
│ 142762.0                ┆ 7     │
│ 143610.0                ┆ 7     │
│ 143672.0                ┆ 7     │
│ 143750.0                ┆ 7     │
│ 145625.0                ┆ 7     │
│ 145728.0                ┆ 7     │
│ 146750.0                ┆ 7     │
│ 147125.0                ┆ 7     │
│ 147917.0                ┆ 7     │
│ 148889.0                ┆ 7     │
│ 149189.0                ┆ 7     │
│ 149856.0                ┆ 7     │
│ 150221.0                ┆ 7     │
│ 151667.0                ┆ 7     │
│ 153407.0                ┆ 7     │
│ 154821.0                ┆ 7     │
│ 156528.0                ┆ 7     │
│ 157821.0                ┆ 7     │
│ 158304.0                ┆ 7     │
│ 159293.0                ┆ 7     │
│ 161250.0                ┆ 7     │
│ 162125.0                ┆ 7     │
│ 162633.0                ┆ 7     │
│ 164357.0                ┆ 7     │
│ 165690.0                ┆ 7     │
│ 167083.0                ┆ 7     │
│ 171688.0                ┆ 7     │
│ 171867.0                ┆ 7     │
│ 173560.0                ┆ 7     │
│ 183750.0                ┆ 7     │
│ 187750.0                ┆ 7     │
│ 188125.0                ┆ 7     │
│ 190034.0                ┆ 7     │
│ 202813.0                ┆ 7     │
│ 204427.0                ┆ 7     │
│ 220250.0                ┆ 7     │
│ 224750.0                ┆ 7     │
└─────────────────────────┴───────┘

=== median_home_value ===
shape: (1_203, 2)
┌───────────────────┬───────┐
│ median_home_value ┆ count │
│ ---               ┆ ---   │
│ f32               ┆ u32   │
╞═══════════════════╪═══════╡
│ null              ┆ 141   │
│ 39000.0           ┆ 7     │
│ 59400.0           ┆ 7     │
│ 66200.0           ┆ 7     │
│ 66400.0           ┆ 14    │
│ 69100.0           ┆ 7     │
│ 70000.0           ┆ 7     │
│ 74400.0           ┆ 6     │
│ 77600.0           ┆ 7     │
│ 77900.0           ┆ 7     │
│ 78500.0           ┆ 7     │
│ 79600.0           ┆ 6     │
│ 81200.0           ┆ 7     │
│ 83900.0           ┆ 7     │
│ 84300.0           ┆ 7     │
│ 84400.0           ┆ 7     │
│ 85200.0           ┆ 7     │
│ 86400.0           ┆ 7     │
│ 87100.0           ┆ 7     │
│ 87400.0           ┆ 7     │
│ 87500.0           ┆ 7     │
│ 87800.0           ┆ 7     │
│ 89000.0           ┆ 7     │
│ 92200.0           ┆ 6     │
│ 93300.0           ┆ 7     │
│ 93600.0           ┆ 5     │
│ 93800.0           ┆ 7     │
│ 94000.0           ┆ 7     │
│ 94400.0           ┆ 7     │
│ 95000.0           ┆ 5     │
│ 96400.0           ┆ 7     │
│ 98700.0           ┆ 7     │
│ 98800.0           ┆ 7     │
│ 103400.0          ┆ 7     │
│ 103600.0          ┆ 7     │
│ 103700.0          ┆ 7     │
│ 104200.0          ┆ 7     │
│ 104700.0          ┆ 7     │
│ 105400.0          ┆ 7     │
│ 105800.0          ┆ 7     │
│ 106100.0          ┆ 7     │
│ 107300.0          ┆ 7     │
│ 107500.0          ┆ 7     │
│ 108000.0          ┆ 5     │
│ 108200.0          ┆ 7     │
│ 108600.0          ┆ 7     │
│ 109000.0          ┆ 7     │
│ 109600.0          ┆ 7     │
│ 109700.0          ┆ 7     │
│ 109900.0          ┆ 7     │
│ 110800.0          ┆ 7     │
│ 111100.0          ┆ 7     │
│ 111700.0          ┆ 7     │
│ 112100.0          ┆ 7     │
│ 112800.0          ┆ 7     │
│ 113200.0          ┆ 7     │
│ 113900.0          ┆ 7     │
│ 114300.0          ┆ 7     │
│ 114800.0          ┆ 7     │
│ 114900.0          ┆ 7     │
│ 115600.0          ┆ 7     │
│ 116900.0          ┆ 7     │
│ 117100.0          ┆ 7     │
│ 117700.0          ┆ 7     │
│ 117900.0          ┆ 7     │
│ 118500.0          ┆ 7     │
│ 118700.0          ┆ 14    │
│ 118900.0          ┆ 14    │
│ 119400.0          ┆ 6     │
│ 119600.0          ┆ 21    │
│ 119900.0          ┆ 14    │
│ 120700.0          ┆ 7     │
│ 121700.0          ┆ 7     │
│ 121900.0          ┆ 7     │
│ 122100.0          ┆ 7     │
│ …                 ┆ …     │
│ 459500.0          ┆ 7     │
│ 460100.0          ┆ 7     │
│ 461000.0          ┆ 7     │
│ 461100.0          ┆ 7     │
│ 461500.0          ┆ 7     │
│ 462000.0          ┆ 7     │
│ 462600.0          ┆ 7     │
│ 466000.0          ┆ 7     │
│ 466700.0          ┆ 7     │
│ 467900.0          ┆ 7     │
│ 470700.0          ┆ 14    │
│ 470900.0          ┆ 7     │
│ 471700.0          ┆ 7     │
│ 472300.0          ┆ 7     │
│ 472500.0          ┆ 7     │
│ 472700.0          ┆ 7     │
│ 473200.0          ┆ 7     │
│ 473300.0          ┆ 7     │
│ 473600.0          ┆ 7     │
│ 474200.0          ┆ 7     │
│ 474800.0          ┆ 7     │
│ 476900.0          ┆ 7     │
│ 478800.0          ┆ 7     │
│ 480400.0          ┆ 14    │
│ 481800.0          ┆ 7     │
│ 482200.0          ┆ 7     │
│ 483700.0          ┆ 7     │
│ 493500.0          ┆ 7     │
│ 494400.0          ┆ 7     │
│ 499300.0          ┆ 7     │
│ 502500.0          ┆ 7     │
│ 505300.0          ┆ 7     │
│ 505600.0          ┆ 7     │
│ 507600.0          ┆ 14    │
│ 513900.0          ┆ 7     │
│ 514500.0          ┆ 7     │
│ 518000.0          ┆ 7     │
│ 518700.0          ┆ 7     │
│ 520500.0          ┆ 7     │
│ 521400.0          ┆ 7     │
│ 522200.0          ┆ 7     │
│ 523500.0          ┆ 7     │
│ 525400.0          ┆ 7     │
│ 532700.0          ┆ 7     │
│ 535100.0          ┆ 7     │
│ 537600.0          ┆ 7     │
│ 538600.0          ┆ 7     │
│ 539800.0          ┆ 14    │
│ 547900.0          ┆ 7     │
│ 550600.0          ┆ 7     │
│ 554300.0          ┆ 7     │
│ 571000.0          ┆ 7     │
│ 582500.0          ┆ 7     │
│ 587300.0          ┆ 7     │
│ 588000.0          ┆ 7     │
│ 592400.0          ┆ 7     │
│ 599100.0          ┆ 7     │
│ 602400.0          ┆ 7     │
│ 602900.0          ┆ 7     │
│ 605300.0          ┆ 7     │
│ 606000.0          ┆ 7     │
│ 624200.0          ┆ 7     │
│ 630600.0          ┆ 7     │
│ 631000.0          ┆ 7     │
│ 653200.0          ┆ 7     │
│ 655800.0          ┆ 7     │
│ 658400.0          ┆ 7     │
│ 692400.0          ┆ 7     │
│ 699600.0          ┆ 7     │
│ 767700.0          ┆ 7     │
│ 792400.0          ┆ 7     │
│ 800000.0          ┆ 7     │
│ 814200.0          ┆ 7     │
│ 889400.0          ┆ 7     │
│ 942500.0          ┆ 7     │
└───────────────────┴───────┘

=== median_gross_rent ===
shape: (768, 2)
┌───────────────────┬───────┐
│ median_gross_rent ┆ count │
│ ---               ┆ ---   │
│ f32               ┆ u32   │
╞═══════════════════╪═══════╡
│ null              ┆ 197   │
│ 408.0             ┆ 7     │
│ 465.0             ┆ 7     │
│ 466.0             ┆ 7     │
│ 488.0             ┆ 7     │
│ 520.0             ┆ 7     │
│ 525.0             ┆ 7     │
│ 531.0             ┆ 7     │
│ 541.0             ┆ 7     │
│ 546.0             ┆ 7     │
│ 550.0             ┆ 7     │
│ 558.0             ┆ 7     │
│ 562.0             ┆ 7     │
│ 583.0             ┆ 7     │
│ 587.0             ┆ 7     │
│ 589.0             ┆ 7     │
│ 591.0             ┆ 7     │
│ 605.0             ┆ 7     │
│ 606.0             ┆ 7     │
│ 608.0             ┆ 14    │
│ 613.0             ┆ 7     │
│ 621.0             ┆ 7     │
│ 622.0             ┆ 7     │
│ 625.0             ┆ 14    │
│ 626.0             ┆ 7     │
│ 633.0             ┆ 7     │
│ 634.0             ┆ 7     │
│ 635.0             ┆ 7     │
│ 638.0             ┆ 7     │
│ 647.0             ┆ 7     │
│ 648.0             ┆ 7     │
│ 650.0             ┆ 7     │
│ 654.0             ┆ 7     │
│ 663.0             ┆ 14    │
│ 666.0             ┆ 7     │
│ 672.0             ┆ 7     │
│ 673.0             ┆ 7     │
│ 675.0             ┆ 7     │
│ 679.0             ┆ 7     │
│ 680.0             ┆ 7     │
│ 681.0             ┆ 28    │
│ 683.0             ┆ 7     │
│ 687.0             ┆ 7     │
│ 689.0             ┆ 7     │
│ 690.0             ┆ 21    │
│ 692.0             ┆ 7     │
│ 694.0             ┆ 7     │
│ 697.0             ┆ 14    │
│ 699.0             ┆ 7     │
│ 700.0             ┆ 7     │
│ 708.0             ┆ 14    │
│ 712.0             ┆ 14    │
│ 713.0             ┆ 14    │
│ 714.0             ┆ 7     │
│ 716.0             ┆ 21    │
│ 717.0             ┆ 7     │
│ 718.0             ┆ 7     │
│ 719.0             ┆ 7     │
│ 720.0             ┆ 7     │
│ 722.0             ┆ 7     │
│ 725.0             ┆ 7     │
│ 726.0             ┆ 7     │
│ 728.0             ┆ 14    │
│ 729.0             ┆ 7     │
│ 732.0             ┆ 7     │
│ 734.0             ┆ 7     │
│ 735.0             ┆ 7     │
│ 737.0             ┆ 7     │
│ 738.0             ┆ 7     │
│ 739.0             ┆ 7     │
│ 740.0             ┆ 7     │
│ 742.0             ┆ 14    │
│ 744.0             ┆ 21    │
│ 745.0             ┆ 7     │
│ 746.0             ┆ 7     │
│ …                 ┆ …     │
│ 1646.0            ┆ 7     │
│ 1647.0            ┆ 7     │
│ 1649.0            ┆ 7     │
│ 1650.0            ┆ 14    │
│ 1651.0            ┆ 7     │
│ 1652.0            ┆ 7     │
│ 1654.0            ┆ 7     │
│ 1666.0            ┆ 7     │
│ 1667.0            ┆ 7     │
│ 1669.0            ┆ 7     │
│ 1672.0            ┆ 7     │
│ 1673.0            ┆ 7     │
│ 1684.0            ┆ 7     │
│ 1685.0            ┆ 7     │
│ 1691.0            ┆ 14    │
│ 1693.0            ┆ 7     │
│ 1697.0            ┆ 7     │
│ 1699.0            ┆ 21    │
│ 1700.0            ┆ 7     │
│ 1702.0            ┆ 7     │
│ 1703.0            ┆ 21    │
│ 1706.0            ┆ 14    │
│ 1709.0            ┆ 7     │
│ 1718.0            ┆ 7     │
│ 1719.0            ┆ 7     │
│ 1721.0            ┆ 7     │
│ 1725.0            ┆ 7     │
│ 1726.0            ┆ 7     │
│ 1728.0            ┆ 7     │
│ 1736.0            ┆ 7     │
│ 1741.0            ┆ 7     │
│ 1742.0            ┆ 7     │
│ 1743.0            ┆ 7     │
│ 1747.0            ┆ 7     │
│ 1750.0            ┆ 7     │
│ 1754.0            ┆ 7     │
│ 1756.0            ┆ 7     │
│ 1757.0            ┆ 7     │
│ 1759.0            ┆ 7     │
│ 1763.0            ┆ 7     │
│ 1764.0            ┆ 7     │
│ 1777.0            ┆ 14    │
│ 1781.0            ┆ 7     │
│ 1786.0            ┆ 7     │
│ 1805.0            ┆ 7     │
│ 1811.0            ┆ 7     │
│ 1812.0            ┆ 7     │
│ 1816.0            ┆ 7     │
│ 1820.0            ┆ 7     │
│ 1852.0            ┆ 7     │
│ 1861.0            ┆ 7     │
│ 1863.0            ┆ 7     │
│ 1893.0            ┆ 7     │
│ 1900.0            ┆ 7     │
│ 1903.0            ┆ 14    │
│ 1907.0            ┆ 7     │
│ 1919.0            ┆ 7     │
│ 1961.0            ┆ 7     │
│ 2038.0            ┆ 7     │
│ 2045.0            ┆ 7     │
│ 2056.0            ┆ 7     │
│ 2075.0            ┆ 7     │
│ 2081.0            ┆ 7     │
│ 2094.0            ┆ 7     │
│ 2118.0            ┆ 7     │
│ 2122.0            ┆ 7     │
│ 2136.0            ┆ 7     │
│ 2142.0            ┆ 7     │
│ 2156.0            ┆ 14    │
│ 2297.0            ┆ 7     │
│ 2339.0            ┆ 7     │
│ 2497.0            ┆ 7     │
│ 2833.0            ┆ 7     │
│ 3138.0            ┆ 7     │
│ 3501.0            ┆ 7     │
└───────────────────┴───────┘

C:\Users\brett\AppData\Local\Temp\ipykernel_22564\2107585949.py:10: DeprecationWarning: `GroupBy.count` was renamed; use `GroupBy.len` instead
  .count()

In [ ]:
# total number of null instances per column
df.select([
    pl.col(col).is_null().sum().alias(col)
    for col in acs_cols
])

shape: (1, 96)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ pop ┆ pop ┆ pop ┆ mal ┆ mal ┆ mal ┆ mal ┆ mal ┆ mal ┆ fem ┆ fem ┆ fem ┆ fem ┆ fem ┆ fem ┆ mal ┆ fem ┆ med ┆ dis ┆ dis ┆ dis ┆ edu ┆ edu ┆ edu ┆ edu ┆ edu ┆ pov ┆ pov ┆ med ┆ lab ┆ lab ┆ une ┆ hou ┆ hou ┆ hou ┆ med ┆ med ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ lan ┆ lim ┆ lim ┆ lim ┆ no_ ┆ no_ ┆ no_ ┆ veh ┆ veh ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ pop ┆ pop ┆ dis ┆ edu ┆ lim ┆ no_ ┆ pct ┆ pct ┆ sex ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct │
│ ula ┆ ula ┆ ula ┆ e_6 ┆ e_6 ┆ e_7 ┆ e_7 ┆ e_8 ┆ e_8 ┆ ale ┆ ale ┆ ale ┆ ale ┆ ale ┆ ale ┆ e_u ┆ ale ┆ ian ┆ abi ┆ abi ┆ abi ┆ _hi ┆ _ba ┆ _ma ┆ _pr ┆ _do ┆ ert ┆ ert ┆ ian ┆ or_ ┆ or_ ┆ mpl ┆ sin ┆ sin ┆ sin ┆ ian ┆ ian ┆ e_u ┆ e_w ┆ e_b ┆ e_a ┆ e_a ┆ e_p ┆ e_h ┆ e_o ┆ gua ┆ ite ┆ ite ┆ ite ┆ eng ┆ eng ┆ eng ┆ icl ┆ icl ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ ula ┆ ula ┆ abi ┆ _to ┆ ite ┆ eng ┆ _ma ┆ _fe ┆ _ra ┆ _65 ┆ _un ┆ _di ┆ _hi ┆ _ba ┆ _gr ┆ _po ┆ _un ┆ _ho ┆ _ho ┆ _wh ┆ _bl ┆ _as ┆ _hi ┆ _am ┆ _pa ┆ _ra ┆ _li ┆ _no ┆ _ve ┆ _si ┆ _sm ┆ _la ┆ _mo │
│ tio ┆ tio ┆ tio ┆ 5_6 ┆ 7_6 ┆ 0_7 ┆ 5_7 ┆ 0_8 ┆ 5_p ┆ _65 ┆ _67 ┆ _70 ┆ _75 ┆ _80 ┆ _85 ┆ nde ┆ _un ┆ _ag ┆ lit ┆ lit ┆ lit ┆ gh_ ┆ che ┆ ste ┆ ofe ┆ cto ┆ y_u ┆ y_b ┆ _ho ┆ for ┆ for ┆ oym ┆ g_u ┆ g_o ┆ g_v ┆ _ho ┆ _gr ┆ niv ┆ hit ┆ lac ┆ mer ┆ sia ┆ aci ┆ isp ┆ the ┆ ge_ ┆ d_e ┆ d_e ┆ d_e ┆ lis ┆ lis ┆ lis ┆ e_u ┆ e_n ┆ g_s ┆ g_1 ┆ g_2 ┆ g_3 ┆ g_5 ┆ g_1 ┆ g_2 ┆ g_5 ┆ g_m ┆ tio ┆ tio ┆ lit ┆ tal ┆ d_e ┆ lis ┆ le  ┆ mal ┆ tio ┆ _pl ┆ der ┆ sab ┆ gh_ ┆ che ┆ ad_ ┆ ver ┆ emp ┆ usi ┆ usi ┆ ite ┆ ack ┆ ian ┆ spa ┆ eri ┆ cif ┆ ce_ ┆ mit ┆ _en ┆ hic ┆ ngl ┆ all ┆ rge ┆ bil │
│ n_t ┆ n_m ┆ n_f ┆ 6   ┆ 9   ┆ 4   ┆ 9   ┆ 4   ┆ lus ┆ _66 ┆ _69 ┆ _74 ┆ _79 ┆ _84 ┆ _pl ┆ r_5 ┆ der ┆ e   ┆ y_u ┆ y_1 ┆ y_6 ┆ sch ┆ lor ┆ rs  ┆ ssi ┆ rat ┆ niv ┆ elo ┆ use ┆ ce  ┆ ce_ ┆ ent ┆ nit ┆ ccu ┆ aca ┆ me_ ┆ oss ┆ ers ┆ e   ┆ k   ┆ ica ┆ n   ┆ fic ┆ ani ┆ r   ┆ uni ┆ ngl ┆ ngl ┆ ngl ┆ h_5 ┆ h_1 ┆ h_6 ┆ niv ┆ one ┆ tru ┆ _un ┆ _un ┆ _4_ ┆ _9_ ┆ 0_1 ┆ 0_4 ┆ 0_p ┆ obi ┆ n_6 ┆ n_u ┆ y_t ┆ --- ┆ ngl ┆ h_t ┆ --- ┆ e   ┆ --- ┆ us  ┆ _5  ┆ ili ┆ sch ┆ lor ┆ deg ┆ ty  ┆ loy ┆ ng_ ┆ ng_ ┆ --- ┆ --- ┆ --- ┆ nic ┆ can ┆ ic_ ┆ oth ┆ ed_ ┆ gli ┆ le_ ┆ e_f ┆ _mu ┆ _mu ┆ e_h │
│ ota ┆ ale ┆ ema ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ us  ┆ --- ┆ _5  ┆ --- ┆ nde ┆ 8_6 ┆ 5_p ┆ ool ┆ s   ┆ --- ┆ ona ┆ e   ┆ ers ┆ w   ┆ hol ┆ --- ┆ civ ┆ _ci ┆ s   ┆ pie ┆ nt  ┆ val ┆ _re ┆ e   ┆ --- ┆ --- ┆ n_i ┆ --- ┆ _is ┆ c   ┆ --- ┆ ver ┆ ish ┆ ish ┆ ish ┆ _17 ┆ 8_6 ┆ 5_p ┆ ers ┆ --- ┆ ctu ┆ it  ┆ it  ┆ uni ┆ uni ┆ 9_u ┆ 9_u ┆ lus ┆ le_ ┆ 5_p ┆ nde ┆ ota ┆ u32 ┆ ish ┆ ota ┆ u32 ┆ --- ┆ u32 ┆ --- ┆ --- ┆ ty  ┆ ool ┆ s   ┆ ree ┆ --- ┆ men ┆ occ ┆ vac ┆ u32 ┆ u32 ┆ u32 ┆ --- ┆ _in ┆ isl ┆ er  ┆ eng ┆ sh  ┆ non ┆ ami ┆ lti ┆ lti ┆ ome │
│ l   ┆ --- ┆ le  ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ --- ┆ u32 ┆ --- ┆ u32 ┆ r_1 ┆ 4   ┆ lus ┆ --- ┆ --- ┆ u32 ┆ l   ┆ --- ┆ e   ┆ --- ┆ d_i ┆ u32 ┆ ili ┆ vil ┆ --- ┆ d   ┆ --- ┆ ue  ┆ nt  ┆ --- ┆ u32 ┆ u32 ┆ ndi ┆ u32 ┆ lan ┆ --- ┆ u32 ┆ se  ┆ _5_ ┆ _18 ┆ _65 ┆ --- ┆ 4   ┆ lus ┆ e   ┆ u32 ┆ re_ ┆ --- ┆ --- ┆ t   ┆ t   ┆ nit ┆ nit ┆ _un ┆ hom ┆ lus ┆ r_5 ┆ l   ┆     ┆ _to ┆ l   ┆     ┆ u32 ┆     ┆ u32 ┆ u32 ┆ --- ┆ --- ┆ --- ┆ --- ┆ u32 ┆ t   ┆ upi ┆ ant ┆     ┆     ┆     ┆ u32 ┆ dia ┆ and ┆ --- ┆ lis ┆ --- ┆ e   ┆ ly  ┆ _fa ┆ _fa ┆ --- │
│ --- ┆ u32 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆ u32 ┆     ┆ 8   ┆ --- ┆ --- ┆ u32 ┆ u32 ┆     ┆ --- ┆ u32 ┆ --- ┆ u32 ┆ nco ┆     ┆ an  ┆ ian ┆ u32 ┆ --- ┆ u32 ┆ --- ┆ --- ┆ u32 ┆     ┆     ┆ an  ┆     ┆ der ┆ u32 ┆     ┆ --- ┆ 17  ┆ _64 ┆ _pl ┆ u32 ┆ --- ┆ --- ┆ --- ┆     ┆ uni ┆ u32 ┆ u32 ┆ --- ┆ --- ┆ --- ┆ --- ┆ it  ┆ e   ┆ --- ┆ --- ┆ --- ┆     ┆ tal ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆     ┆ --- ┆ ed  ┆ --- ┆     ┆     ┆     ┆     ┆ n   ┆ er  ┆ u32 ┆ h   ┆ u32 ┆ --- ┆ --- ┆ mil ┆ mil ┆ u32 │
│ u32 ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ u32 ┆ u32 ┆     ┆     ┆     ┆ u32 ┆     ┆ u32 ┆     ┆ me  ┆     ┆ --- ┆ --- ┆     ┆ u32 ┆     ┆ u32 ┆ u32 ┆     ┆     ┆     ┆ --- ┆     ┆ --- ┆     ┆     ┆ u32 ┆ --- ┆ --- ┆ us  ┆     ┆ u32 ┆ u32 ┆ u32 ┆     ┆ ver ┆     ┆     ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ --- ┆ --- ┆ u32 ┆ u32 ┆ u32 ┆     ┆ --- ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ --- ┆ u32 ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ u32 ┆ u32 ┆ y   ┆ y   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ u32 ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆ u32 ┆     ┆     ┆     ┆ u32 ┆ u32 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ se  ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ u32 ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ u32 ┆     ┆ u32 ┆     ┆     ┆     ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ u32 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 7   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 141 ┆ 197 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [ ]:
# unique value counts per column, variance check
df.select([
    pl.col(col).n_unique().alias(col)
    for col in acs_cols
])

shape: (1, 96)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ pop ┆ pop ┆ pop ┆ mal ┆ mal ┆ mal ┆ mal ┆ mal ┆ mal ┆ fem ┆ fem ┆ fem ┆ fem ┆ fem ┆ fem ┆ mal ┆ fem ┆ med ┆ dis ┆ dis ┆ dis ┆ edu ┆ edu ┆ edu ┆ edu ┆ edu ┆ pov ┆ pov ┆ med ┆ lab ┆ lab ┆ une ┆ hou ┆ hou ┆ hou ┆ med ┆ med ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ lan ┆ lim ┆ lim ┆ lim ┆ no_ ┆ no_ ┆ no_ ┆ veh ┆ veh ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ pop ┆ pop ┆ dis ┆ edu ┆ lim ┆ no_ ┆ pct ┆ pct ┆ sex ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct │
│ ula ┆ ula ┆ ula ┆ e_6 ┆ e_6 ┆ e_7 ┆ e_7 ┆ e_8 ┆ e_8 ┆ ale ┆ ale ┆ ale ┆ ale ┆ ale ┆ ale ┆ e_u ┆ ale ┆ ian ┆ abi ┆ abi ┆ abi ┆ _hi ┆ _ba ┆ _ma ┆ _pr ┆ _do ┆ ert ┆ ert ┆ ian ┆ or_ ┆ or_ ┆ mpl ┆ sin ┆ sin ┆ sin ┆ ian ┆ ian ┆ e_u ┆ e_w ┆ e_b ┆ e_a ┆ e_a ┆ e_p ┆ e_h ┆ e_o ┆ gua ┆ ite ┆ ite ┆ ite ┆ eng ┆ eng ┆ eng ┆ icl ┆ icl ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ ula ┆ ula ┆ abi ┆ _to ┆ ite ┆ eng ┆ _ma ┆ _fe ┆ _ra ┆ _65 ┆ _un ┆ _di ┆ _hi ┆ _ba ┆ _gr ┆ _po ┆ _un ┆ _ho ┆ _ho ┆ _wh ┆ _bl ┆ _as ┆ _hi ┆ _am ┆ _pa ┆ _ra ┆ _li ┆ _no ┆ _ve ┆ _si ┆ _sm ┆ _la ┆ _mo │
│ tio ┆ tio ┆ tio ┆ 5_6 ┆ 7_6 ┆ 0_7 ┆ 5_7 ┆ 0_8 ┆ 5_p ┆ _65 ┆ _67 ┆ _70 ┆ _75 ┆ _80 ┆ _85 ┆ nde ┆ _un ┆ _ag ┆ lit ┆ lit ┆ lit ┆ gh_ ┆ che ┆ ste ┆ ofe ┆ cto ┆ y_u ┆ y_b ┆ _ho ┆ for ┆ for ┆ oym ┆ g_u ┆ g_o ┆ g_v ┆ _ho ┆ _gr ┆ niv ┆ hit ┆ lac ┆ mer ┆ sia ┆ aci ┆ isp ┆ the ┆ ge_ ┆ d_e ┆ d_e ┆ d_e ┆ lis ┆ lis ┆ lis ┆ e_u ┆ e_n ┆ g_s ┆ g_1 ┆ g_2 ┆ g_3 ┆ g_5 ┆ g_1 ┆ g_2 ┆ g_5 ┆ g_m ┆ tio ┆ tio ┆ lit ┆ tal ┆ d_e ┆ lis ┆ le  ┆ mal ┆ tio ┆ _pl ┆ der ┆ sab ┆ gh_ ┆ che ┆ ad_ ┆ ver ┆ emp ┆ usi ┆ usi ┆ ite ┆ ack ┆ ian ┆ spa ┆ eri ┆ cif ┆ ce_ ┆ mit ┆ _en ┆ hic ┆ ngl ┆ all ┆ rge ┆ bil │
│ n_t ┆ n_m ┆ n_f ┆ 6   ┆ 9   ┆ 4   ┆ 9   ┆ 4   ┆ lus ┆ _66 ┆ _69 ┆ _74 ┆ _79 ┆ _84 ┆ _pl ┆ r_5 ┆ der ┆ e   ┆ y_u ┆ y_1 ┆ y_6 ┆ sch ┆ lor ┆ rs  ┆ ssi ┆ rat ┆ niv ┆ elo ┆ use ┆ ce  ┆ ce_ ┆ ent ┆ nit ┆ ccu ┆ aca ┆ me_ ┆ oss ┆ ers ┆ e   ┆ k   ┆ ica ┆ n   ┆ fic ┆ ani ┆ r   ┆ uni ┆ ngl ┆ ngl ┆ ngl ┆ h_5 ┆ h_1 ┆ h_6 ┆ niv ┆ one ┆ tru ┆ _un ┆ _un ┆ _4_ ┆ _9_ ┆ 0_1 ┆ 0_4 ┆ 0_p ┆ obi ┆ n_6 ┆ n_u ┆ y_t ┆ --- ┆ ngl ┆ h_t ┆ --- ┆ e   ┆ --- ┆ us  ┆ _5  ┆ ili ┆ sch ┆ lor ┆ deg ┆ ty  ┆ loy ┆ ng_ ┆ ng_ ┆ --- ┆ --- ┆ --- ┆ nic ┆ can ┆ ic_ ┆ oth ┆ ed_ ┆ gli ┆ le_ ┆ e_f ┆ _mu ┆ _mu ┆ e_h │
│ ota ┆ ale ┆ ema ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ us  ┆ --- ┆ _5  ┆ --- ┆ nde ┆ 8_6 ┆ 5_p ┆ ool ┆ s   ┆ --- ┆ ona ┆ e   ┆ ers ┆ w   ┆ hol ┆ --- ┆ civ ┆ _ci ┆ s   ┆ pie ┆ nt  ┆ val ┆ _re ┆ e   ┆ --- ┆ --- ┆ n_i ┆ --- ┆ _is ┆ c   ┆ --- ┆ ver ┆ ish ┆ ish ┆ ish ┆ _17 ┆ 8_6 ┆ 5_p ┆ ers ┆ --- ┆ ctu ┆ it  ┆ it  ┆ uni ┆ uni ┆ 9_u ┆ 9_u ┆ lus ┆ le_ ┆ 5_p ┆ nde ┆ ota ┆ u32 ┆ ish ┆ ota ┆ u32 ┆ --- ┆ u32 ┆ --- ┆ --- ┆ ty  ┆ ool ┆ s   ┆ ree ┆ --- ┆ men ┆ occ ┆ vac ┆ u32 ┆ u32 ┆ u32 ┆ --- ┆ _in ┆ isl ┆ er  ┆ eng ┆ sh  ┆ non ┆ ami ┆ lti ┆ lti ┆ ome │
│ l   ┆ --- ┆ le  ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ --- ┆ u32 ┆ --- ┆ u32 ┆ r_1 ┆ 4   ┆ lus ┆ --- ┆ --- ┆ u32 ┆ l   ┆ --- ┆ e   ┆ --- ┆ d_i ┆ u32 ┆ ili ┆ vil ┆ --- ┆ d   ┆ --- ┆ ue  ┆ nt  ┆ --- ┆ u32 ┆ u32 ┆ ndi ┆ u32 ┆ lan ┆ --- ┆ u32 ┆ se  ┆ _5_ ┆ _18 ┆ _65 ┆ --- ┆ 4   ┆ lus ┆ e   ┆ u32 ┆ re_ ┆ --- ┆ --- ┆ t   ┆ t   ┆ nit ┆ nit ┆ _un ┆ hom ┆ lus ┆ r_5 ┆ l   ┆     ┆ _to ┆ l   ┆     ┆ u32 ┆     ┆ u32 ┆ u32 ┆ --- ┆ --- ┆ --- ┆ --- ┆ u32 ┆ t   ┆ upi ┆ ant ┆     ┆     ┆     ┆ u32 ┆ dia ┆ and ┆ --- ┆ lis ┆ --- ┆ e   ┆ ly  ┆ _fa ┆ _fa ┆ --- │
│ --- ┆ u32 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆ u32 ┆     ┆ 8   ┆ --- ┆ --- ┆ u32 ┆ u32 ┆     ┆ --- ┆ u32 ┆ --- ┆ u32 ┆ nco ┆     ┆ an  ┆ ian ┆ u32 ┆ --- ┆ u32 ┆ --- ┆ --- ┆ u32 ┆     ┆     ┆ an  ┆     ┆ der ┆ u32 ┆     ┆ --- ┆ 17  ┆ _64 ┆ _pl ┆ u32 ┆ --- ┆ --- ┆ --- ┆     ┆ uni ┆ u32 ┆ u32 ┆ --- ┆ --- ┆ --- ┆ --- ┆ it  ┆ e   ┆ --- ┆ --- ┆ --- ┆     ┆ tal ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆     ┆ --- ┆ ed  ┆ --- ┆     ┆     ┆     ┆     ┆ n   ┆ er  ┆ u32 ┆ h   ┆ u32 ┆ --- ┆ --- ┆ mil ┆ mil ┆ u32 │
│ u32 ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ u32 ┆ u32 ┆     ┆     ┆     ┆ u32 ┆     ┆ u32 ┆     ┆ me  ┆     ┆ --- ┆ --- ┆     ┆ u32 ┆     ┆ u32 ┆ u32 ┆     ┆     ┆     ┆ --- ┆     ┆ --- ┆     ┆     ┆ u32 ┆ --- ┆ --- ┆ us  ┆     ┆ u32 ┆ u32 ┆ u32 ┆     ┆ ver ┆     ┆     ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ --- ┆ --- ┆ u32 ┆ u32 ┆ u32 ┆     ┆ --- ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ --- ┆ u32 ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆ --- ┆     ┆ u32 ┆ u32 ┆ y   ┆ y   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ u32 ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆ u32 ┆     ┆     ┆     ┆ u32 ┆ u32 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ se  ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ u32 ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ u32 ┆     ┆ u32 ┆     ┆     ┆     ┆ --- ┆ --- ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ u32 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 131 ┆ 118 ┆ 115 ┆ 167 ┆ 209 ┆ 265 ┆ 189 ┆ 145 ┆ 142 ┆ 181 ┆ 217 ┆ 270 ┆ 203 ┆ 174 ┆ 205 ┆ 288 ┆ 287 ┆ 365 ┆ 123 ┆ 426 ┆ 423 ┆ 898 ┆ 877 ┆ 529 ┆ 221 ┆ 195 ┆ 131 ┆ 712 ┆ 145 ┆ 120 ┆ 120 ┆ 225 ┆ 112 ┆ 111 ┆ 451 ┆ 120 ┆ 768 ┆ 131 ┆ 130 ┆ 456 ┆ 133 ┆ 391 ┆ 33  ┆ 621 ┆ 119 ┆ 131 ┆ 11  ┆ 36  ┆ 13  ┆ 4   ┆ 10  ┆ 5   ┆ 111 ┆ 337 ┆ 112 ┆ 304 ┆ 369 ┆ 258 ┆ 345 ┆ 293 ┆ 304 ┆ 314 ┆ 289 ┆ 896 ┆ 470 ┆ 653 ┆ 115 ┆ 40  ┆ 15  ┆ 150 ┆ 150 ┆ 150 ┆ 151 ┆ 149 ┆ 150 ┆ 151 ┆ 150 ┆ 150 ┆ 151 ┆ 146 ┆ 142 ┆ 142 ┆ 151 ┆ 127 ┆ 124 ┆ 149 ┆ 782 ┆ 99  ┆ 694 ┆ 92  ┆ 18  ┆ 147 ┆ 141 ┆ 148 ┆ 132 ┆ 819 │
│ 5   ┆ 1   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆ 6   ┆ 7   ┆ 9   ┆     ┆ 4   ┆ 2   ┆     ┆ 3   ┆     ┆ 5   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆ 8   ┆ 8   ┆ 8   ┆ 2   ┆ 0   ┆ 9   ┆ 0   ┆ 7   ┆ 5   ┆ 5   ┆ 4   ┆ 6   ┆ 6   ┆ 2   ┆ 2   ┆ 9   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆ 1   ┆ 6   ┆ 8   ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘