In [1]:
import polars as pl

# Configure Polars so Jupyter shows ALL columns and a controlled
# number of rows. This prevents truncation and keeps rendering fast.

pl.Config.set_tbl_cols(-1)   # show all columns, no matter how many
pl.Config.set_tbl_rows(150)   # show only 10 rows in the HTML output

# Load the unified tract-quarter feature dataset
df = pl.read_parquet("../../data/processed/feature_engineering/tract_quarter_features.parquet")

In [2]:
# Extract column names between 'x' and 'y' (exclusive)
start_idx = df.columns.index("weighted_dry_bulb_temp_mean")
end_idx = df.columns.index("severe_weather_clusters")
middle_cols = df.columns[start_idx + 1 : end_idx]

print(middle_cols)

['weighted_dry_bulb_temp_median', 'weighted_dry_bulb_temp_std', 'weighted_dry_bulb_temp_min', 'weighted_dry_bulb_temp_max', 'weighted_dry_bulb_temp_range', 'weighted_dry_bulb_temp_cv', 'weighted_dry_bulb_temp_p10', 'weighted_dry_bulb_temp_p25', 'weighted_dry_bulb_temp_p75', 'weighted_dry_bulb_temp_p90', 'weighted_dry_bulb_temp_bucket_-999_0_hours', 'weighted_dry_bulb_temp_bucket_-999_0_prop', 'weighted_dry_bulb_temp_bucket_0_10_hours', 'weighted_dry_bulb_temp_bucket_0_10_prop', 'weighted_dry_bulb_temp_bucket_10_20_hours', 'weighted_dry_bulb_temp_bucket_10_20_prop', 'weighted_dry_bulb_temp_bucket_20_30_hours', 'weighted_dry_bulb_temp_bucket_20_30_prop', 'weighted_dry_bulb_temp_bucket_30_40_hours', 'weighted_dry_bulb_temp_bucket_30_40_prop', 'weighted_dry_bulb_temp_bucket_40_50_hours', 'weighted_dry_bulb_temp_bucket_40_50_prop', 'weighted_dry_bulb_temp_bucket_50_60_hours', 'weighted_dry_bulb_temp_bucket_50_60_prop', 'weighted_dry_bulb_temp_bucket_60_70_hours', 'weighted_dry_bulb_temp_bucket_60_70_prop', 'weighted_dry_bulb_temp_bucket_70_80_hours', 'weighted_dry_bulb_temp_bucket_70_80_prop', 'weighted_dry_bulb_temp_bucket_80_999_hours', 'weighted_dry_bulb_temp_bucket_80_999_prop', 'weighted_wet_bulb_temp_mean', 'weighted_wet_bulb_temp_median', 'weighted_wet_bulb_temp_std', 'weighted_wet_bulb_temp_min', 'weighted_wet_bulb_temp_max', 'weighted_wet_bulb_temp_range', 'weighted_wet_bulb_temp_cv', 'weighted_wet_bulb_temp_p10', 'weighted_wet_bulb_temp_p25', 'weighted_wet_bulb_temp_p75', 'weighted_wet_bulb_temp_p90', 'weighted_wet_bulb_temp_bucket_-999_0_hours', 'weighted_wet_bulb_temp_bucket_-999_0_prop', 'weighted_wet_bulb_temp_bucket_0_10_hours', 'weighted_wet_bulb_temp_bucket_0_10_prop', 'weighted_wet_bulb_temp_bucket_10_20_hours', 'weighted_wet_bulb_temp_bucket_10_20_prop', 'weighted_wet_bulb_temp_bucket_20_30_hours', 'weighted_wet_bulb_temp_bucket_20_30_prop', 'weighted_wet_bulb_temp_bucket_30_40_hours', 'weighted_wet_bulb_temp_bucket_30_40_prop', 'weighted_wet_bulb_temp_bucket_40_50_hours', 'weighted_wet_bulb_temp_bucket_40_50_prop', 'weighted_wet_bulb_temp_bucket_50_60_hours', 'weighted_wet_bulb_temp_bucket_50_60_prop', 'weighted_wet_bulb_temp_bucket_60_70_hours', 'weighted_wet_bulb_temp_bucket_60_70_prop', 'weighted_wet_bulb_temp_bucket_70_80_hours', 'weighted_wet_bulb_temp_bucket_70_80_prop', 'weighted_wet_bulb_temp_bucket_80_999_hours', 'weighted_wet_bulb_temp_bucket_80_999_prop', 'weighted_dew_point_temp_mean', 'weighted_dew_point_temp_median', 'weighted_dew_point_temp_std', 'weighted_dew_point_temp_min', 'weighted_dew_point_temp_max', 'weighted_dew_point_temp_range', 'weighted_dew_point_temp_cv', 'weighted_dew_point_temp_p10', 'weighted_dew_point_temp_p25', 'weighted_dew_point_temp_p75', 'weighted_dew_point_temp_p90', 'weighted_dew_point_temp_bucket_-999_0_hours', 'weighted_dew_point_temp_bucket_-999_0_prop', 'weighted_dew_point_temp_bucket_0_10_hours', 'weighted_dew_point_temp_bucket_0_10_prop', 'weighted_dew_point_temp_bucket_10_20_hours', 'weighted_dew_point_temp_bucket_10_20_prop', 'weighted_dew_point_temp_bucket_20_30_hours', 'weighted_dew_point_temp_bucket_20_30_prop', 'weighted_dew_point_temp_bucket_30_40_hours', 'weighted_dew_point_temp_bucket_30_40_prop', 'weighted_dew_point_temp_bucket_40_50_hours', 'weighted_dew_point_temp_bucket_40_50_prop', 'weighted_dew_point_temp_bucket_50_60_hours', 'weighted_dew_point_temp_bucket_50_60_prop', 'weighted_dew_point_temp_bucket_60_70_hours', 'weighted_dew_point_temp_bucket_60_70_prop', 'weighted_dew_point_temp_bucket_70_80_hours', 'weighted_dew_point_temp_bucket_70_80_prop', 'weighted_dew_point_temp_bucket_80_999_hours', 'weighted_dew_point_temp_bucket_80_999_prop', 'weighted_relative_humidity_mean', 'weighted_relative_humidity_median', 'weighted_relative_humidity_std', 'weighted_relative_humidity_min', 'weighted_relative_humidity_max', 'weighted_relative_humidity_range', 'weighted_relative_humidity_cv', 'weighted_relative_humidity_p10', 'weighted_relative_humidity_p25', 'weighted_relative_humidity_p75', 'weighted_relative_humidity_p90', 'weighted_relative_humidity_bucket_0_30_hours', 'weighted_relative_humidity_bucket_0_30_prop', 'weighted_relative_humidity_bucket_30_50_hours', 'weighted_relative_humidity_bucket_30_50_prop', 'weighted_relative_humidity_bucket_50_70_hours', 'weighted_relative_humidity_bucket_50_70_prop', 'weighted_relative_humidity_bucket_70_80_hours', 'weighted_relative_humidity_bucket_70_80_prop', 'weighted_relative_humidity_bucket_80_100_hours', 'weighted_relative_humidity_bucket_80_100_prop', 'weighted_wind_speed_mean', 'weighted_wind_speed_median', 'weighted_wind_speed_std', 'weighted_wind_speed_min', 'weighted_wind_speed_max', 'weighted_wind_speed_range', 'weighted_wind_speed_cv', 'weighted_wind_speed_p10', 'weighted_wind_speed_p25', 'weighted_wind_speed_p75', 'weighted_wind_speed_p90', 'weighted_wind_speed_bucket_0_5_hours', 'weighted_wind_speed_bucket_0_5_prop', 'weighted_wind_speed_bucket_5_10_hours', 'weighted_wind_speed_bucket_5_10_prop', 'weighted_wind_speed_bucket_10_15_hours', 'weighted_wind_speed_bucket_10_15_prop', 'weighted_wind_speed_bucket_15_20_hours', 'weighted_wind_speed_bucket_15_20_prop', 'weighted_wind_speed_bucket_20_30_hours', 'weighted_wind_speed_bucket_20_30_prop', 'weighted_wind_speed_bucket_30_999_hours', 'weighted_wind_speed_bucket_30_999_prop', 'weighted_wind_gust_speed_mean', 'weighted_wind_gust_speed_median', 'weighted_wind_gust_speed_std', 'weighted_wind_gust_speed_min', 'weighted_wind_gust_speed_max', 'weighted_wind_gust_speed_range', 'weighted_wind_gust_speed_cv', 'weighted_wind_gust_speed_p10', 'weighted_wind_gust_speed_p25', 'weighted_wind_gust_speed_p75', 'weighted_wind_gust_speed_p90', 'weighted_wind_gust_speed_bucket_0_20_hours', 'weighted_wind_gust_speed_bucket_0_20_prop', 'weighted_wind_gust_speed_bucket_20_30_hours', 'weighted_wind_gust_speed_bucket_20_30_prop', 'weighted_wind_gust_speed_bucket_30_40_hours', 'weighted_wind_gust_speed_bucket_30_40_prop', 'weighted_wind_gust_speed_bucket_40_50_hours', 'weighted_wind_gust_speed_bucket_40_50_prop', 'weighted_wind_gust_speed_bucket_50_999_hours', 'weighted_wind_gust_speed_bucket_50_999_prop', 'weighted_precipitation_mean', 'weighted_precipitation_median', 'weighted_precipitation_std', 'weighted_precipitation_min', 'weighted_precipitation_max', 'weighted_precipitation_range', 'weighted_precipitation_cv', 'weighted_precipitation_p10', 'weighted_precipitation_p25', 'weighted_precipitation_p75', 'weighted_precipitation_p90', 'weighted_precipitation_bucket_-0.0001_0.0001_hours', 'weighted_precipitation_bucket_-0.0001_0.0001_prop', 'weighted_precipitation_bucket_0.0001_0.01_hours', 'weighted_precipitation_bucket_0.0001_0.01_prop', 'weighted_precipitation_bucket_0.01_0.1_hours', 'weighted_precipitation_bucket_0.01_0.1_prop', 'weighted_precipitation_bucket_0.1_0.25_hours', 'weighted_precipitation_bucket_0.1_0.25_prop', 'weighted_precipitation_bucket_0.25_0.5_hours', 'weighted_precipitation_bucket_0.25_0.5_prop', 'weighted_precipitation_bucket_0.5_999_hours', 'weighted_precipitation_bucket_0.5_999_prop', 'weighted_visibility_mean', 'weighted_visibility_median', 'weighted_visibility_std', 'weighted_visibility_min', 'weighted_visibility_max', 'weighted_visibility_range', 'weighted_visibility_cv', 'weighted_visibility_p10', 'weighted_visibility_p25', 'weighted_visibility_p75', 'weighted_visibility_p90', 'weighted_visibility_bucket_0_1_hours', 'weighted_visibility_bucket_0_1_prop', 'weighted_visibility_bucket_1_2_hours', 'weighted_visibility_bucket_1_2_prop', 'weighted_visibility_bucket_2_5_hours', 'weighted_visibility_bucket_2_5_prop', 'weighted_visibility_bucket_5_999_hours', 'weighted_visibility_bucket_5_999_prop', 'weighted_station_pressure_mean', 'weighted_station_pressure_median', 'weighted_station_pressure_std', 'weighted_station_pressure_min', 'weighted_station_pressure_max', 'weighted_station_pressure_range', 'weighted_station_pressure_cv', 'weighted_station_pressure_p10', 'weighted_station_pressure_p25', 'weighted_station_pressure_p75', 'weighted_station_pressure_p90', 'weighted_station_pressure_bucket_28.0_28.75_hours', 'weighted_station_pressure_bucket_28.0_28.75_prop', 'weighted_station_pressure_bucket_28.75_29.25_hours', 'weighted_station_pressure_bucket_28.75_29.25_prop', 'weighted_station_pressure_bucket_29.25_29.75_hours', 'weighted_station_pressure_bucket_29.25_29.75_prop', 'weighted_station_pressure_bucket_29.75_31.0_hours', 'weighted_station_pressure_bucket_29.75_31.0_prop', 'weighted_barometric_pressure_mean', 'weighted_barometric_pressure_median', 'weighted_barometric_pressure_std', 'weighted_barometric_pressure_min', 'weighted_barometric_pressure_max', 'weighted_barometric_pressure_range', 'weighted_barometric_pressure_cv', 'weighted_barometric_pressure_p10', 'weighted_barometric_pressure_p25', 'weighted_barometric_pressure_p75', 'weighted_barometric_pressure_p90', 'weighted_barometric_pressure_bucket_28.0_28.75_hours', 'weighted_barometric_pressure_bucket_28.0_28.75_prop', 'weighted_barometric_pressure_bucket_28.75_29.25_hours', 'weighted_barometric_pressure_bucket_28.75_29.25_prop', 'weighted_barometric_pressure_bucket_29.25_29.75_hours', 'weighted_barometric_pressure_bucket_29.25_29.75_prop', 'weighted_barometric_pressure_bucket_29.75_31.0_hours', 'weighted_barometric_pressure_bucket_29.75_31.0_prop', 'temp_below_freezing_hours', 'temp_above_90_hours', 'gust_gt_20_hours', 'gust_gt_30_hours', 'gust_gt_40_hours', 'gust_gt_50_hours', 'precip_gt_0_01_hours', 'precip_gt_0_10_hours', 'precip_gt_0_25_hours', 'precip_gt_0_50_hours', 'visibility_lt_1_hours', 'low_pressure_hours', 'wet_windy_hours', 'cold_windy_hours', 'hot_humid_hours', 'storm_event_hours', 'observed_hours', 'expected_hours', 'coverage_ratio', 'wind_dir_resultant_length', 'wind_dir_circular_variance', 'sustained_high_wind_periods']

# Dry Bulb Temperature

In [4]:
dry_bulb_summary = [
    "weighted_dry_bulb_temp_median",
    "weighted_dry_bulb_temp_std",
    "weighted_dry_bulb_temp_min",
    "weighted_dry_bulb_temp_max",
    "weighted_dry_bulb_temp_range",
    "weighted_dry_bulb_temp_cv",
]

# Descriptive stats
print(df.select(dry_bulb_summary).describe())

# Correlation with reliability_index
print(
    df.select([
        pl.corr("reliability_index", c).alias(c)
        for c in dry_bulb_summary
    ])
)

shape: (9, 7)
┌────────────┬──────────────┬──────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ statistic  ┆ weighted_dry ┆ weighted_dry ┆ weighted_dr ┆ weighted_dr ┆ weighted_dr ┆ weighted_dr │
│ ---        ┆ _bulb_temp_m ┆ _bulb_temp_s ┆ y_bulb_temp ┆ y_bulb_temp ┆ y_bulb_temp ┆ y_bulb_temp │
│ str        ┆ edian        ┆ td           ┆ _min        ┆ _max        ┆ _range      ┆ _cv         │
│            ┆ ---          ┆ ---          ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│            ┆ f64          ┆ f64          ┆ f64         ┆ f64         ┆ f64         ┆ f64         │
╞════════════╪══════════════╪══════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ count      ┆ 10589.0      ┆ 10589.0      ┆ 10589.0     ┆ 10589.0     ┆ 10589.0     ┆ 10589.0     │
│ null_count ┆ 0.0          ┆ 0.0          ┆ 0.0         ┆ 0.0         ┆ 0.0         ┆ 0.0         │
│ mean       ┆ 49.180324    ┆ 12.880746    ┆ 9.112202    ┆ 83.671036   ┆ 74.558835   ┆ 0.312487    │
│ std        ┆ 15.791014    ┆ 2.482043     ┆ 17.299616   ┆ 8.551213    ┆ 11.493743   ┆ 0.1593      │
│ min        ┆ 11.590422    ┆ 6.828041     ┆ -28.0       ┆ 52.523496   ┆ 37.0        ┆ 0.096804    │
│ 25%        ┆ 32.818357    ┆ 11.021749    ┆ -7.835077   ┆ 77.015789   ┆ 66.214817   ┆ 0.190594    │
│ 50%        ┆ 53.76679     ┆ 13.264084    ┆ 11.649399   ┆ 86.207707   ┆ 76.666667   ┆ 0.252608    │
│ 75%        ┆ 62.164044    ┆ 14.662405    ┆ 22.576437   ┆ 91.19142    ┆ 82.40018    ┆ 0.419152    │
│ max        ┆ 74.0         ┆ 24.949204    ┆ 51.0        ┆ 97.0        ┆ 106.045742  ┆ 0.968556    │
└────────────┴──────────────┴──────────────┴─────────────┴─────────────┴─────────────┴─────────────┘
shape: (1, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ weighted_dry_b ┆ weighted_dry_b ┆ weighted_dry_b ┆ weighted_dry_ ┆ weighted_dry_ ┆ weighted_dry_ │
│ ulb_temp_media ┆ ulb_temp_std   ┆ ulb_temp_min   ┆ bulb_temp_max ┆ bulb_temp_ran ┆ bulb_temp_cv  │
│ n              ┆ ---            ┆ ---            ┆ ---           ┆ ge            ┆ ---           │
│ ---            ┆ f64            ┆ f64            ┆ f64           ┆ ---           ┆ f64           │
│ f64            ┆                ┆                ┆               ┆ f64           ┆               │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 0.069963       ┆ -0.095647      ┆ 0.089708       ┆ 0.072685      ┆ -0.080946     ┆ -0.107077     │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

In [5]:
dry_bulb_percentiles = [
    "weighted_dry_bulb_temp_p10",
    "weighted_dry_bulb_temp_p25",
    "weighted_dry_bulb_temp_p75",
    "weighted_dry_bulb_temp_p90",
]

print(df.select(dry_bulb_percentiles).describe())

print(
    df.select([
        pl.corr("reliability_index", c).alias(c)
        for c in dry_bulb_percentiles
    ])
)

shape: (9, 5)
┌────────────┬─────────────────────┬─────────────────────┬────────────────────┬────────────────────┐
│ statistic  ┆ weighted_dry_bulb_t ┆ weighted_dry_bulb_t ┆ weighted_dry_bulb_ ┆ weighted_dry_bulb_ │
│ ---        ┆ emp_p10             ┆ emp_p25             ┆ temp_p75           ┆ temp_p90           │
│ str        ┆ ---                 ┆ ---                 ┆ ---                ┆ ---                │
│            ┆ f64                 ┆ f64                 ┆ f64                ┆ f64                │
╞════════════╪═════════════════════╪═════════════════════╪════════════════════╪════════════════════╡
│ count      ┆ 10589.0             ┆ 10589.0             ┆ 10589.0            ┆ 10589.0            │
│ null_count ┆ 0.0                 ┆ 0.0                 ┆ 0.0                ┆ 0.0                │
│ mean       ┆ 31.911102           ┆ 40.837768           ┆ 57.332459          ┆ 65.021725          │
│ std        ┆ 18.454948           ┆ 16.798537           ┆ 15.403367          ┆ 14.382695          │
│ min        ┆ -6.333333           ┆ 6.0                 ┆ 18.764557          ┆ 21.335044          │
│ 25%        ┆ 15.270489           ┆ 27.054464           ┆ 38.838966          ┆ 47.711086          │
│ 50%        ┆ 36.694964           ┆ 44.880779           ┆ 63.423316          ┆ 70.560725          │
│ 75%        ┆ 43.551753           ┆ 54.424052           ┆ 69.909342          ┆ 77.218226          │
│ max        ┆ 64.0                ┆ 69.0                ┆ 79.0               ┆ 84.0               │
└────────────┴─────────────────────┴─────────────────────┴────────────────────┴────────────────────┘
shape: (1, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ weighted_dry_bulb_temp ┆ weighted_dry_bulb_temp ┆ weighted_dry_bulb_temp ┆ weighted_dry_bulb_tem │
│ _p10                   ┆ _p25                   ┆ _p75                   ┆ p_p90                 │
│ ---                    ┆ ---                    ┆ ---                    ┆ ---                   │
│ f64                    ┆ f64                    ┆ f64                    ┆ f64                   │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ 0.082775               ┆ 0.08253                ┆ 0.056924               ┆ 0.0571                │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

In [6]:
dry_bulb_bucket_counts = [
    c for c in df.columns
    if "weighted_dry_bulb_temp_bucket" in c and c.endswith("_hours")
]

df.select([
    pl.corr("reliability_index", c).alias(c)
    for c in dry_bulb_bucket_counts
])

shape: (1, 10)
┌─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬────────┐
│ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weight │
│ d_dry_b ┆ d_dry_b ┆ d_dry_b ┆ d_dry_b ┆ d_dry_b ┆ d_dry_b ┆ d_dry_b ┆ d_dry_b ┆ d_dry_b ┆ ed_dry │
│ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ _bulb_ │
│ p_bucke ┆ p_bucke ┆ p_bucke ┆ p_bucke ┆ p_bucke ┆ p_bucke ┆ p_bucke ┆ p_bucke ┆ p_bucke ┆ temp_b │
│ t_…     ┆ t_…     ┆ t_…     ┆ t_…     ┆ t_…     ┆ t_…     ┆ t_…     ┆ t_…     ┆ t_…     ┆ ucket_ │
│ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ …      │
│ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ ---    │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ f64    │
╞═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪════════╡
│ -0.1251 ┆ -0.0905 ┆ -0.0904 ┆ -0.0724 ┆ -0.0001 ┆ 0.01065 ┆ 0.01414 ┆ 0.04074 ┆ 0.05063 ┆ 0.0361 │
│ 52      ┆ 89      ┆ 84      ┆ 7       ┆ 34      ┆ 7       ┆         ┆ 1       ┆ 7       ┆ 72     │
└─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴────────┘

In [7]:
dry_bulb_bucket_props = [
    c for c in df.columns
    if "weighted_dry_bulb_temp_bucket" in c and c.endswith("_prop")
]

df.select([
    pl.corr("reliability_index", c).alias(c)
    for c in dry_bulb_bucket_props
])

shape: (1, 10)
┌─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬────────┐
│ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weight │
│ d_dry_b ┆ d_dry_b ┆ d_dry_b ┆ d_dry_b ┆ d_dry_b ┆ d_dry_b ┆ d_dry_b ┆ d_dry_b ┆ d_dry_b ┆ ed_dry │
│ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ _bulb_ │
│ p_bucke ┆ p_bucke ┆ p_bucke ┆ p_bucke ┆ p_bucke ┆ p_bucke ┆ p_bucke ┆ p_bucke ┆ p_bucke ┆ temp_b │
│ t_…     ┆ t_…     ┆ t_…     ┆ t_…     ┆ t_…     ┆ t_…     ┆ t_…     ┆ t_…     ┆ t_…     ┆ ucket_ │
│ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ …      │
│ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ ---    │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ f64    │
╞═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪════════╡
│ -0.1254 ┆ -0.0913 ┆ -0.0918 ┆ -0.0740 ┆ -0.0023 ┆ 0.01313 ┆ 0.01918 ┆ 0.04662 ┆ 0.05169 ┆ 0.0401 │
│ 95      ┆ 54      ┆ 86      ┆ 98      ┆ 25      ┆ 7       ┆         ┆         ┆ 1       ┆ 43     │
└─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴────────┘

# Wet Bulb Temperature

In [8]:
wet_bulb_summary = [
    "weighted_wet_bulb_temp_mean",
    "weighted_wet_bulb_temp_median",
    "weighted_wet_bulb_temp_std",
    "weighted_wet_bulb_temp_min",
    "weighted_wet_bulb_temp_max",
    "weighted_wet_bulb_temp_range",
    "weighted_wet_bulb_temp_cv",
]

print(df.select(wet_bulb_summary).describe())

print(
    df.select([
        pl.corr("reliability_index", c).alias(c)
        for c in wet_bulb_summary
    ])
)

shape: (9, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ weighted_w ┆ weighted_w ┆ weighted_ ┆ weighted_ ┆ weighted_ ┆ weighted_ ┆ weighted_ │
│ ---        ┆ et_bulb_te ┆ et_bulb_te ┆ wet_bulb_ ┆ wet_bulb_ ┆ wet_bulb_ ┆ wet_bulb_ ┆ wet_bulb_ │
│ str        ┆ mp_mean    ┆ mp_median  ┆ temp_std  ┆ temp_min  ┆ temp_max  ┆ temp_rang ┆ temp_cv   │
│            ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ e         ┆ ---       │
│            ┆ f64        ┆ f64        ┆ f64       ┆ f64       ┆ f64       ┆ ---       ┆ f64       │
│            ┆            ┆            ┆           ┆           ┆           ┆ f64       ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 10589.0    ┆ 10589.0    ┆ 10589.0   ┆ 10589.0   ┆ 10589.0   ┆ 10589.0   ┆ 10589.0   │
│ null_count ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 43.103697  ┆ 44.302878  ┆ 11.78692  ┆ 6.262078  ┆ 70.082918 ┆ 63.820841 ┆ 0.334098  │
│ std        ┆ 15.171414  ┆ 15.000302  ┆ 2.908966  ┆ 14.923728 ┆ 9.9058    ┆ 8.936798  ┆ 0.18822   │
│ min        ┆ 11.414159  ┆ 6.804021   ┆ 4.262367  ┆ -28.0     ┆ 32.286072 ┆ 27.0      ┆ 0.081073  │
│ 25%        ┆ 28.844844  ┆ 30.42477   ┆ 9.836309  ┆ -7.843574 ┆ 62.829727 ┆ 58.548385 ┆ 0.190612  │
│ 50%        ┆ 48.412144  ┆ 47.469563  ┆ 11.674091 ┆ 8.231214  ┆ 74.996916 ┆ 65.242825 ┆ 0.252195  │
│ 75%        ┆ 54.805038  ┆ 55.86022   ┆ 12.992397 ┆ 17.622948 ┆ 79.41036  ┆ 69.839651 ┆ 0.47026   │
│ max        ┆ 68.509484  ┆ 69.019959  ┆ 22.428217 ┆ 50.0      ┆ 84.333333 ┆ 89.199746 ┆ 1.029803  │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘
shape: (1, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ weighted_wet ┆ weighted_we ┆ weighted_we ┆ weighted_we ┆ weighted_we ┆ weighted_we ┆ weighted_we │
│ _bulb_temp_m ┆ t_bulb_temp ┆ t_bulb_temp ┆ t_bulb_temp ┆ t_bulb_temp ┆ t_bulb_temp ┆ t_bulb_temp │
│ ean          ┆ _median     ┆ _std        ┆ _min        ┆ _max        ┆ _range      ┆ _cv         │
│ ---          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│ f64          ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 0.061922     ┆ 0.068622    ┆ 0.011569    ┆ 0.054137    ┆ 0.079633    ┆ -0.002136   ┆ -0.052711   │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [9]:
wet_bulb_percentiles = [
    "weighted_wet_bulb_temp_p10",
    "weighted_wet_bulb_temp_p25",
    "weighted_wet_bulb_temp_p75",
    "weighted_wet_bulb_temp_p90",
]

print(df.select(wet_bulb_percentiles).describe())

print(
    df.select([
        pl.corr("reliability_index", c).alias(c)
        for c in wet_bulb_percentiles
    ])
)

shape: (9, 5)
┌────────────┬─────────────────────┬─────────────────────┬────────────────────┬────────────────────┐
│ statistic  ┆ weighted_wet_bulb_t ┆ weighted_wet_bulb_t ┆ weighted_wet_bulb_ ┆ weighted_wet_bulb_ │
│ ---        ┆ emp_p10             ┆ emp_p25             ┆ temp_p75           ┆ temp_p90           │
│ str        ┆ ---                 ┆ ---                 ┆ ---                ┆ ---                │
│            ┆ f64                 ┆ f64                 ┆ f64                ┆ f64                │
╞════════════╪═════════════════════╪═════════════════════╪════════════════════╪════════════════════╡
│ count      ┆ 10589.0             ┆ 10589.0             ┆ 10589.0            ┆ 10589.0            │
│ null_count ┆ 0.0                 ┆ 0.0                 ┆ 0.0                ┆ 0.0                │
│ mean       ┆ 27.502113           ┆ 35.636105           ┆ 51.352735          ┆ 57.073868          │
│ std        ┆ 18.607501           ┆ 17.60934            ┆ 13.875912          ┆ 13.336695          │
│ min        ┆ -7.0                ┆ 3.116834            ┆ 16.708167          ┆ 18.250459          │
│ 25%        ┆ 8.799525            ┆ 19.463642           ┆ 35.3912            ┆ 41.633893          │
│ 50%        ┆ 32.631673           ┆ 40.27708            ┆ 56.112743          ┆ 62.0               │
│ 75%        ┆ 39.217847           ┆ 48.45348            ┆ 62.683452          ┆ 68.937576          │
│ max        ┆ 61.0                ┆ 65.0                ┆ 72.692996          ┆ 75.167073          │
└────────────┴─────────────────────┴─────────────────────┴────────────────────┴────────────────────┘
shape: (1, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ weighted_wet_bulb_temp ┆ weighted_wet_bulb_temp ┆ weighted_wet_bulb_temp ┆ weighted_wet_bulb_tem │
│ _p10                   ┆ _p25                   ┆ _p75                   ┆ p_p90                 │
│ ---                    ┆ ---                    ┆ ---                    ┆ ---                   │
│ f64                    ┆ f64                    ┆ f64                    ┆ f64                   │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ 0.051459               ┆ 0.048013               ┆ 0.067982               ┆ 0.070953              │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

In [10]:
wet_bulb_bucket_counts = [
    c for c in df.columns
    if "weighted_wet_bulb_temp_bucket" in c and c.endswith("_hours")
]

df.select([
    pl.corr("reliability_index", c).alias(c)
    for c in wet_bulb_bucket_counts
])

shape: (1, 10)
┌─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬────────┐
│ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weight │
│ d_wet_b ┆ d_wet_b ┆ d_wet_b ┆ d_wet_b ┆ d_wet_b ┆ d_wet_b ┆ d_wet_b ┆ d_wet_b ┆ d_wet_b ┆ ed_wet │
│ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ _bulb_ │
│ p_bucke ┆ p_bucke ┆ p_bucke ┆ p_bucke ┆ p_bucke ┆ p_bucke ┆ p_bucke ┆ p_bucke ┆ p_bucke ┆ temp_b │
│ t_…     ┆ t_…     ┆ t_…     ┆ t_…     ┆ t_…     ┆ t_…     ┆ t_…     ┆ t_…     ┆ t_…     ┆ ucket_ │
│ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ …      │
│ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ ---    │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ f64    │
╞═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪════════╡
│ -0.1052 ┆ -0.0005 ┆ -0.0572 ┆ -0.0570 ┆ -0.0274 ┆ 0.01655 ┆ 0.02588 ┆ 0.05355 ┆ 0.05034 ┆ -0.028 │
│ 92      ┆ 8       ┆ 46      ┆ 47      ┆ 4       ┆ 4       ┆ 9       ┆ 3       ┆ 3       ┆ 63     │
└─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴────────┘

In [11]:
wet_bulb_bucket_props = [
    c for c in df.columns
    if "weighted_wet_bulb_temp_bucket" in c and c.endswith("_prop")
]

df.select([
    pl.corr("reliability_index", c).alias(c)
    for c in wet_bulb_bucket_props
])

shape: (1, 10)
┌─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬────────┐
│ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weight │
│ d_wet_b ┆ d_wet_b ┆ d_wet_b ┆ d_wet_b ┆ d_wet_b ┆ d_wet_b ┆ d_wet_b ┆ d_wet_b ┆ d_wet_b ┆ ed_wet │
│ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ ulb_tem ┆ _bulb_ │
│ p_bucke ┆ p_bucke ┆ p_bucke ┆ p_bucke ┆ p_bucke ┆ p_bucke ┆ p_bucke ┆ p_bucke ┆ p_bucke ┆ temp_b │
│ t_…     ┆ t_…     ┆ t_…     ┆ t_…     ┆ t_…     ┆ t_…     ┆ t_…     ┆ t_…     ┆ t_…     ┆ ucket_ │
│ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ …      │
│ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ ---    │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ f64    │
╞═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪════════╡
│ -0.1057 ┆ -0.0020 ┆ -0.0589 ┆ -0.0585 ┆ -0.0292 ┆ 0.01824 ┆ 0.03172 ┆ 0.05494 ┆ 0.04746 ┆ -0.025 │
│ 77      ┆ 6       ┆ 3       ┆ 09      ┆ 67      ┆ 7       ┆ 1       ┆ 4       ┆ 9       ┆ 899    │
└─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴────────┘

# Dew Point Temperature

In [12]:
dew_point_summary = [
    "weighted_dew_point_temp_mean",
    "weighted_dew_point_temp_median",
    "weighted_dew_point_temp_std",
    "weighted_dew_point_temp_min",
    "weighted_dew_point_temp_max",
    "weighted_dew_point_temp_range",
    "weighted_dew_point_temp_cv",
]

print(df.select(dew_point_summary).describe())

print(
    df.select([
        pl.corr("reliability_index", c).alias(c)
        for c in dew_point_summary
    ])
)

shape: (9, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ weighted_d ┆ weighted_d ┆ weighted_ ┆ weighted_ ┆ weighted_ ┆ weighted_ ┆ weighted_ │
│ ---        ┆ ew_point_t ┆ ew_point_t ┆ dew_point ┆ dew_point ┆ dew_point ┆ dew_point ┆ dew_point │
│ str        ┆ emp_mean   ┆ emp_median ┆ _temp_std ┆ _temp_min ┆ _temp_max ┆ _temp_ran ┆ _temp_cv  │
│            ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ge        ┆ ---       │
│            ┆ f64        ┆ f64        ┆ f64       ┆ f64       ┆ f64       ┆ ---       ┆ f64       │
│            ┆            ┆            ┆           ┆           ┆           ┆ f64       ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 10589.0    ┆ 10589.0    ┆ 10589.0   ┆ 10589.0   ┆ 10589.0   ┆ 10589.0   ┆ 10589.0   │
│ null_count ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 38.935327  ┆ 39.87354   ┆ 11.729996 ┆ 2.713477  ┆ 65.786249 ┆ 63.072772 ┆ 0.408864  │
│ std        ┆ 16.010348  ┆ 15.316276  ┆ 2.681356  ┆ 18.290004 ┆ 11.107715 ┆ 10.565508 ┆ 0.292714  │
│ min        ┆ 7.536998   ┆ 8.625431   ┆ 4.687021  ┆ -35.66666 ┆ 27.338275 ┆ 25.333333 ┆ 0.089282  │
│            ┆            ┆            ┆           ┆ 7         ┆           ┆           ┆           │
│ 25%        ┆ 23.921237  ┆ 26.752571  ┆ 9.505114  ┆ -14.03300 ┆ 55.65056  ┆ 55.789371 ┆ 0.192814  │
│            ┆            ┆            ┆           ┆ 7         ┆           ┆           ┆           │
│ 50%        ┆ 43.386151  ┆ 42.030995  ┆ 12.313332 ┆ 7.142613  ┆ 72.0      ┆ 64.492369 ┆ 0.305819  │
│ 75%        ┆ 52.068953  ┆ 52.77069   ┆ 13.879842 ┆ 16.54821  ┆ 75.236358 ┆ 72.048408 ┆ 0.498091  │
│ max        ┆ 66.058007  ┆ 67.333333  ┆ 21.307494 ┆ 48.0      ┆ 84.0      ┆ 85.834243 ┆ 1.980319  │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘
shape: (1, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ weighted_dew ┆ weighted_de ┆ weighted_de ┆ weighted_de ┆ weighted_de ┆ weighted_de ┆ weighted_de │
│ _point_temp_ ┆ w_point_tem ┆ w_point_tem ┆ w_point_tem ┆ w_point_tem ┆ w_point_tem ┆ w_point_tem │
│ mean         ┆ p_median    ┆ p_std       ┆ p_min       ┆ p_max       ┆ p_range     ┆ p_cv        │
│ ---          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│ f64          ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 0.074032     ┆ 0.081648    ┆ -0.045094   ┆ 0.058314    ┆ 0.068066    ┆ -0.029389   ┆ -0.095027   │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [13]:
dew_point_percentiles = [
    "weighted_dew_point_temp_p10",
    "weighted_dew_point_temp_p25",
    "weighted_dew_point_temp_p75",
    "weighted_dew_point_temp_p90",
]

print(df.select(dew_point_percentiles).describe())

print(
    df.select([
        pl.corr("reliability_index", c).alias(c)
        for c in dew_point_percentiles
    ])
)

shape: (9, 5)
┌────────────┬─────────────────────┬─────────────────────┬────────────────────┬────────────────────┐
│ statistic  ┆ weighted_dew_point_ ┆ weighted_dew_point_ ┆ weighted_dew_point ┆ weighted_dew_point │
│ ---        ┆ temp_p10            ┆ temp_p25            ┆ _temp_p75          ┆ _temp_p90          │
│ str        ┆ ---                 ┆ ---                 ┆ ---                ┆ ---                │
│            ┆ f64                 ┆ f64                 ┆ f64                ┆ f64                │
╞════════════╪═════════════════════╪═════════════════════╪════════════════════╪════════════════════╡
│ count      ┆ 10589.0             ┆ 10589.0             ┆ 10589.0            ┆ 10589.0            │
│ null_count ┆ 0.0                 ┆ 0.0                 ┆ 0.0                ┆ 0.0                │
│ mean       ┆ 22.9351             ┆ 31.750099           ┆ 47.177412          ┆ 53.166367          │
│ std        ┆ 19.677741           ┆ 17.41965            ┆ 14.723254          ┆ 14.609118          │
│ min        ┆ -15.0               ┆ -4.333333           ┆ 13.874023          ┆ 17.164421          │
│ 25%        ┆ 6.024754            ┆ 18.342879           ┆ 32.0               ┆ 35.744731          │
│ 50%        ┆ 26.549887           ┆ 34.609196           ┆ 52.08071           ┆ 59.583941          │
│ 75%        ┆ 37.690667           ┆ 46.640991           ┆ 59.439264          ┆ 66.420142          │
│ max        ┆ 57.333333           ┆ 62.0                ┆ 71.0               ┆ 73.468309          │
└────────────┴─────────────────────┴─────────────────────┴────────────────────┴────────────────────┘
shape: (1, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ weighted_dew_point_tem ┆ weighted_dew_point_tem ┆ weighted_dew_point_tem ┆ weighted_dew_point_te │
│ p_p10                  ┆ p_p25                  ┆ p_p75                  ┆ mp_p90                │
│ ---                    ┆ ---                    ┆ ---                    ┆ ---                   │
│ f64                    ┆ f64                    ┆ f64                    ┆ f64                   │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ 0.068768               ┆ 0.079037               ┆ 0.06884                ┆ 0.064015              │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

In [14]:
dew_point_bucket_counts = [
    c for c in df.columns
    if "weighted_dew_point_temp_bucket" in c and c.endswith("_hours")
]

df.select([
    pl.corr("reliability_index", c).alias(c)
    for c in dew_point_bucket_counts
])

shape: (1, 10)
┌─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬────────┐
│ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weight │
│ d_dew_p ┆ d_dew_p ┆ d_dew_p ┆ d_dew_p ┆ d_dew_p ┆ d_dew_p ┆ d_dew_p ┆ d_dew_p ┆ d_dew_p ┆ ed_dew │
│ oint_te ┆ oint_te ┆ oint_te ┆ oint_te ┆ oint_te ┆ oint_te ┆ oint_te ┆ oint_te ┆ oint_te ┆ _point │
│ mp_buck ┆ mp_buck ┆ mp_buck ┆ mp_buck ┆ mp_buck ┆ mp_buck ┆ mp_buck ┆ mp_buck ┆ mp_buck ┆ _temp_ │
│ et…     ┆ et…     ┆ et…     ┆ et…     ┆ et…     ┆ et…     ┆ et…     ┆ et…     ┆ et…     ┆ bucket │
│ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ …      │
│ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ ---    │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ f64    │
╞═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪════════╡
│ -0.0839 ┆ -0.0668 ┆ -0.0995 ┆ -0.0540 ┆ 0.02130 ┆ 0.03019 ┆ 0.03389 ┆ 0.05310 ┆ 0.03780 ┆ -0.021 │
│ 56      ┆ 27      ┆ 4       ┆ 97      ┆ 5       ┆ 4       ┆ 7       ┆ 4       ┆ 4       ┆ 749    │
└─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴────────┘

In [15]:
dew_point_bucket_props = [
    c for c in df.columns
    if "weighted_dew_point_temp_bucket" in c and c.endswith("_prop")
]

df.select([
    pl.corr("reliability_index", c).alias(c)
    for c in dew_point_bucket_props
])

shape: (1, 10)
┌─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬────────┐
│ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weighte ┆ weight │
│ d_dew_p ┆ d_dew_p ┆ d_dew_p ┆ d_dew_p ┆ d_dew_p ┆ d_dew_p ┆ d_dew_p ┆ d_dew_p ┆ d_dew_p ┆ ed_dew │
│ oint_te ┆ oint_te ┆ oint_te ┆ oint_te ┆ oint_te ┆ oint_te ┆ oint_te ┆ oint_te ┆ oint_te ┆ _point │
│ mp_buck ┆ mp_buck ┆ mp_buck ┆ mp_buck ┆ mp_buck ┆ mp_buck ┆ mp_buck ┆ mp_buck ┆ mp_buck ┆ _temp_ │
│ et…     ┆ et…     ┆ et…     ┆ et…     ┆ et…     ┆ et…     ┆ et…     ┆ et…     ┆ et…     ┆ bucket │
│ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ …      │
│ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ ---    │
│         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ f64    │
╞═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪════════╡
│ -0.0844 ┆ -0.0676 ┆ -0.1012 ┆ -0.0562 ┆ 0.01960 ┆ 0.03246 ┆ 0.03883 ┆ 0.05323 ┆ 0.03940 ┆ -0.021 │
│ 21      ┆ 35      ┆ 53      ┆ 4       ┆ 2       ┆ 5       ┆ 2       ┆ 5       ┆ 8       ┆ 729    │
└─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴────────┘

# Relative Humidity

In [16]:
rh_summary = [
    "weighted_relative_humidity_mean",
    "weighted_relative_humidity_median",
    "weighted_relative_humidity_std",
    "weighted_relative_humidity_min",
    "weighted_relative_humidity_max",
    "weighted_relative_humidity_range",
    "weighted_relative_humidity_cv",
]

print(df.select(rh_summary).describe())

print(
    df.select([
        pl.corr("reliability_index", c).alias(c)
        for c in rh_summary
    ])
)

shape: (9, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ weighted_r ┆ weighted_r ┆ weighted_ ┆ weighted_ ┆ weighted_ ┆ weighted_ ┆ weighted_ │
│ ---        ┆ elative_hu ┆ elative_hu ┆ relative_ ┆ relative_ ┆ relative_ ┆ relative_ ┆ relative_ │
│ str        ┆ midity_mea ┆ midity_med ┆ humidity_ ┆ humidity_ ┆ humidity_ ┆ humidity_ ┆ humidity_ │
│            ┆ …          ┆ …          ┆ std       ┆ min       ┆ max       ┆ ran…      ┆ cv        │
│            ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆ f64        ┆ f64        ┆ f64       ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 10589.0    ┆ 10589.0    ┆ 10589.0   ┆ 10589.0   ┆ 10589.0   ┆ 10589.0   ┆ 10589.0   │
│ null_count ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 68.233354  ┆ 69.97135   ┆ 17.663862 ┆ 18.128633 ┆ 98.077046 ┆ 79.948413 ┆ 0.260911  │
│ std        ┆ 5.778764   ┆ 6.903311   ┆ 2.407666  ┆ 7.366113  ┆ 4.039957  ┆ 8.056655  ┆ 0.044224  │
│ min        ┆ 23.989236  ┆ 20.091723  ┆ 9.725832  ┆ 1.63076   ┆ 55.044611 ┆ 46.879615 ┆ 0.140585  │
│ 25%        ┆ 65.455351  ┆ 66.315497  ┆ 16.041922 ┆ 12.319512 ┆ 97.715231 ┆ 74.687892 ┆ 0.233132  │
│ 50%        ┆ 68.372036  ┆ 70.361588  ┆ 17.307595 ┆ 18.245807 ┆ 98.74229  ┆ 80.0      ┆ 0.253358  │
│ 75%        ┆ 71.713517  ┆ 74.026558  ┆ 18.973594 ┆ 23.414181 ┆ 99.699184 ┆ 86.163234 ┆ 0.278641  │
│ max        ┆ 87.279241  ┆ 98.0       ┆ 34.335899 ┆ 43.296444 ┆ 100.0     ┆ 97.837705 ┆ 0.775678  │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘
shape: (1, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ weighted_rel ┆ weighted_re ┆ weighted_re ┆ weighted_re ┆ weighted_re ┆ weighted_re ┆ weighted_re │
│ ative_humidi ┆ lative_humi ┆ lative_humi ┆ lative_humi ┆ lative_humi ┆ lative_humi ┆ lative_humi │
│ ty_mea…      ┆ dity_med…   ┆ dity_std    ┆ dity_min    ┆ dity_max    ┆ dity_ran…   ┆ dity_cv     │
│ ---          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│ f64          ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 0.047602     ┆ 0.026254    ┆ -0.190296   ┆ 0.088693    ┆ 0.030956    ┆ -0.065568   ┆ -0.193006   │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [17]:
rh_percentiles = [
    "weighted_relative_humidity_p10",
    "weighted_relative_humidity_p25",
    "weighted_relative_humidity_p75",
    "weighted_relative_humidity_p90",
]

print(df.select(rh_percentiles).describe())

print(
    df.select([
        pl.corr("reliability_index", c).alias(c)
        for c in rh_percentiles
    ])
)

shape: (9, 5)
┌────────────┬─────────────────────┬─────────────────────┬────────────────────┬────────────────────┐
│ statistic  ┆ weighted_relative_h ┆ weighted_relative_h ┆ weighted_relative_ ┆ weighted_relative_ │
│ ---        ┆ umidity_p10         ┆ umidity_p25         ┆ humidity_p75       ┆ humidity_p90       │
│ str        ┆ ---                 ┆ ---                 ┆ ---                ┆ ---                │
│            ┆ f64                 ┆ f64                 ┆ f64                ┆ f64                │
╞════════════╪═════════════════════╪═════════════════════╪════════════════════╪════════════════════╡
│ count      ┆ 10589.0             ┆ 10589.0             ┆ 10589.0            ┆ 10589.0            │
│ null_count ┆ 0.0                 ┆ 0.0                 ┆ 0.0                ┆ 0.0                │
│ mean       ┆ 43.358895           ┆ 55.240449           ┆ 82.632746          ┆ 90.625081          │
│ std        ┆ 6.371239            ┆ 6.318659            ┆ 7.056056           ┆ 6.006522           │
│ min        ┆ 12.437733           ┆ 15.679972           ┆ 22.961969          ┆ 25.319299          │
│ 25%        ┆ 40.0                ┆ 51.683801           ┆ 79.119636          ┆ 88.459669          │
│ 50%        ┆ 43.898118           ┆ 55.15954            ┆ 83.250458          ┆ 91.503707          │
│ 75%        ┆ 47.221489           ┆ 59.730688           ┆ 86.789243          ┆ 94.155518          │
│ max        ┆ 71.0                ┆ 79.0                ┆ 100.0              ┆ 100.0              │
└────────────┴─────────────────────┴─────────────────────┴────────────────────┴────────────────────┘
shape: (1, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ weighted_relative_humi ┆ weighted_relative_humi ┆ weighted_relative_humi ┆ weighted_relative_hum │
│ dity_p10               ┆ dity_p25               ┆ dity_p75               ┆ idity_p90             │
│ ---                    ┆ ---                    ┆ ---                    ┆ ---                   │
│ f64                    ┆ f64                    ┆ f64                    ┆ f64                   │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ 0.160245               ┆ 0.100411               ┆ -0.026717              ┆ -0.043283             │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

In [18]:
rh_bucket_counts = [
    c for c in df.columns
    if "weighted_relative_humidity_bucket" in c and c.endswith("_hours")
]

df.select([
    pl.corr("reliability_index", c).alias(c)
    for c in rh_bucket_counts
])

shape: (1, 5)
┌───────────────────┬───────────────────┬───────────────────┬───────────────────┬──────────────────┐
│ weighted_relative ┆ weighted_relative ┆ weighted_relative ┆ weighted_relative ┆ weighted_relativ │
│ _humidity_buc…    ┆ _humidity_buc…    ┆ _humidity_buc…    ┆ _humidity_buc…    ┆ e_humidity_buc…  │
│ ---               ┆ ---               ┆ ---               ┆ ---               ┆ ---              │
│ f64               ┆ f64               ┆ f64               ┆ f64               ┆ f64              │
╞═══════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪══════════════════╡
│ -0.182697         ┆ -0.091615         ┆ 0.099264          ┆ 0.12503           ┆ -0.042706        │
└───────────────────┴───────────────────┴───────────────────┴───────────────────┴──────────────────┘

In [19]:
rh_bucket_props = [
    c for c in df.columns
    if "weighted_relative_humidity_bucket" in c and c.endswith("_prop")
]

df.select([
    pl.corr("reliability_index", c).alias(c)
    for c in rh_bucket_props
])

shape: (1, 5)
┌───────────────────┬───────────────────┬───────────────────┬───────────────────┬──────────────────┐
│ weighted_relative ┆ weighted_relative ┆ weighted_relative ┆ weighted_relative ┆ weighted_relativ │
│ _humidity_buc…    ┆ _humidity_buc…    ┆ _humidity_buc…    ┆ _humidity_buc…    ┆ e_humidity_buc…  │
│ ---               ┆ ---               ┆ ---               ┆ ---               ┆ ---              │
│ f64               ┆ f64               ┆ f64               ┆ f64               ┆ f64              │
╞═══════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪══════════════════╡
│ -0.181754         ┆ -0.088761         ┆ 0.134229          ┆ 0.156259          ┆ -0.03443         │
└───────────────────┴───────────────────┴───────────────────┴───────────────────┴──────────────────┘

# Wind Speed

In [20]:
wind_speed_summary = [
    "weighted_wind_speed_mean",
    "weighted_wind_speed_median",
    "weighted_wind_speed_std",
    "weighted_wind_speed_min",
    "weighted_wind_speed_max",
    "weighted_wind_speed_range",
    "weighted_wind_speed_cv",
]

print(df.select(wind_speed_summary).describe())

print(
    df.select([
        pl.corr("reliability_index", c).alias(c)
        for c in wind_speed_summary
    ])
)

shape: (9, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ weighted_w ┆ weighted_w ┆ weighted_ ┆ weighted_ ┆ weighted_ ┆ weighted_ ┆ weighted_ │
│ ---        ┆ ind_speed_ ┆ ind_speed_ ┆ wind_spee ┆ wind_spee ┆ wind_spee ┆ wind_spee ┆ wind_spee │
│ str        ┆ mean       ┆ median     ┆ d_std     ┆ d_min     ┆ d_max     ┆ d_range   ┆ d_cv      │
│            ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆ f64        ┆ f64        ┆ f64       ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 10589.0    ┆ 10589.0    ┆ 10589.0   ┆ 10589.0   ┆ 10589.0   ┆ 10589.0   ┆ 10589.0   │
│ null_count ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 7.243666   ┆ 6.872386   ┆ 4.370952  ┆ 0.00013   ┆ 23.544848 ┆ 23.544718 ┆ 0.619087  │
│ std        ┆ 1.66301    ┆ 1.621311   ┆ 0.675997  ┆ 0.006523  ┆ 4.619434  ┆ 4.619299  ┆ 0.086214  │
│ min        ┆ 1.843952   ┆ 0.634503   ┆ 1.844294  ┆ 0.0       ┆ 8.803397  ┆ 8.803397  ┆ 0.436703  │
│ 25%        ┆ 5.922498   ┆ 5.695064   ┆ 3.792535  ┆ 0.0       ┆ 19.452304 ┆ 19.452304 ┆ 0.557155  │
│ 50%        ┆ 7.54725    ┆ 7.141252   ┆ 4.614408  ┆ 0.0       ┆ 24.194929 ┆ 24.194929 ┆ 0.607844  │
│ 75%        ┆ 8.463569   ┆ 8.098984   ┆ 4.833822  ┆ 0.0       ┆ 26.928806 ┆ 26.926862 ┆ 0.659033  │
│ max        ┆ 12.325364  ┆ 11.333333  ┆ 6.155194  ┆ 0.502611  ┆ 39.333333 ┆ 39.333333 ┆ 1.37565   │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘
shape: (1, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ weighted_win ┆ weighted_wi ┆ weighted_wi ┆ weighted_wi ┆ weighted_wi ┆ weighted_wi ┆ weighted_wi │
│ d_speed_mean ┆ nd_speed_me ┆ nd_speed_st ┆ nd_speed_mi ┆ nd_speed_ma ┆ nd_speed_ra ┆ nd_speed_cv │
│ ---          ┆ dian        ┆ d           ┆ n           ┆ x           ┆ nge         ┆ ---         │
│ f64          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ f64         │
│              ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆             │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 0.135299     ┆ 0.154655    ┆ 0.025976    ┆ -0.013572   ┆ 0.002462    ┆ 0.002481    ┆ -0.22812    │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [21]:
wind_speed_percentiles = [
    "weighted_wind_speed_p10",
    "weighted_wind_speed_p25",
    "weighted_wind_speed_p75",
    "weighted_wind_speed_p90",
]

print(df.select(wind_speed_percentiles).describe())

print(
    df.select([
        pl.corr("reliability_index", c).alias(c)
        for c in wind_speed_percentiles
    ])
)

shape: (9, 5)
┌────────────┬─────────────────────┬─────────────────────┬────────────────────┬────────────────────┐
│ statistic  ┆ weighted_wind_speed ┆ weighted_wind_speed ┆ weighted_wind_spee ┆ weighted_wind_spee │
│ ---        ┆ _p10                ┆ _p25                ┆ d_p75              ┆ d_p90              │
│ str        ┆ ---                 ┆ ---                 ┆ ---                ┆ ---                │
│            ┆ f64                 ┆ f64                 ┆ f64                ┆ f64                │
╞════════════╪═════════════════════╪═════════════════════╪════════════════════╪════════════════════╡
│ count      ┆ 10589.0             ┆ 10589.0             ┆ 10589.0            ┆ 10589.0            │
│ null_count ┆ 0.0                 ┆ 0.0                 ┆ 0.0                ┆ 0.0                │
│ mean       ┆ 1.669634            ┆ 3.955203            ┆ 10.032036          ┆ 13.180414          │
│ std        ┆ 1.062301            ┆ 1.453777            ┆ 2.030911           ┆ 2.5429             │
│ min        ┆ 0.0                 ┆ 0.0                 ┆ 2.152685           ┆ 3.470158           │
│ 25%        ┆ 0.922471            ┆ 2.934804            ┆ 8.424135           ┆ 10.865306          │
│ 50%        ┆ 1.597634            ┆ 4.044015            ┆ 10.455958          ┆ 14.0               │
│ 75%        ┆ 2.432341            ┆ 5.044349            ┆ 11.537754          ┆ 15.147314          │
│ max        ┆ 6.333333            ┆ 8.333333            ┆ 15.333333          ┆ 20.333333          │
└────────────┴─────────────────────┴─────────────────────┴────────────────────┴────────────────────┘
shape: (1, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ weighted_wind_speed_p1 ┆ weighted_wind_speed_p2 ┆ weighted_wind_speed_p7 ┆ weighted_wind_speed_p │
│ 0                      ┆ 5                      ┆ 5                      ┆ 90                    │
│ ---                    ┆ ---                    ┆ ---                    ┆ ---                   │
│ f64                    ┆ f64                    ┆ f64                    ┆ f64                   │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ 0.169341               ┆ 0.165317               ┆ 0.125902               ┆ 0.094906              │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

In [22]:
wind_speed_bucket_counts = [
    c for c in df.columns
    if "weighted_wind_speed_bucket" in c and c.endswith("_hours")
]

df.select([
    pl.corr("reliability_index", c).alias(c)
    for c in wind_speed_bucket_counts
])

shape: (1, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ weighted_wind_ ┆ weighted_wind_ ┆ weighted_wind_ ┆ weighted_wind ┆ weighted_wind ┆ weighted_wind │
│ speed_bucket_0 ┆ speed_bucket_5 ┆ speed_bucket_1 ┆ _speed_bucket ┆ _speed_bucket ┆ _speed_bucket │
│ _5…            ┆ _1…            ┆ 0_…            ┆ _15_…         ┆ _20_…         ┆ _30_…         │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ f64            ┆ f64            ┆ f64            ┆ f64           ┆ f64           ┆ f64           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ -0.188133      ┆ 0.044754       ┆ 0.102054       ┆ 0.091651      ┆ 0.008133      ┆ -0.062644     │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

In [23]:
wind_speed_bucket_props = [
    c for c in df.columns
    if "weighted_wind_speed_bucket" in c and c.endswith("_prop")
]

df.select([
    pl.corr("reliability_index", c).alias(c)
    for c in wind_speed_bucket_props
])

shape: (1, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ weighted_wind_ ┆ weighted_wind_ ┆ weighted_wind_ ┆ weighted_wind ┆ weighted_wind ┆ weighted_wind │
│ speed_bucket_0 ┆ speed_bucket_5 ┆ speed_bucket_1 ┆ _speed_bucket ┆ _speed_bucket ┆ _speed_bucket │
│ _5…            ┆ _1…            ┆ 0_…            ┆ _15_…         ┆ _20_…         ┆ _30_…         │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ f64            ┆ f64            ┆ f64            ┆ f64           ┆ f64           ┆ f64           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ -0.158377      ┆ 0.099188       ┆ 0.119181       ┆ 0.092789      ┆ 0.007018      ┆ -0.062644     │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

# Wind Gust Speed

In [24]:
wind_gust_summary = [
    "weighted_wind_gust_speed_mean",
    "weighted_wind_gust_speed_median",
    "weighted_wind_gust_speed_std",
    "weighted_wind_gust_speed_min",
    "weighted_wind_gust_speed_max",
    "weighted_wind_gust_speed_range",
    "weighted_wind_gust_speed_cv",
]

print(df.select(wind_gust_summary).describe())

print(
    df.select([
        pl.corr("reliability_index", c).alias(c)
        for c in wind_gust_summary
    ])
)

shape: (9, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ weighted_w ┆ weighted_w ┆ weighted_ ┆ weighted_ ┆ weighted_ ┆ weighted_ ┆ weighted_ │
│ ---        ┆ ind_gust_s ┆ ind_gust_s ┆ wind_gust ┆ wind_gust ┆ wind_gust ┆ wind_gust ┆ wind_gust │
│ str        ┆ peed_mean  ┆ peed_media ┆ _speed_st ┆ _speed_mi ┆ _speed_ma ┆ _speed_ra ┆ _speed_cv │
│            ┆ ---        ┆ …          ┆ d         ┆ n         ┆ x         ┆ nge       ┆ ---       │
│            ┆ f64        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ f64       │
│            ┆            ┆ f64        ┆ f64       ┆ f64       ┆ f64       ┆ f64       ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 10589.0    ┆ 10589.0    ┆ 10589.0   ┆ 10589.0   ┆ 10589.0   ┆ 10589.0   ┆ 10589.0   │
│ null_count ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 14.191835  ┆ 12.763563  ┆ 8.214091  ┆ 3.723454  ┆ 40.091869 ┆ 36.368415 ┆ 0.605395  │
│ std        ┆ 3.501911   ┆ 4.235973   ┆ 1.659994  ┆ 3.462647  ┆ 7.384076  ┆ 7.48014   ┆ 0.138368  │
│ min        ┆ 5.241832   ┆ 2.911235   ┆ 2.647911  ┆ 0.793378  ┆ 15.694668 ┆ 11.978269 ┆ 0.138664  │
│ 25%        ┆ 12.579178  ┆ 10.50372   ┆ 6.978293  ┆ 1.751937  ┆ 35.93379  ┆ 31.25304  ┆ 0.54093   │
│ 50%        ┆ 14.393249  ┆ 12.692339  ┆ 8.661671  ┆ 2.482972  ┆ 40.267222 ┆ 37.082186 ┆ 0.63458   │
│ 75%        ┆ 15.887516  ┆ 14.685421  ┆ 9.48688   ┆ 3.994291  ┆ 45.0      ┆ 41.709676 ┆ 0.697487  │
│ max        ┆ 27.443038  ┆ 26.0       ┆ 11.715836 ┆ 17.0      ┆ 79.0      ┆ 68.502489 ┆ 0.966208  │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘
shape: (1, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ weighted_win ┆ weighted_wi ┆ weighted_wi ┆ weighted_wi ┆ weighted_wi ┆ weighted_wi ┆ weighted_wi │
│ d_gust_speed ┆ nd_gust_spe ┆ nd_gust_spe ┆ nd_gust_spe ┆ nd_gust_spe ┆ nd_gust_spe ┆ nd_gust_spe │
│ _mean        ┆ ed_media…   ┆ ed_std      ┆ ed_min      ┆ ed_max      ┆ ed_range    ┆ ed_cv       │
│ ---          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│ f64          ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ -0.160015    ┆ -0.172296   ┆ 0.234819    ┆ -0.264225   ┆ 0.029662    ┆ 0.151594    ┆ 0.311802    │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [25]:
wind_gust_percentiles = [
    "weighted_wind_gust_speed_p10",
    "weighted_wind_gust_speed_p25",
    "weighted_wind_gust_speed_p75",
    "weighted_wind_gust_speed_p90",
]

print(df.select(wind_gust_percentiles).describe())

print(
    df.select([
        pl.corr("reliability_index", c).alias(c)
        for c in wind_gust_percentiles
    ])
)

shape: (9, 5)
┌────────────┬─────────────────────┬─────────────────────┬────────────────────┬────────────────────┐
│ statistic  ┆ weighted_wind_gust_ ┆ weighted_wind_gust_ ┆ weighted_wind_gust ┆ weighted_wind_gust │
│ ---        ┆ speed_p10           ┆ speed_p25           ┆ _speed_p75         ┆ _speed_p90         │
│ str        ┆ ---                 ┆ ---                 ┆ ---                ┆ ---                │
│            ┆ f64                 ┆ f64                 ┆ f64                ┆ f64                │
╞════════════╪═════════════════════╪═════════════════════╪════════════════════╪════════════════════╡
│ count      ┆ 10589.0             ┆ 10589.0             ┆ 10589.0            ┆ 10589.0            │
│ null_count ┆ 0.0                 ┆ 0.0                 ┆ 0.0                ┆ 0.0                │
│ mean       ┆ 4.770771            ┆ 6.850489            ┆ 20.354581          ┆ 25.864478          │
│ std        ┆ 3.586613            ┆ 3.594654            ┆ 4.382958           ┆ 4.08867            │
│ min        ┆ 1.279152            ┆ 1.631637            ┆ 7.160814           ┆ 9.822734           │
│ 25%        ┆ 2.729116            ┆ 4.800297            ┆ 18.28698           ┆ 23.088455          │
│ 50%        ┆ 3.477905            ┆ 5.851543            ┆ 21.703774          ┆ 27.092473          │
│ 75%        ┆ 5.384609            ┆ 7.639819            ┆ 23.273074          ┆ 28.816277          │
│ max        ┆ 21.0                ┆ 23.0                ┆ 31.0               ┆ 36.0               │
└────────────┴─────────────────────┴─────────────────────┴────────────────────┴────────────────────┘
shape: (1, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ weighted_wind_gust_spe ┆ weighted_wind_gust_spe ┆ weighted_wind_gust_spe ┆ weighted_wind_gust_sp │
│ ed_p10                 ┆ ed_p25                 ┆ ed_p75                 ┆ eed_p90               │
│ ---                    ┆ ---                    ┆ ---                    ┆ ---                   │
│ f64                    ┆ f64                    ┆ f64                    ┆ f64                   │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ -0.265712              ┆ -0.256706              ┆ -0.049279              ┆ 0.021917              │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

In [26]:
wind_gust_bucket_counts = [
    c for c in df.columns
    if "weighted_wind_gust_speed_bucket" in c and c.endswith("_hours")
]

df.select([
    pl.corr("reliability_index", c).alias(c)
    for c in wind_gust_bucket_counts
])

shape: (1, 5)
┌───────────────────┬───────────────────┬───────────────────┬───────────────────┬──────────────────┐
│ weighted_wind_gus ┆ weighted_wind_gus ┆ weighted_wind_gus ┆ weighted_wind_gus ┆ weighted_wind_gu │
│ t_speed_bucke…    ┆ t_speed_bucke…    ┆ t_speed_bucke…    ┆ t_speed_bucke…    ┆ st_speed_bucke…  │
│ ---               ┆ ---               ┆ ---               ┆ ---               ┆ ---              │
│ f64               ┆ f64               ┆ f64               ┆ f64               ┆ f64              │
╞═══════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪══════════════════╡
│ 0.173242          ┆ -0.020534         ┆ 0.083234          ┆ 0.035431          ┆ -0.014986        │
└───────────────────┴───────────────────┴───────────────────┴───────────────────┴──────────────────┘

In [27]:
wind_gust_bucket_props = [
    c for c in df.columns
    if "weighted_wind_gust_speed_bucket" in c and c.endswith("_prop")
]

df.select([
    pl.corr("reliability_index", c).alias(c)
    for c in wind_gust_bucket_props
])

shape: (1, 5)
┌───────────────────┬───────────────────┬───────────────────┬───────────────────┬──────────────────┐
│ weighted_wind_gus ┆ weighted_wind_gus ┆ weighted_wind_gus ┆ weighted_wind_gus ┆ weighted_wind_gu │
│ t_speed_bucke…    ┆ t_speed_bucke…    ┆ t_speed_bucke…    ┆ t_speed_bucke…    ┆ st_speed_bucke…  │
│ ---               ┆ ---               ┆ ---               ┆ ---               ┆ ---              │
│ f64               ┆ f64               ┆ f64               ┆ f64               ┆ f64              │
╞═══════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪══════════════════╡
│ 0.204005          ┆ -0.021699         ┆ 0.082123          ┆ 0.03434           ┆ -0.019859        │
└───────────────────┴───────────────────┴───────────────────┴───────────────────┴──────────────────┘

# Precipitation

In [28]:
precip_summary = [
    "weighted_precipitation_mean",
    "weighted_precipitation_median",
    "weighted_precipitation_std",
    "weighted_precipitation_min",
    "weighted_precipitation_max",
    "weighted_precipitation_range",
    "weighted_precipitation_cv",
]

print(df.select(precip_summary).describe())

print(
    df.select([
        pl.corr("reliability_index", c).alias(c)
        for c in precip_summary
    ])
)

shape: (9, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ weighted_p ┆ weighted_p ┆ weighted_ ┆ weighted_ ┆ weighted_ ┆ weighted_ ┆ weighted_ │
│ ---        ┆ recipitati ┆ recipitati ┆ precipita ┆ precipita ┆ precipita ┆ precipita ┆ precipita │
│ str        ┆ on_mean    ┆ on_median  ┆ tion_std  ┆ tion_min  ┆ tion_max  ┆ tion_rang ┆ tion_cv   │
│            ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ e         ┆ ---       │
│            ┆ f64        ┆ f64        ┆ f64       ┆ f64       ┆ f64       ┆ ---       ┆ f64       │
│            ┆            ┆            ┆           ┆           ┆           ┆ f64       ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 10577.0    ┆ 10577.0    ┆ 10575.0   ┆ 10577.0   ┆ 10577.0   ┆ 10577.0   ┆ 10575.0   │
│ null_count ┆ 12.0       ┆ 12.0       ┆ 14.0      ┆ 12.0      ┆ 12.0      ┆ 12.0      ┆ 14.0      │
│ mean       ┆ 0.009221   ┆ 0.002927   ┆ 0.025405  ┆ 0.000749  ┆ 0.365973  ┆ 0.365223  ┆ 5.262815  │
│ std        ┆ 0.016491   ┆ 0.007812   ┆ 0.024237  ┆ 0.002126  ┆ 0.27745   ┆ 0.277401  ┆ 2.095736  │
│ min        ┆ 0.000479   ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.01      ┆ 0.0       ┆ 0.0       │
│ 25%        ┆ 0.001981   ┆ 0.0        ┆ 0.010364  ┆ 0.0       ┆ 0.157284  ┆ 0.15676   ┆ 4.486477  │
│ 50%        ┆ 0.003251   ┆ 0.0        ┆ 0.018313  ┆ 0.0       ┆ 0.298195  ┆ 0.297782  ┆ 5.571704  │
│ 75%        ┆ 0.005448   ┆ 0.0        ┆ 0.030919  ┆ 0.0       ┆ 0.479609  ┆ 0.478685  ┆ 6.725403  │
│ max        ┆ 0.148448   ┆ 0.09       ┆ 0.24175   ┆ 0.01      ┆ 2.61      ┆ 2.61      ┆ 17.329887 │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘
shape: (1, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ weighted_pre ┆ weighted_pr ┆ weighted_pr ┆ weighted_pr ┆ weighted_pr ┆ weighted_pr ┆ weighted_pr │
│ cipitation_m ┆ ecipitation ┆ ecipitation ┆ ecipitation ┆ ecipitation ┆ ecipitation ┆ ecipitation │
│ ean          ┆ _median     ┆ _std        ┆ _min        ┆ _max        ┆ _range      ┆ _cv         │
│ ---          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│ f64          ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ -0.221525    ┆ -0.231534   ┆ -0.15746    ┆ -0.240351   ┆ -0.007119   ┆ -0.005278   ┆ 0.211765    │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [29]:
precip_percentiles = [
    "weighted_precipitation_p10",
    "weighted_precipitation_p25",
    "weighted_precipitation_p75",
    "weighted_precipitation_p90",
]

print(df.select(precip_percentiles).describe())

print(
    df.select([
        pl.corr("reliability_index", c).alias(c)
        for c in precip_percentiles
    ])
)

shape: (9, 5)
┌────────────┬─────────────────────┬─────────────────────┬────────────────────┬────────────────────┐
│ statistic  ┆ weighted_precipitat ┆ weighted_precipitat ┆ weighted_precipita ┆ weighted_precipita │
│ ---        ┆ ion_p10             ┆ ion_p25             ┆ tion_p75           ┆ tion_p90           │
│ str        ┆ ---                 ┆ ---                 ┆ ---                ┆ ---                │
│            ┆ f64                 ┆ f64                 ┆ f64                ┆ f64                │
╞════════════╪═════════════════════╪═════════════════════╪════════════════════╪════════════════════╡
│ count      ┆ 10577.0             ┆ 10577.0             ┆ 10577.0            ┆ 10577.0            │
│ null_count ┆ 12.0                ┆ 12.0                ┆ 12.0               ┆ 12.0               │
│ mean       ┆ 0.000831            ┆ 0.001192            ┆ 0.007829           ┆ 0.017814           │
│ std        ┆ 0.002216            ┆ 0.003271            ┆ 0.020739           ┆ 0.04371            │
│ min        ┆ 0.0                 ┆ 0.0                 ┆ 0.0                ┆ 0.0                │
│ 25%        ┆ 0.0                 ┆ 0.0                 ┆ 0.0                ┆ 0.0                │
│ 50%        ┆ 0.0                 ┆ 0.0                 ┆ 0.0                ┆ 0.0011             │
│ 75%        ┆ 0.0                 ┆ 0.0                 ┆ 0.0                ┆ 0.005658           │
│ max        ┆ 0.01                ┆ 0.04                ┆ 0.21               ┆ 0.42               │
└────────────┴─────────────────────┴─────────────────────┴────────────────────┴────────────────────┘
shape: (1, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ weighted_precipitation ┆ weighted_precipitation ┆ weighted_precipitation ┆ weighted_precipitatio │
│ _p10                   ┆ _p25                   ┆ _p75                   ┆ n_p90                 │
│ ---                    ┆ ---                    ┆ ---                    ┆ ---                   │
│ f64                    ┆ f64                    ┆ f64                    ┆ f64                   │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ -0.25083               ┆ -0.228275              ┆ -0.226277              ┆ -0.216856             │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

In [30]:
precip_bucket_counts = [
    c for c in df.columns
    if "weighted_precipitation_bucket" in c and c.endswith("_hours")
]

df.select([
    pl.corr("reliability_index", c).alias(c)
    for c in precip_bucket_counts
])

shape: (1, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ weighted_preci ┆ weighted_preci ┆ weighted_preci ┆ weighted_prec ┆ weighted_prec ┆ weighted_prec │
│ pitation_bucke ┆ pitation_bucke ┆ pitation_bucke ┆ ipitation_buc ┆ ipitation_buc ┆ ipitation_buc │
│ t_…            ┆ t_…            ┆ t_…            ┆ ket_…         ┆ ket_…         ┆ ket_…         │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ f64            ┆ f64            ┆ f64            ┆ f64           ┆ f64           ┆ f64           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 0.250804       ┆ 0.146364       ┆ 0.092844       ┆ -0.051287     ┆ -0.010692     ┆ 0.028455      │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

In [31]:
precip_bucket_props = [
    c for c in df.columns
    if "weighted_precipitation_bucket" in c and c.endswith("_prop")
]

df.select([
    pl.corr("reliability_index", c).alias(c)
    for c in precip_bucket_props
])

shape: (1, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ weighted_preci ┆ weighted_preci ┆ weighted_preci ┆ weighted_prec ┆ weighted_prec ┆ weighted_prec │
│ pitation_bucke ┆ pitation_bucke ┆ pitation_bucke ┆ ipitation_buc ┆ ipitation_buc ┆ ipitation_buc │
│ t_…            ┆ t_…            ┆ t_…            ┆ ket_…         ┆ ket_…         ┆ ket_…         │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ f64            ┆ f64            ┆ f64            ┆ f64           ┆ f64           ┆ f64           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 0.271269       ┆ 0.162117       ┆ 0.113171       ┆ -0.046001     ┆ 0.000332      ┆ 0.038855      │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

# Visibility

In [32]:
visibility_summary = [
    "weighted_visibility_mean",
    "weighted_visibility_median",
    "weighted_visibility_std",
    "weighted_visibility_min",
    "weighted_visibility_max",
    "weighted_visibility_range",
    "weighted_visibility_cv",
]

print(df.select(visibility_summary).describe())

print(
    df.select([
        pl.corr("reliability_index", c).alias(c)
        for c in visibility_summary
    ])
)

shape: (9, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ weighted_v ┆ weighted_v ┆ weighted_ ┆ weighted_ ┆ weighted_ ┆ weighted_ ┆ weighted_ │
│ ---        ┆ isibility_ ┆ isibility_ ┆ visibilit ┆ visibilit ┆ visibilit ┆ visibilit ┆ visibilit │
│ str        ┆ mean       ┆ median     ┆ y_std     ┆ y_min     ┆ y_max     ┆ y_range   ┆ y_cv      │
│            ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆ f64        ┆ f64        ┆ f64       ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 10589.0    ┆ 10589.0    ┆ 10589.0   ┆ 10589.0   ┆ 10589.0   ┆ 10589.0   ┆ 10589.0   │
│ null_count ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 8.906942   ┆ 9.765393   ┆ 1.914924  ┆ 0.483781  ┆ 9.985647  ┆ 9.501866  ┆ 0.217743  │
│ std        ┆ 0.624176   ┆ 0.709784   ┆ 0.462239  ┆ 0.631675  ┆ 0.485479  ┆ 0.714219  ┆ 0.061416  │
│ min        ┆ 2.721476   ┆ 2.391872   ┆ 0.76063   ┆ 0.0       ┆ 5.65084   ┆ 5.398079  ┆ 0.077926  │
│ 25%        ┆ 8.672185   ┆ 9.992049   ┆ 1.575135  ┆ 0.118961  ┆ 10.0      ┆ 9.512706  ┆ 0.17079   │
│ 50%        ┆ 9.034574   ┆ 10.0       ┆ 1.883011  ┆ 0.246118  ┆ 10.0      ┆ 9.75      ┆ 0.209115  │
│ 75%        ┆ 9.300021   ┆ 10.0       ┆ 2.260408  ┆ 0.458191  ┆ 10.0      ┆ 9.881301  ┆ 0.256916  │
│ max        ┆ 9.830238   ┆ 10.0       ┆ 3.750486  ┆ 4.138565  ┆ 13.87737  ┆ 13.324563 ┆ 0.746261  │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘
shape: (1, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ weighted_vis ┆ weighted_vi ┆ weighted_vi ┆ weighted_vi ┆ weighted_vi ┆ weighted_vi ┆ weighted_vi │
│ ibility_mean ┆ sibility_me ┆ sibility_st ┆ sibility_mi ┆ sibility_ma ┆ sibility_ra ┆ sibility_cv │
│ ---          ┆ dian        ┆ d           ┆ n           ┆ x           ┆ nge         ┆ ---         │
│ f64          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ f64         │
│              ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆             │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 0.114825     ┆ 0.092455    ┆ -0.061333   ┆ 0.120362    ┆ 0.110941    ┆ -0.031041   ┆ -0.085861   │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [33]:
visibility_percentiles = [
    "weighted_visibility_p10",
    "weighted_visibility_p25",
    "weighted_visibility_p75",
    "weighted_visibility_p90",
]

print(df.select(visibility_percentiles).describe())

print(
    df.select([
        pl.corr("reliability_index", c).alias(c)
        for c in visibility_percentiles
    ])
)

shape: (9, 5)
┌────────────┬─────────────────────┬─────────────────────┬────────────────────┬────────────────────┐
│ statistic  ┆ weighted_visibility ┆ weighted_visibility ┆ weighted_visibilit ┆ weighted_visibilit │
│ ---        ┆ _p10                ┆ _p25                ┆ y_p75              ┆ y_p90              │
│ str        ┆ ---                 ┆ ---                 ┆ ---                ┆ ---                │
│            ┆ f64                 ┆ f64                 ┆ f64                ┆ f64                │
╞════════════╪═════════════════════╪═════════════════════╪════════════════════╪════════════════════╡
│ count      ┆ 10589.0             ┆ 10589.0             ┆ 10589.0            ┆ 10589.0            │
│ null_count ┆ 0.0                 ┆ 0.0                 ┆ 0.0                ┆ 0.0                │
│ mean       ┆ 6.176058            ┆ 8.988135            ┆ 9.910318           ┆ 9.931158           │
│ std        ┆ 1.571759            ┆ 1.13464             ┆ 0.462869           ┆ 0.434505           │
│ min        ┆ 1.166037            ┆ 2.391872            ┆ 2.570487           ┆ 2.570487           │
│ 25%        ┆ 5.143585            ┆ 8.404609            ┆ 10.0               ┆ 10.0               │
│ 50%        ┆ 6.240153            ┆ 9.429914            ┆ 10.0               ┆ 10.0               │
│ 75%        ┆ 7.532528            ┆ 9.896084            ┆ 10.0               ┆ 10.0               │
│ max        ┆ 10.0                ┆ 10.0                ┆ 10.0               ┆ 10.0               │
└────────────┴─────────────────────┴─────────────────────┴────────────────────┴────────────────────┘
shape: (1, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ weighted_visibility_p1 ┆ weighted_visibility_p2 ┆ weighted_visibility_p7 ┆ weighted_visibility_p │
│ 0                      ┆ 5                      ┆ 5                      ┆ 90                    │
│ ---                    ┆ ---                    ┆ ---                    ┆ ---                   │
│ f64                    ┆ f64                    ┆ f64                    ┆ f64                   │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ 0.060694               ┆ 0.095033               ┆ 0.098608               ┆ 0.090749              │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

In [34]:
visibility_bucket_counts = [
    c for c in df.columns
    if "weighted_visibility_bucket" in c and c.endswith("_hours")
]

df.select([
    pl.corr("reliability_index", c).alias(c)
    for c in visibility_bucket_counts
])

shape: (1, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ weighted_visibility_bu ┆ weighted_visibility_bu ┆ weighted_visibility_bu ┆ weighted_visibility_b │
│ cket_0_1…              ┆ cket_1_2…              ┆ cket_2_5…              ┆ ucket_5_9…            │
│ ---                    ┆ ---                    ┆ ---                    ┆ ---                   │
│ f64                    ┆ f64                    ┆ f64                    ┆ f64                   │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ -0.056198              ┆ -0.028963              ┆ -0.109677              ┆ 0.006993              │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

In [35]:
visibility_bucket_props = [
    c for c in df.columns
    if "weighted_visibility_bucket" in c and c.endswith("_prop")
]

df.select([
    pl.corr("reliability_index", c).alias(c)
    for c in visibility_bucket_props
])

shape: (1, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ weighted_visibility_bu ┆ weighted_visibility_bu ┆ weighted_visibility_bu ┆ weighted_visibility_b │
│ cket_0_1…              ┆ cket_1_2…              ┆ cket_2_5…              ┆ ucket_5_9…            │
│ ---                    ┆ ---                    ┆ ---                    ┆ ---                   │
│ f64                    ┆ f64                    ┆ f64                    ┆ f64                   │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ -0.063936              ┆ -0.034723              ┆ -0.101005              ┆ 0.092361              │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

# Station Pressure

In [36]:
station_pressure_summary = [
    "weighted_station_pressure_mean",
    "weighted_station_pressure_median",
    "weighted_station_pressure_std",
    "weighted_station_pressure_min",
    "weighted_station_pressure_max",
    "weighted_station_pressure_range",
    "weighted_station_pressure_cv",
]

print(df.select(station_pressure_summary).describe())

print(
    df.select([
        pl.corr("reliability_index", c).alias(c)
        for c in station_pressure_summary
    ])
)

shape: (9, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ weighted_s ┆ weighted_s ┆ weighted_ ┆ weighted_ ┆ weighted_ ┆ weighted_ ┆ weighted_ │
│ ---        ┆ tation_pre ┆ tation_pre ┆ station_p ┆ station_p ┆ station_p ┆ station_p ┆ station_p │
│ str        ┆ ssure_mean ┆ ssure_medi ┆ ressure_s ┆ ressure_m ┆ ressure_m ┆ ressure_r ┆ ressure_c │
│            ┆ ---        ┆ …          ┆ td        ┆ in        ┆ ax        ┆ ang…      ┆ v         │
│            ┆ f64        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆ f64        ┆ f64       ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 10589.0    ┆ 10589.0    ┆ 10589.0   ┆ 10589.0   ┆ 10589.0   ┆ 10589.0   ┆ 10589.0   │
│ null_count ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 27.301141  ┆ 28.494099  ┆ 3.2288    ┆ 10.535106 ┆ 29.346919 ┆ 18.811813 ┆ 0.126724  │
│ std        ┆ 2.50855    ┆ 2.097379   ┆ 2.261973  ┆ 6.419657  ┆ 1.188284  ┆ 6.458088  ┆ 0.109155  │
│ min        ┆ 8.938619   ┆ 7.001009   ┆ 0.079154  ┆ 2.134492  ┆ 16.687492 ┆ 0.403333  ┆ 0.002735  │
│ 25%        ┆ 27.349496  ┆ 28.916865  ┆ 1.931969  ┆ 5.685092  ┆ 29.406928 ┆ 15.935778 ┆ 0.067293  │
│ 50%        ┆ 28.3189    ┆ 29.047921  ┆ 2.809235  ┆ 9.129284  ┆ 29.547653 ┆ 20.024607 ┆ 0.100804  │
│ 75%        ┆ 28.777768  ┆ 29.152706  ┆ 3.759524  ┆ 13.446123 ┆ 29.646911 ┆ 23.766563 ┆ 0.140969  │
│ max        ┆ 29.381738  ┆ 29.396666  ┆ 12.082981 ┆ 29.113334 ┆ 29.98     ┆ 27.51282  ┆ 0.708501  │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘
shape: (1, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ weighted_sta ┆ weighted_st ┆ weighted_st ┆ weighted_st ┆ weighted_st ┆ weighted_st ┆ weighted_st │
│ tion_pressur ┆ ation_press ┆ ation_press ┆ ation_press ┆ ation_press ┆ ation_press ┆ ation_press │
│ e_mean       ┆ ure_medi…   ┆ ure_std     ┆ ure_min     ┆ ure_max     ┆ ure_rang…   ┆ ure_cv      │
│ ---          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│ f64          ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 0.016351     ┆ 0.118611    ┆ 0.100465    ┆ -0.131992   ┆ 0.130991    ┆ 0.155309    ┆ 0.079891    │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [37]:
station_pressure_percentiles = [
    "weighted_station_pressure_p10",
    "weighted_station_pressure_p25",
    "weighted_station_pressure_p75",
    "weighted_station_pressure_p90",
]

print(df.select(station_pressure_percentiles).describe())

print(
    df.select([
        pl.corr("reliability_index", c).alias(c)
        for c in station_pressure_percentiles
    ])
)

shape: (9, 5)
┌────────────┬─────────────────────┬─────────────────────┬────────────────────┬────────────────────┐
│ statistic  ┆ weighted_station_pr ┆ weighted_station_pr ┆ weighted_station_p ┆ weighted_station_p │
│ ---        ┆ essure_p10          ┆ essure_p25          ┆ ressure_p75        ┆ ressure_p90        │
│ str        ┆ ---                 ┆ ---                 ┆ ---                ┆ ---                │
│            ┆ f64                 ┆ f64                 ┆ f64                ┆ f64                │
╞════════════╪═════════════════════╪═════════════════════╪════════════════════╪════════════════════╡
│ count      ┆ 10589.0             ┆ 10589.0             ┆ 10589.0            ┆ 10589.0            │
│ null_count ┆ 0.0                 ┆ 0.0                 ┆ 0.0                ┆ 0.0                │
│ mean       ┆ 24.991431           ┆ 26.278537           ┆ 28.952487          ┆ 29.082501          │
│ std        ┆ 6.255368            ┆ 5.262359            ┆ 1.327584           ┆ 1.305541           │
│ min        ┆ 2.636878            ┆ 2.962031            ┆ 7.491685           ┆ 7.557232           │
│ 25%        ┆ 23.363029           ┆ 26.280826           ┆ 29.085436          ┆ 29.211218          │
│ 50%        ┆ 28.491361           ┆ 28.849545           ┆ 29.216276          ┆ 29.322317          │
│ 75%        ┆ 28.818183           ┆ 28.994991           ┆ 29.302354          ┆ 29.413859          │
│ max        ┆ 29.23               ┆ 29.286668           ┆ 29.57              ┆ 29.75              │
└────────────┴─────────────────────┴─────────────────────┴────────────────────┴────────────────────┘
shape: (1, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ weighted_station_press ┆ weighted_station_press ┆ weighted_station_press ┆ weighted_station_pres │
│ ure_p10                ┆ ure_p25                ┆ ure_p75                ┆ sure_p90              │
│ ---                    ┆ ---                    ┆ ---                    ┆ ---                   │
│ f64                    ┆ f64                    ┆ f64                    ┆ f64                   │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ -0.03114               ┆ -0.028206              ┆ 0.131638               ┆ 0.129876              │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

In [38]:
station_pressure_bucket_counts = [
    c for c in df.columns
    if "weighted_station_pressure_bucket" in c and c.endswith("_hours")
]

df.select([
    pl.corr("reliability_index", c).alias(c)
    for c in station_pressure_bucket_counts
])

shape: (1, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ weighted_station_press ┆ weighted_station_press ┆ weighted_station_press ┆ weighted_station_pres │
│ ure_buck…              ┆ ure_buck…              ┆ ure_buck…              ┆ sure_buck…            │
│ ---                    ┆ ---                    ┆ ---                    ┆ ---                   │
│ f64                    ┆ f64                    ┆ f64                    ┆ f64                   │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ -0.272002              ┆ 0.106067               ┆ 0.1775                 ┆ -0.045858             │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

In [39]:
station_pressure_bucket_props = [
    c for c in df.columns
    if "weighted_station_pressure_bucket" in c and c.endswith("_prop")
]

df.select([
    pl.corr("reliability_index", c).alias(c)
    for c in station_pressure_bucket_props
])

shape: (1, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ weighted_station_press ┆ weighted_station_press ┆ weighted_station_press ┆ weighted_station_pres │
│ ure_buck…              ┆ ure_buck…              ┆ ure_buck…              ┆ sure_buck…            │
│ ---                    ┆ ---                    ┆ ---                    ┆ ---                   │
│ f64                    ┆ f64                    ┆ f64                    ┆ f64                   │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ -0.2694                ┆ 0.117675               ┆ 0.178053               ┆ -0.046929             │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

# Barometric Pressure

In [40]:
baro_summary = [
    "weighted_barometric_pressure_mean",
    "weighted_barometric_pressure_median",
    "weighted_barometric_pressure_std",
    "weighted_barometric_pressure_min",
    "weighted_barometric_pressure_max",
    "weighted_barometric_pressure_range",
    "weighted_barometric_pressure_cv",
]

print(df.select(baro_summary).describe())

print(
    df.select([
        pl.corr("reliability_index", c).alias(c)
        for c in baro_summary
    ])
)

shape: (9, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ weighted_b ┆ weighted_b ┆ weighted_ ┆ weighted_ ┆ weighted_ ┆ weighted_ ┆ weighted_ │
│ ---        ┆ arometric_ ┆ arometric_ ┆ barometri ┆ barometri ┆ barometri ┆ barometri ┆ barometri │
│ str        ┆ pressure_m ┆ pressure_m ┆ c_pressur ┆ c_pressur ┆ c_pressur ┆ c_pressur ┆ c_pressur │
│            ┆ …          ┆ …          ┆ e_s…      ┆ e_m…      ┆ e_m…      ┆ e_r…      ┆ e_c…      │
│            ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆ f64        ┆ f64        ┆ f64       ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 10589.0    ┆ 10589.0    ┆ 10589.0   ┆ 10589.0   ┆ 10589.0   ┆ 10589.0   ┆ 10589.0   │
│ null_count ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
│ mean       ┆ 29.005292  ┆ 29.426604  ┆ 1.997048  ┆ 12.999442 ┆ 30.304015 ┆ 17.304572 ┆ 0.071576  │
│ std        ┆ 1.909509   ┆ 2.164887   ┆ 1.35032   ┆ 6.572273  ┆ 1.202368  ┆ 6.582105  ┆ 0.057377  │
│ min        ┆ 9.264323   ┆ 7.213885   ┆ 0.082994  ┆ 2.195353  ┆ 17.266837 ┆ 0.413333  ┆ 0.002767  │
│ 25%        ┆ 29.104929  ┆ 29.918043  ┆ 1.062575  ┆ 7.920122  ┆ 30.362555 ┆ 14.027116 ┆ 0.035646  │
│ 50%        ┆ 29.701217  ┆ 29.991666  ┆ 1.760794  ┆ 12.352913 ┆ 30.423071 ┆ 17.84887  ┆ 0.059764  │
│ 75%        ┆ 29.861033  ┆ 30.027289  ┆ 2.604603  ┆ 16.022772 ┆ 30.572727 ┆ 22.319794 ┆ 0.089718  │
│ max        ┆ 30.071466  ┆ 30.085833  ┆ 10.967678 ┆ 29.83     ┆ 30.719999 ┆ 28.49836  ┆ 0.704612  │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘
shape: (1, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ weighted_bar ┆ weighted_ba ┆ weighted_ba ┆ weighted_ba ┆ weighted_ba ┆ weighted_ba ┆ weighted_ba │
│ ometric_pres ┆ rometric_pr ┆ rometric_pr ┆ rometric_pr ┆ rometric_pr ┆ rometric_pr ┆ rometric_pr │
│ sure_m…      ┆ essure_m…   ┆ essure_s…   ┆ essure_m…   ┆ essure_m…   ┆ essure_r…   ┆ essure_c…   │
│ ---          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│ f64          ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 0.105791     ┆ 0.099407    ┆ -0.027712   ┆ -0.079439   ┆ 0.090568    ┆ 0.095865    ┆ -0.048508   │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [41]:
baro_percentiles = [
    "weighted_barometric_pressure_p10",
    "weighted_barometric_pressure_p25",
    "weighted_barometric_pressure_p75",
    "weighted_barometric_pressure_p90",
]

print(df.select(baro_percentiles).describe())

print(
    df.select([
        pl.corr("reliability_index", c).alias(c)
        for c in baro_percentiles
    ])
)

shape: (9, 5)
┌────────────┬─────────────────────┬─────────────────────┬────────────────────┬────────────────────┐
│ statistic  ┆ weighted_barometric ┆ weighted_barometric ┆ weighted_barometri ┆ weighted_barometri │
│ ---        ┆ _pressure_p…        ┆ _pressure_p…        ┆ c_pressure_p…      ┆ c_pressure_p…      │
│ str        ┆ ---                 ┆ ---                 ┆ ---                ┆ ---                │
│            ┆ f64                 ┆ f64                 ┆ f64                ┆ f64                │
╞════════════╪═════════════════════╪═════════════════════╪════════════════════╪════════════════════╡
│ count      ┆ 10589.0             ┆ 10589.0             ┆ 10589.0            ┆ 10589.0            │
│ null_count ┆ 0.0                 ┆ 0.0                 ┆ 0.0                ┆ 0.0                │
│ mean       ┆ 27.673525           ┆ 28.706326           ┆ 29.899862          ┆ 30.02457           │
│ std        ┆ 3.945516            ┆ 2.881692            ┆ 1.328676           ┆ 1.320693           │
│ min        ┆ 6.221564            ┆ 7.178007            ┆ 7.720459           ┆ 7.786006           │
│ 25%        ┆ 26.918568           ┆ 29.733959           ┆ 30.069587          ┆ 30.175368          │
│ 50%        ┆ 29.622934           ┆ 29.805418           ┆ 30.117575          ┆ 30.210444          │
│ 75%        ┆ 29.704428           ┆ 29.871433           ┆ 30.15              ┆ 30.304961          │
│ max        ┆ 29.941113           ┆ 30.003446           ┆ 30.270551          ┆ 30.465371          │
└────────────┴─────────────────────┴─────────────────────┴────────────────────┴────────────────────┘
shape: (1, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ weighted_barometric_pr ┆ weighted_barometric_pr ┆ weighted_barometric_pr ┆ weighted_barometric_p │
│ essure_p…              ┆ essure_p…              ┆ essure_p…              ┆ ressure_p…            │
│ ---                    ┆ ---                    ┆ ---                    ┆ ---                   │
│ f64                    ┆ f64                    ┆ f64                    ┆ f64                   │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ 0.050261               ┆ 0.078959               ┆ 0.094529               ┆ 0.092042              │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

In [42]:
baro_bucket_counts = [
    c for c in df.columns
    if "weighted_barometric_pressure_bucket" in c and c.endswith("_hours")
]

df.select([
    pl.corr("reliability_index", c).alias(c)
    for c in baro_bucket_counts
])

shape: (1, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ weighted_barometric_pr ┆ weighted_barometric_pr ┆ weighted_barometric_pr ┆ weighted_barometric_p │
│ essure_b…              ┆ essure_b…              ┆ essure_b…              ┆ ressure_b…            │
│ ---                    ┆ ---                    ┆ ---                    ┆ ---                   │
│ f64                    ┆ f64                    ┆ f64                    ┆ f64                   │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ 0.106809               ┆ 0.032532               ┆ -0.070093              ┆ 0.05766               │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

In [43]:
baro_bucket_props = [
    c for c in df.columns
    if "weighted_barometric_pressure_bucket" in c and c.endswith("_prop")
]

df.select([
    pl.corr("reliability_index", c).alias(c)
    for c in baro_bucket_props
])

shape: (1, 4)
┌────────────────────────┬────────────────────────┬────────────────────────┬───────────────────────┐
│ weighted_barometric_pr ┆ weighted_barometric_pr ┆ weighted_barometric_pr ┆ weighted_barometric_p │
│ essure_b…              ┆ essure_b…              ┆ essure_b…              ┆ ressure_b…            │
│ ---                    ┆ ---                    ┆ ---                    ┆ ---                   │
│ f64                    ┆ f64                    ┆ f64                    ┆ f64                   │
╞════════════════════════╪════════════════════════╪════════════════════════╪═══════════════════════╡
│ 0.10683                ┆ 0.031338               ┆ -0.071887              ┆ 0.071303              │
└────────────────────────┴────────────────────────┴────────────────────────┴───────────────────────┘

# Engineered Conditional Features

In [ ]:
engineered_features_1 = [
    "temp_below_freezing_hours",
    "temp_above_90_hours",
    "gust_gt_20_hours",
    "gust_gt_30_hours",
    "gust_gt_40_hours",
    "gust_gt_50_hours",
]

engineered_features_2 = [
    "precip_gt_0_01_hours",
    "precip_gt_0_10_hours",
    "precip_gt_0_25_hours",
    "precip_gt_0_50_hours",
    "visibility_lt_1_hours",
    "low_pressure_hours",
]

engineered_features_3 = [
    "wet_windy_hours",
    "cold_windy_hours",
    "hot_humid_hours",
    "storm_event_hours",
    "observed_hours",
]

engineered_features_4 = [
    "expected_hours",
    "coverage_ratio",
    "wind_dir_resultant_length",
    "wind_dir_circular_variance",
    "sustained_high_wind_periods",
]

In [49]:
print(df.select(engineered_features_1).describe())

print(
    df.select([
        pl.corr("reliability_index", c).alias(c)
        for c in engineered_features_1
    ])
)

shape: (9, 7)
┌────────────┬──────────────┬──────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ statistic  ┆ temp_below_f ┆ temp_above_9 ┆ gust_gt_20_ ┆ gust_gt_30_ ┆ gust_gt_40_ ┆ gust_gt_50_ │
│ ---        ┆ reezing_hour ┆ 0_hours      ┆ hours       ┆ hours       ┆ hours       ┆ hours       │
│ str        ┆ s            ┆ ---          ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│            ┆ ---          ┆ f64          ┆ f64         ┆ f64         ┆ f64         ┆ f64         │
│            ┆ f64          ┆              ┆             ┆             ┆             ┆             │
╞════════════╪══════════════╪══════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ count      ┆ 10589.0      ┆ 10589.0      ┆ 10589.0     ┆ 10589.0     ┆ 10589.0     ┆ 10589.0     │
│ null_count ┆ 0.0          ┆ 0.0          ┆ 0.0         ┆ 0.0         ┆ 0.0         ┆ 0.0         │
│ mean       ┆ 477.845594   ┆ 3.368779     ┆ 223.196336  ┆ 43.283124   ┆ 2.469166    ┆ 0.069412    │
│ std        ┆ 554.406084   ┆ 6.209485     ┆ 132.283486  ┆ 36.929462   ┆ 3.900093    ┆ 0.265434    │
│ min        ┆ 0.0          ┆ 0.0          ┆ 0.0         ┆ 0.0         ┆ 0.0         ┆ 0.0         │
│ 25%        ┆ 17.0         ┆ 0.0          ┆ 58.0        ┆ 4.0         ┆ 0.0         ┆ 0.0         │
│ 50%        ┆ 87.0         ┆ 0.0          ┆ 265.0       ┆ 44.0        ┆ 1.0         ┆ 0.0         │
│ 75%        ┆ 971.0        ┆ 4.0          ┆ 322.0       ┆ 67.0        ┆ 4.0         ┆ 0.0         │
│ max        ┆ 2021.0       ┆ 35.0         ┆ 718.0       ┆ 180.0       ┆ 25.0        ┆ 3.0         │
└────────────┴──────────────┴──────────────┴─────────────┴─────────────┴─────────────┴─────────────┘
shape: (1, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ temp_below_fre ┆ temp_above_90_ ┆ gust_gt_20_hou ┆ gust_gt_30_ho ┆ gust_gt_40_ho ┆ gust_gt_50_ho │
│ ezing_hours    ┆ hours          ┆ rs             ┆ urs           ┆ urs           ┆ urs           │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ f64            ┆ f64            ┆ f64            ┆ f64           ┆ f64           ┆ f64           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ -0.080844      ┆ 0.07295        ┆ 0.028508       ┆ 0.099067      ┆ 0.04949       ┆ -0.014986     │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

In [50]:
print(df.select(engineered_features_2).describe())

print(
    df.select([
        pl.corr("reliability_index", c).alias(c)
        for c in engineered_features_2
    ])
)

shape: (9, 7)
┌────────────┬──────────────┬──────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ statistic  ┆ precip_gt_0_ ┆ precip_gt_0_ ┆ precip_gt_0 ┆ precip_gt_0 ┆ visibility_ ┆ low_pressur │
│ ---        ┆ 01_hours     ┆ 10_hours     ┆ _25_hours   ┆ _50_hours   ┆ lt_1_hours  ┆ e_hours     │
│ str        ┆ ---          ┆ ---          ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│            ┆ f64          ┆ f64          ┆ f64         ┆ f64         ┆ f64         ┆ f64         │
╞════════════╪══════════════╪══════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ count      ┆ 10589.0      ┆ 10589.0      ┆ 10589.0     ┆ 10589.0     ┆ 10589.0     ┆ 10589.0     │
│ null_count ┆ 0.0          ┆ 0.0          ┆ 0.0         ┆ 0.0         ┆ 0.0         ┆ 0.0         │
│ mean       ┆ 90.055529    ┆ 11.90169     ┆ 2.239305    ┆ 0.463878    ┆ 18.430824   ┆ 957.933516  │
│ std        ┆ 41.82181     ┆ 9.823675     ┆ 2.913395    ┆ 1.040792    ┆ 20.424385   ┆ 568.111168  │
│ min        ┆ 0.0          ┆ 0.0          ┆ 0.0         ┆ 0.0         ┆ 0.0         ┆ 0.0         │
│ 25%        ┆ 60.0         ┆ 4.0          ┆ 0.0         ┆ 0.0         ┆ 3.0         ┆ 510.0       │
│ 50%        ┆ 81.0         ┆ 10.0         ┆ 1.0         ┆ 0.0         ┆ 11.0        ┆ 899.0       │
│ 75%        ┆ 117.0        ┆ 16.0         ┆ 4.0         ┆ 0.0         ┆ 32.0        ┆ 1250.0      │
│ max        ┆ 229.0        ┆ 52.0         ┆ 17.0        ┆ 8.0         ┆ 206.0       ┆ 2208.0      │
└────────────┴──────────────┴──────────────┴─────────────┴─────────────┴─────────────┴─────────────┘
shape: (1, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ precip_gt_0_01 ┆ precip_gt_0_10 ┆ precip_gt_0_25 ┆ precip_gt_0_5 ┆ visibility_lt ┆ low_pressure_ │
│ _hours         ┆ _hours         ┆ _hours         ┆ 0_hours       ┆ _1_hours      ┆ hours         │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ f64            ┆ f64            ┆ f64            ┆ f64           ┆ f64           ┆ f64           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 0.071012       ┆ -0.039288      ┆ 0.004964       ┆ 0.030122      ┆ -0.049886     ┆ -0.223884     │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

In [51]:
print(df.select(engineered_features_3).describe())

print(
    df.select([
        pl.corr("reliability_index", c).alias(c)
        for c in engineered_features_3
    ])
)

shape: (9, 7)
┌────────────┬──────────────┬──────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ statistic  ┆ low_pressure ┆ wet_windy_ho ┆ cold_windy_ ┆ hot_humid_h ┆ storm_event ┆ observed_ho │
│ ---        ┆ _hours       ┆ urs          ┆ hours       ┆ ours        ┆ _hours      ┆ urs         │
│ str        ┆ ---          ┆ ---          ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│            ┆ f64          ┆ f64          ┆ f64         ┆ f64         ┆ f64         ┆ f64         │
╞════════════╪══════════════╪══════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ count      ┆ 10589.0      ┆ 10589.0      ┆ 10589.0     ┆ 10589.0     ┆ 10589.0     ┆ 10589.0     │
│ null_count ┆ 0.0          ┆ 0.0          ┆ 0.0         ┆ 0.0         ┆ 0.0         ┆ 0.0         │
│ mean       ┆ 957.933516   ┆ 18.71206     ┆ 33.610634   ┆ 0.007838    ┆ 0.005383    ┆ 2063.073189 │
│ std        ┆ 568.111168   ┆ 15.909919    ┆ 46.178465   ┆ 0.089255    ┆ 0.082859    ┆ 298.86947   │
│ min        ┆ 0.0          ┆ 0.0          ┆ 0.0         ┆ 0.0         ┆ 0.0         ┆ 186.0       │
│ 25%        ┆ 510.0        ┆ 4.0          ┆ 0.0         ┆ 0.0         ┆ 0.0         ┆ 2160.0      │
│ 50%        ┆ 899.0        ┆ 18.0         ┆ 3.0         ┆ 0.0         ┆ 0.0         ┆ 2184.0      │
│ 75%        ┆ 1250.0       ┆ 30.0         ┆ 60.0        ┆ 0.0         ┆ 0.0         ┆ 2198.0      │
│ max        ┆ 2208.0       ┆ 73.0         ┆ 259.0       ┆ 2.0         ┆ 2.0         ┆ 2208.0      │
└────────────┴──────────────┴──────────────┴─────────────┴─────────────┴─────────────┴─────────────┘
shape: (1, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ low_pressure_h ┆ wet_windy_hour ┆ cold_windy_hou ┆ hot_humid_hou ┆ storm_event_h ┆ observed_hour │
│ ours           ┆ s              ┆ rs             ┆ rs            ┆ ours          ┆ s             │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ f64            ┆ f64            ┆ f64            ┆ f64           ┆ f64           ┆ f64           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ -0.223884      ┆ 0.169482       ┆ 0.011389       ┆ -0.040847     ┆ -0.0076       ┆ -0.02668      │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

In [52]:
print(df.select(engineered_features_4).describe())

print(
    df.select([
        pl.corr("reliability_index", c).alias(c)
        for c in engineered_features_4
    ])
)

shape: (9, 6)
┌────────────┬────────────────┬────────────────┬─────────────────┬────────────────┬────────────────┐
│ statistic  ┆ expected_hours ┆ coverage_ratio ┆ wind_dir_result ┆ wind_dir_circu ┆ sustained_high │
│ ---        ┆ ---            ┆ ---            ┆ ant_length      ┆ lar_variance   ┆ _wind_periods  │
│ str        ┆ f64            ┆ f64            ┆ ---             ┆ ---            ┆ ---            │
│            ┆                ┆                ┆ f64             ┆ f64            ┆ f64            │
╞════════════╪════════════════╪════════════════╪═════════════════╪════════════════╪════════════════╡
│ count      ┆ 10589.0        ┆ 10589.0        ┆ 10589.0         ┆ 10589.0        ┆ 10589.0        │
│ null_count ┆ 0.0            ┆ 0.0            ┆ 0.0             ┆ 0.0            ┆ 0.0            │
│ mean       ┆ 2160.0         ┆ 0.955126       ┆ 0.260014        ┆ 0.739986       ┆ 0.252148       │
│ std        ┆ 0.0            ┆ 0.138365       ┆ 0.100235        ┆ 0.100235       ┆ 0.646747       │
│ min        ┆ 2160.0         ┆ 0.086111       ┆ 0.009381        ┆ 0.352143       ┆ 0.0            │
│ 25%        ┆ 2160.0         ┆ 1.0            ┆ 0.182023        ┆ 0.678507       ┆ 0.0            │
│ 50%        ┆ 2160.0         ┆ 1.011111       ┆ 0.262982        ┆ 0.737018       ┆ 0.0            │
│ 75%        ┆ 2160.0         ┆ 1.017593       ┆ 0.321493        ┆ 0.817977       ┆ 0.0            │
│ max        ┆ 2160.0         ┆ 1.022222       ┆ 0.647857        ┆ 0.990619       ┆ 11.0           │
└────────────┴────────────────┴────────────────┴─────────────────┴────────────────┴────────────────┘
shape: (1, 5)
┌────────────────┬────────────────┬─────────────────────┬─────────────────────┬────────────────────┐
│ expected_hours ┆ coverage_ratio ┆ wind_dir_resultant_ ┆ wind_dir_circular_v ┆ sustained_high_win │
│ ---            ┆ ---            ┆ length              ┆ ariance             ┆ d_periods          │
│ f64            ┆ f64            ┆ ---                 ┆ ---                 ┆ ---                │
│                ┆                ┆ f64                 ┆ f64                 ┆ f64                │
╞════════════════╪════════════════╪═════════════════════╪═════════════════════╪════════════════════╡
│ NaN            ┆ -0.02668       ┆ -0.034537           ┆ 0.034537            ┆ 0.010874           │
└────────────────┴────────────────┴─────────────────────┴─────────────────────┴────────────────────┘