In [7]:
import os

os.getcwd()

'c:\\Users\\brett\\Projects\\fixed_broadband_tract_reliability_model\\notebooks\\eda'

In [ ]:
import polars as pl

# Configure Polars so Jupyter shows ALL columns and a controlled
# number of rows. This prevents truncation and keeps rendering fast.

pl.Config.set_tbl_cols(-1)   # show all columns, no matter how many
pl.Config.set_tbl_rows(10)   # show only 10 rows in the HTML output

# Load the unified tract-quarter feature dataset
df = pl.read_parquet("../../data/processed/feature_engineering/tract_quarter_features.parquet")

# Display the first 10 rows with all columns visible
df.head(10)

shape: (10, 593)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ tra ┆ yea ┆ qua ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ tem ┆ tem ┆ gus ┆ gus ┆ gus ┆ gus ┆ pre ┆ pre ┆ pre ┆ pre ┆ vis ┆ low ┆ wet ┆ col ┆ hot ┆ sto ┆ obs ┆ exp ┆ cov ┆ win ┆ win ┆ sus ┆ sev ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ lcd ┆ lcd ┆ lcd ┆ rel ┆ pop ┆ pop ┆ pop ┆ mal ┆ mal ┆ mal ┆ mal ┆ mal ┆ mal ┆ fem ┆ fem ┆ fem ┆ fem ┆ fem ┆ fem ┆ mal ┆ fem ┆ med ┆ dis ┆ dis ┆ dis ┆ edu ┆ edu ┆ edu ┆ edu ┆ edu ┆ pov ┆ pov ┆ med ┆ lab ┆ lab ┆ une ┆ hou ┆ hou ┆ hou ┆ med ┆ med ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ lan ┆ lim ┆ lim ┆ lim ┆ no_ ┆ no_ ┆ no_ ┆ veh ┆ veh ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ ele ┆ cen ┆ cen ┆ bbo ┆ bbo ┆ bbo ┆ bbo ┆ tra ┆ tra ┆ tra ┆ pop ┆ pop ┆ dis ┆ edu ┆ lim ┆ no_ ┆ pct ┆ pct ┆ sex ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pop ┆ pop ┆ pop ┆ mal ┆ mal ┆ mal ┆ mal ┆ mal ┆ mal ┆ fem ┆ fem ┆ fem ┆ fem ┆ fem ┆ fem ┆ mal ┆ fem ┆ med ┆ dis ┆ dis ┆ dis ┆ edu ┆ edu ┆ edu ┆ edu ┆ edu ┆ pov ┆ pov ┆ med ┆ lab ┆ lab ┆ une ┆ hou ┆ hou ┆ hou ┆ med ┆ med ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ lan ┆ lim ┆ lim ┆ lim ┆ no_ ┆ no_ ┆ no_ ┆ veh ┆ veh ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ ele ┆ cen ┆ cen ┆ bbo ┆ bbo ┆ bbo ┆ bbo ┆ tra ┆ tra ┆ tra ┆ pop ┆ pop ┆ dis ┆ edu ┆ lim ┆ no_ ┆ pct ┆ pct ┆ sex ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ tra ┆ tra ┆ tra │
│ ct  ┆ r   ┆ rte ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ p_b ┆ p_a ┆ t_g ┆ t_g ┆ t_g ┆ t_g ┆ cip ┆ cip ┆ cip ┆ cip ┆ ibi ┆ _pr ┆ _wi ┆ d_w ┆ _hu ┆ rm_ ┆ erv ┆ ect ┆ era ┆ d_d ┆ d_d ┆ tai ┆ ere ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ v2_ ┆ v2_ ┆ v2_ ┆ iab ┆ ula ┆ ula ┆ ula ┆ e_6 ┆ e_6 ┆ e_7 ┆ e_7 ┆ e_8 ┆ e_8 ┆ ale ┆ ale ┆ ale ┆ ale ┆ ale ┆ ale ┆ e_u ┆ ale ┆ ian ┆ abi ┆ abi ┆ abi ┆ _hi ┆ _ba ┆ _ma ┆ _pr ┆ _do ┆ ert ┆ ert ┆ ian ┆ or_ ┆ or_ ┆ mpl ┆ sin ┆ sin ┆ sin ┆ ian ┆ ian ┆ e_u ┆ e_w ┆ e_b ┆ e_a ┆ e_a ┆ e_p ┆ e_h ┆ e_o ┆ gua ┆ ite ┆ ite ┆ ite ┆ eng ┆ eng ┆ eng ┆ icl ┆ icl ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ vat ┆ tro ┆ tro ┆ x_m ┆ x_m ┆ x_m ┆ x_m ┆ ct_ ┆ ct_ ┆ ct_ ┆ ula ┆ ula ┆ abi ┆ _to ┆ ite ┆ eng ┆ _ma ┆ _fe ┆ _ra ┆ _65 ┆ _un ┆ _di ┆ _hi ┆ _ba ┆ _gr ┆ _po ┆ _un ┆ _ho ┆ _ho ┆ _wh ┆ _bl ┆ _as ┆ _hi ┆ _am ┆ _pa ┆ _ra ┆ _li ┆ _no ┆ _ve ┆ _si ┆ _sm ┆ _la ┆ _mo ┆ ula ┆ ula ┆ ula ┆ e_6 ┆ e_6 ┆ e_7 ┆ e_7 ┆ e_8 ┆ e_8 ┆ ale ┆ ale ┆ ale ┆ ale ┆ ale ┆ ale ┆ e_u ┆ ale ┆ ian ┆ abi ┆ abi ┆ abi ┆ _hi ┆ _ba ┆ _ma ┆ _pr ┆ _do ┆ ert ┆ ert ┆ ian ┆ or_ ┆ or_ ┆ mpl ┆ sin ┆ sin ┆ sin ┆ ian ┆ ian ┆ e_u ┆ e_w ┆ e_b ┆ e_a ┆ e_a ┆ e_p ┆ e_h ┆ e_o ┆ gua ┆ ite ┆ ite ┆ ite ┆ eng ┆ eng ┆ eng ┆ icl ┆ icl ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ vat ┆ tro ┆ tro ┆ x_m ┆ x_m ┆ x_m ┆ x_m ┆ ct_ ┆ ct_ ┆ ct_ ┆ ula ┆ ula ┆ abi ┆ _to ┆ ite ┆ eng ┆ _ma ┆ _fe ┆ _ra ┆ _65 ┆ _un ┆ _di ┆ _hi ┆ _ba ┆ _gr ┆ _po ┆ _un ┆ _ho ┆ _ho ┆ _wh ┆ _bl ┆ _as ┆ _hi ┆ _am ┆ _pa ┆ _ra ┆ _li ┆ _no ┆ _ve ┆ _si ┆ _sm ┆ _la ┆ _mo ┆ ct_ ┆ ct_ ┆ ct_ │
│ --- ┆ --- ┆ r   ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ elo ┆ bov ┆ t_2 ┆ t_3 ┆ t_4 ┆ t_5 ┆ _gt ┆ _gt ┆ _gt ┆ _gt ┆ lit ┆ ess ┆ ndy ┆ ind ┆ mid ┆ eve ┆ ed_ ┆ ed_ ┆ ge_ ┆ ir_ ┆ ir_ ┆ ned ┆ _we ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ num ┆ is_ ┆ san ┆ ili ┆ tio ┆ tio ┆ tio ┆ 5_6 ┆ 7_6 ┆ 0_7 ┆ 5_7 ┆ 0_8 ┆ 5_p ┆ _65 ┆ _67 ┆ _70 ┆ _75 ┆ _80 ┆ _85 ┆ nde ┆ _un ┆ _ag ┆ lit ┆ lit ┆ lit ┆ gh_ ┆ che ┆ ste ┆ ofe ┆ cto ┆ y_u ┆ y_b ┆ _ho ┆ for ┆ for ┆ oym ┆ g_u ┆ g_o ┆ g_v ┆ _ho ┆ _gr ┆ niv ┆ hit ┆ lac ┆ mer ┆ sia ┆ aci ┆ isp ┆ the ┆ ge_ ┆ d_e ┆ d_e ┆ d_e ┆ lis ┆ lis ┆ lis ┆ e_u ┆ e_n ┆ g_s ┆ g_1 ┆ g_2 ┆ g_3 ┆ g_5 ┆ g_1 ┆ g_2 ┆ g_5 ┆ g_m ┆ ion ┆ id_ ┆ id_ ┆ inx ┆ iny ┆ axx ┆ axy ┆ are ┆ per ┆ com ┆ tio ┆ tio ┆ lit ┆ tal ┆ d_e ┆ lis ┆ le  ┆ mal ┆ tio ┆ _pl ┆ der ┆ sab ┆ gh_ ┆ che ┆ ad_ ┆ ver ┆ emp ┆ usi ┆ usi ┆ ite ┆ ack ┆ ian ┆ spa ┆ eri ┆ cif ┆ ce_ ┆ mit ┆ _en ┆ hic ┆ ngl ┆ all ┆ rge ┆ bil ┆ tio ┆ tio ┆ tio ┆ 5_6 ┆ 7_6 ┆ 0_7 ┆ 5_7 ┆ 0_8 ┆ 5_p ┆ _65 ┆ _67 ┆ _70 ┆ _75 ┆ _80 ┆ _85 ┆ nde ┆ _un ┆ _ag ┆ lit ┆ lit ┆ lit ┆ gh_ ┆ che ┆ ste ┆ ofe ┆ cto ┆ y_u ┆ y_b ┆ _ho ┆ for ┆ for ┆ oym ┆ g_u ┆ g_o ┆ g_v ┆ _ho ┆ _gr ┆ niv ┆ hit ┆ lac ┆ mer ┆ sia ┆ aci ┆ isp ┆ the ┆ ge_ ┆ d_e ┆ d_e ┆ d_e ┆ lis ┆ lis ┆ lis ┆ e_u ┆ e_n ┆ g_s ┆ g_1 ┆ g_2 ┆ g_3 ┆ g_5 ┆ g_1 ┆ g_2 ┆ g_5 ┆ g_m ┆ ion ┆ id_ ┆ id_ ┆ inx ┆ iny ┆ axx ┆ axy ┆ are ┆ per ┆ com ┆ tio ┆ tio ┆ lit ┆ tal ┆ d_e ┆ lis ┆ le_ ┆ mal ┆ tio ┆ _pl ┆ der ┆ sab ┆ gh_ ┆ che ┆ ad_ ┆ ver ┆ emp ┆ usi ┆ usi ┆ ite ┆ ack ┆ ian ┆ spa ┆ eri ┆ cif ┆ ce_ ┆ mit ┆ _en ┆ hic ┆ ngl ┆ all ┆ rge ┆ bil ┆ num ┆ is_ ┆ san │
│ str ┆ i32 ┆ --- ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ w_f ┆ e_9 ┆ 0_h ┆ 0_h ┆ 0_h ┆ 0_h ┆ _0_ ┆ _0_ ┆ _0_ ┆ _0_ ┆ y_l ┆ ure ┆ _ho ┆ y_h ┆ _ho ┆ nt_ ┆ hou ┆ hou ┆ rat ┆ res ┆ cir ┆ _hi ┆ ath ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ _sa ┆ san ┆ iti ┆ ty_ ┆ n_t ┆ n_m ┆ n_f ┆ 6   ┆ 9   ┆ 4   ┆ 9   ┆ 4   ┆ lus ┆ _66 ┆ _69 ┆ _74 ┆ _79 ┆ _84 ┆ _pl ┆ r_5 ┆ der ┆ e   ┆ y_u ┆ y_1 ┆ y_6 ┆ sch ┆ lor ┆ rs  ┆ ssi ┆ rat ┆ niv ┆ elo ┆ use ┆ ce  ┆ ce_ ┆ ent ┆ nit ┆ ccu ┆ aca ┆ me_ ┆ oss ┆ ers ┆ e   ┆ k   ┆ ica ┆ n   ┆ fic ┆ ani ┆ r   ┆ uni ┆ ngl ┆ ngl ┆ ngl ┆ h_5 ┆ h_1 ┆ h_6 ┆ niv ┆ one ┆ tru ┆ _un ┆ _un ┆ _4_ ┆ _9_ ┆ 0_1 ┆ 0_4 ┆ 0_p ┆ obi ┆ _m  ┆ lat ┆ lon ┆ --- ┆ --- ┆ --- ┆ --- ┆ a   ┆ ime ┆ pac ┆ n_6 ┆ n_u ┆ y_t ┆ --- ┆ ngl ┆ h_t ┆ --- ┆ e   ┆ --- ┆ us  ┆ _5  ┆ ili ┆ sch ┆ lor ┆ deg ┆ ty  ┆ loy ┆ ng_ ┆ ng_ ┆ --- ┆ --- ┆ --- ┆ nic ┆ can ┆ ic_ ┆ oth ┆ ed_ ┆ gli ┆ le_ ┆ e_f ┆ _mu ┆ _mu ┆ e_h ┆ n_t ┆ n_m ┆ n_f ┆ 6_w ┆ 9_w ┆ 4_w ┆ 9_w ┆ 4_w ┆ lus ┆ _66 ┆ _69 ┆ _74 ┆ _79 ┆ _84 ┆ _pl ┆ r_5 ┆ der ┆ e_w ┆ y_u ┆ y_1 ┆ y_6 ┆ sch ┆ lor ┆ rs_ ┆ ssi ┆ rat ┆ niv ┆ elo ┆ use ┆ ce_ ┆ ce_ ┆ ent ┆ nit ┆ ccu ┆ aca ┆ me_ ┆ oss ┆ ers ┆ e_w ┆ k_w ┆ ica ┆ n_w ┆ fic ┆ ani ┆ r_w ┆ uni ┆ ngl ┆ ngl ┆ ngl ┆ h_5 ┆ h_1 ┆ h_6 ┆ niv ┆ one ┆ tru ┆ _un ┆ _un ┆ _4_ ┆ _9_ ┆ 0_1 ┆ 0_4 ┆ 0_p ┆ obi ┆ _m_ ┆ lat ┆ lon ┆ _wa ┆ _wa ┆ _wa ┆ _wa ┆ a_w ┆ ime ┆ pac ┆ n_6 ┆ n_u ┆ y_t ┆ _wa ┆ ngl ┆ h_t ┆ was ┆ e_w ┆ _wa ┆ us_ ┆ _5_ ┆ ili ┆ sch ┆ lor ┆ deg ┆ ty_ ┆ loy ┆ ng_ ┆ ng_ ┆ _wa ┆ _wa ┆ _wa ┆ nic ┆ can ┆ ic_ ┆ oth ┆ ed_ ┆ gli ┆ le_ ┆ e_f ┆ _mu ┆ _mu ┆ e_h ┆ _sa ┆ san ┆ iti │

In [6]:
print(df.shape)

(10794, 593)

In [8]:
# Are any features missing or degenerate?
missing = df.null_count()
missing

shape: (1, 593)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ tra ┆ yea ┆ qua ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ tem ┆ tem ┆ gus ┆ gus ┆ gus ┆ gus ┆ pre ┆ pre ┆ pre ┆ pre ┆ vis ┆ low ┆ wet ┆ col ┆ hot ┆ sto ┆ obs ┆ exp ┆ cov ┆ win ┆ win ┆ sus ┆ sev ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ lcd ┆ lcd ┆ lcd ┆ rel ┆ pop ┆ pop ┆ pop ┆ mal ┆ mal ┆ mal ┆ mal ┆ mal ┆ mal ┆ fem ┆ fem ┆ fem ┆ fem ┆ fem ┆ fem ┆ mal ┆ fem ┆ med ┆ dis ┆ dis ┆ dis ┆ edu ┆ edu ┆ edu ┆ edu ┆ edu ┆ pov ┆ pov ┆ med ┆ lab ┆ lab ┆ une ┆ hou ┆ hou ┆ hou ┆ med ┆ med ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ lan ┆ lim ┆ lim ┆ lim ┆ no_ ┆ no_ ┆ no_ ┆ veh ┆ veh ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ ele ┆ cen ┆ cen ┆ bbo ┆ bbo ┆ bbo ┆ bbo ┆ tra ┆ tra ┆ tra ┆ pop ┆ pop ┆ dis ┆ edu ┆ lim ┆ no_ ┆ pct ┆ pct ┆ sex ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pop ┆ pop ┆ pop ┆ mal ┆ mal ┆ mal ┆ mal ┆ mal ┆ mal ┆ fem ┆ fem ┆ fem ┆ fem ┆ fem ┆ fem ┆ mal ┆ fem ┆ med ┆ dis ┆ dis ┆ dis ┆ edu ┆ edu ┆ edu ┆ edu ┆ edu ┆ pov ┆ pov ┆ med ┆ lab ┆ lab ┆ une ┆ hou ┆ hou ┆ hou ┆ med ┆ med ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ lan ┆ lim ┆ lim ┆ lim ┆ no_ ┆ no_ ┆ no_ ┆ veh ┆ veh ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ ele ┆ cen ┆ cen ┆ bbo ┆ bbo ┆ bbo ┆ bbo ┆ tra ┆ tra ┆ tra ┆ pop ┆ pop ┆ dis ┆ edu ┆ lim ┆ no_ ┆ pct ┆ pct ┆ sex ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ tra ┆ tra ┆ tra │
│ ct  ┆ r   ┆ rte ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ p_b ┆ p_a ┆ t_g ┆ t_g ┆ t_g ┆ t_g ┆ cip ┆ cip ┆ cip ┆ cip ┆ ibi ┆ _pr ┆ _wi ┆ d_w ┆ _hu ┆ rm_ ┆ erv ┆ ect ┆ era ┆ d_d ┆ d_d ┆ tai ┆ ere ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ v2_ ┆ v2_ ┆ v2_ ┆ iab ┆ ula ┆ ula ┆ ula ┆ e_6 ┆ e_6 ┆ e_7 ┆ e_7 ┆ e_8 ┆ e_8 ┆ ale ┆ ale ┆ ale ┆ ale ┆ ale ┆ ale ┆ e_u ┆ ale ┆ ian ┆ abi ┆ abi ┆ abi ┆ _hi ┆ _ba ┆ _ma ┆ _pr ┆ _do ┆ ert ┆ ert ┆ ian ┆ or_ ┆ or_ ┆ mpl ┆ sin ┆ sin ┆ sin ┆ ian ┆ ian ┆ e_u ┆ e_w ┆ e_b ┆ e_a ┆ e_a ┆ e_p ┆ e_h ┆ e_o ┆ gua ┆ ite ┆ ite ┆ ite ┆ eng ┆ eng ┆ eng ┆ icl ┆ icl ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ vat ┆ tro ┆ tro ┆ x_m ┆ x_m ┆ x_m ┆ x_m ┆ ct_ ┆ ct_ ┆ ct_ ┆ ula ┆ ula ┆ abi ┆ _to ┆ ite ┆ eng ┆ _ma ┆ _fe ┆ _ra ┆ _65 ┆ _un ┆ _di ┆ _hi ┆ _ba ┆ _gr ┆ _po ┆ _un ┆ _ho ┆ _ho ┆ _wh ┆ _bl ┆ _as ┆ _hi ┆ _am ┆ _pa ┆ _ra ┆ _li ┆ _no ┆ _ve ┆ _si ┆ _sm ┆ _la ┆ _mo ┆ ula ┆ ula ┆ ula ┆ e_6 ┆ e_6 ┆ e_7 ┆ e_7 ┆ e_8 ┆ e_8 ┆ ale ┆ ale ┆ ale ┆ ale ┆ ale ┆ ale ┆ e_u ┆ ale ┆ ian ┆ abi ┆ abi ┆ abi ┆ _hi ┆ _ba ┆ _ma ┆ _pr ┆ _do ┆ ert ┆ ert ┆ ian ┆ or_ ┆ or_ ┆ mpl ┆ sin ┆ sin ┆ sin ┆ ian ┆ ian ┆ e_u ┆ e_w ┆ e_b ┆ e_a ┆ e_a ┆ e_p ┆ e_h ┆ e_o ┆ gua ┆ ite ┆ ite ┆ ite ┆ eng ┆ eng ┆ eng ┆ icl ┆ icl ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ vat ┆ tro ┆ tro ┆ x_m ┆ x_m ┆ x_m ┆ x_m ┆ ct_ ┆ ct_ ┆ ct_ ┆ ula ┆ ula ┆ abi ┆ _to ┆ ite ┆ eng ┆ _ma ┆ _fe ┆ _ra ┆ _65 ┆ _un ┆ _di ┆ _hi ┆ _ba ┆ _gr ┆ _po ┆ _un ┆ _ho ┆ _ho ┆ _wh ┆ _bl ┆ _as ┆ _hi ┆ _am ┆ _pa ┆ _ra ┆ _li ┆ _no ┆ _ve ┆ _si ┆ _sm ┆ _la ┆ _mo ┆ ct_ ┆ ct_ ┆ ct_ │
│ --- ┆ --- ┆ r   ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ elo ┆ bov ┆ t_2 ┆ t_3 ┆ t_4 ┆ t_5 ┆ _gt ┆ _gt ┆ _gt ┆ _gt ┆ lit ┆ ess ┆ ndy ┆ ind ┆ mid ┆ eve ┆ ed_ ┆ ed_ ┆ ge_ ┆ ir_ ┆ ir_ ┆ ned ┆ _we ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ num ┆ is_ ┆ san ┆ ili ┆ tio ┆ tio ┆ tio ┆ 5_6 ┆ 7_6 ┆ 0_7 ┆ 5_7 ┆ 0_8 ┆ 5_p ┆ _65 ┆ _67 ┆ _70 ┆ _75 ┆ _80 ┆ _85 ┆ nde ┆ _un ┆ _ag ┆ lit ┆ lit ┆ lit ┆ gh_ ┆ che ┆ ste ┆ ofe ┆ cto ┆ y_u ┆ y_b ┆ _ho ┆ for ┆ for ┆ oym ┆ g_u ┆ g_o ┆ g_v ┆ _ho ┆ _gr ┆ niv ┆ hit ┆ lac ┆ mer ┆ sia ┆ aci ┆ isp ┆ the ┆ ge_ ┆ d_e ┆ d_e ┆ d_e ┆ lis ┆ lis ┆ lis ┆ e_u ┆ e_n ┆ g_s ┆ g_1 ┆ g_2 ┆ g_3 ┆ g_5 ┆ g_1 ┆ g_2 ┆ g_5 ┆ g_m ┆ ion ┆ id_ ┆ id_ ┆ inx ┆ iny ┆ axx ┆ axy ┆ are ┆ per ┆ com ┆ tio ┆ tio ┆ lit ┆ tal ┆ d_e ┆ lis ┆ le  ┆ mal ┆ tio ┆ _pl ┆ der ┆ sab ┆ gh_ ┆ che ┆ ad_ ┆ ver ┆ emp ┆ usi ┆ usi ┆ ite ┆ ack ┆ ian ┆ spa ┆ eri ┆ cif ┆ ce_ ┆ mit ┆ _en ┆ hic ┆ ngl ┆ all ┆ rge ┆ bil ┆ tio ┆ tio ┆ tio ┆ 5_6 ┆ 7_6 ┆ 0_7 ┆ 5_7 ┆ 0_8 ┆ 5_p ┆ _65 ┆ _67 ┆ _70 ┆ _75 ┆ _80 ┆ _85 ┆ nde ┆ _un ┆ _ag ┆ lit ┆ lit ┆ lit ┆ gh_ ┆ che ┆ ste ┆ ofe ┆ cto ┆ y_u ┆ y_b ┆ _ho ┆ for ┆ for ┆ oym ┆ g_u ┆ g_o ┆ g_v ┆ _ho ┆ _gr ┆ niv ┆ hit ┆ lac ┆ mer ┆ sia ┆ aci ┆ isp ┆ the ┆ ge_ ┆ d_e ┆ d_e ┆ d_e ┆ lis ┆ lis ┆ lis ┆ e_u ┆ e_n ┆ g_s ┆ g_1 ┆ g_2 ┆ g_3 ┆ g_5 ┆ g_1 ┆ g_2 ┆ g_5 ┆ g_m ┆ ion ┆ id_ ┆ id_ ┆ inx ┆ iny ┆ axx ┆ axy ┆ are ┆ per ┆ com ┆ tio ┆ tio ┆ lit ┆ tal ┆ d_e ┆ lis ┆ le_ ┆ mal ┆ tio ┆ _pl ┆ der ┆ sab ┆ gh_ ┆ che ┆ ad_ ┆ ver ┆ emp ┆ usi ┆ usi ┆ ite ┆ ack ┆ ian ┆ spa ┆ eri ┆ cif ┆ ce_ ┆ mit ┆ _en ┆ hic ┆ ngl ┆ all ┆ rge ┆ bil ┆ num ┆ is_ ┆ san │
│ u32 ┆ u32 ┆ --- ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ w_f ┆ e_9 ┆ 0_h ┆ 0_h ┆ 0_h ┆ 0_h ┆ _0_ ┆ _0_ ┆ _0_ ┆ _0_ ┆ y_l ┆ ure ┆ _ho ┆ y_h ┆ _ho ┆ nt_ ┆ hou ┆ hou ┆ rat ┆ res ┆ cir ┆ _hi ┆ ath ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ _sa ┆ san ┆ iti ┆ ty_ ┆ n_t ┆ n_m ┆ n_f ┆ 6   ┆ 9   ┆ 4   ┆ 9   ┆ 4   ┆ lus ┆ _66 ┆ _69 ┆ _74 ┆ _79 ┆ _84 ┆ _pl ┆ r_5 ┆ der ┆ e   ┆ y_u ┆ y_1 ┆ y_6 ┆ sch ┆ lor ┆ rs  ┆ ssi ┆ rat ┆ niv ┆ elo ┆ use ┆ ce  ┆ ce_ ┆ ent ┆ nit ┆ ccu ┆ aca ┆ me_ ┆ oss ┆ ers ┆ e   ┆ k   ┆ ica ┆ n   ┆ fic ┆ ani ┆ r   ┆ uni ┆ ngl ┆ ngl ┆ ngl ┆ h_5 ┆ h_1 ┆ h_6 ┆ niv ┆ one ┆ tru ┆ _un ┆ _un ┆ _4_ ┆ _9_ ┆ 0_1 ┆ 0_4 ┆ 0_p ┆ obi ┆ _m  ┆ lat ┆ lon ┆ --- ┆ --- ┆ --- ┆ --- ┆ a   ┆ ime ┆ pac ┆ n_6 ┆ n_u ┆ y_t ┆ --- ┆ ngl ┆ h_t ┆ --- ┆ e   ┆ --- ┆ us  ┆ _5  ┆ ili ┆ sch ┆ lor ┆ deg ┆ ty  ┆ loy ┆ ng_ ┆ ng_ ┆ --- ┆ --- ┆ --- ┆ nic ┆ can ┆ ic_ ┆ oth ┆ ed_ ┆ gli ┆ le_ ┆ e_f ┆ _mu ┆ _mu ┆ e_h ┆ n_t ┆ n_m ┆ n_f ┆ 6_w ┆ 9_w ┆ 4_w ┆ 9_w ┆ 4_w ┆ lus ┆ _66 ┆ _69 ┆ _74 ┆ _79 ┆ _84 ┆ _pl ┆ r_5 ┆ der ┆ e_w ┆ y_u ┆ y_1 ┆ y_6 ┆ sch ┆ lor ┆ rs_ ┆ ssi ┆ rat ┆ niv ┆ elo ┆ use ┆ ce_ ┆ ce_ ┆ ent ┆ nit ┆ ccu ┆ aca ┆ me_ ┆ oss ┆ ers ┆ e_w ┆ k_w ┆ ica ┆ n_w ┆ fic ┆ ani ┆ r_w ┆ uni ┆ ngl ┆ ngl ┆ ngl ┆ h_5 ┆ h_1 ┆ h_6 ┆ niv ┆ one ┆ tru ┆ _un ┆ _un ┆ _4_ ┆ _9_ ┆ 0_1 ┆ 0_4 ┆ 0_p ┆ obi ┆ _m_ ┆ lat ┆ lon ┆ _wa ┆ _wa ┆ _wa ┆ _wa ┆ a_w ┆ ime ┆ pac ┆ n_6 ┆ n_u ┆ y_t ┆ _wa ┆ ngl ┆ h_t ┆ was ┆ e_w ┆ _wa ┆ us_ ┆ _5_ ┆ ili ┆ sch ┆ lor ┆ deg ┆ ty_ ┆ loy ┆ ng_ ┆ ng_ ┆ _wa ┆ _wa ┆ _wa ┆ nic ┆ can ┆ ic_ ┆ oth ┆ ed_ ┆ gli ┆ le_ ┆ e_f ┆ _mu ┆ _mu ┆ e_h ┆ _sa ┆ san ┆ iti │

12-14 records contain null summary stats for weighted_precipitation, 144 records have null target value (reliability_index).

In [28]:
# check for data clearning that occured during prior data normalization, may have modeling implications
san_cols = [c for c in df.columns if "sanitization" in c]
df.filter((pl.col('lcdv2_sanitization_level') != 'none') | (pl.col('tract_sanitization_level') != 'none')).select(san_cols)

shape: (14, 2)
┌──────────────────────────┬──────────────────────────┐
│ lcdv2_sanitization_level ┆ tract_sanitization_level │
│ ---                      ┆ ---                      │
│ str                      ┆ str                      │
╞══════════════════════════╪══════════════════════════╡
│ moderate                 ┆ none                     │
│ moderate                 ┆ none                     │
│ moderate                 ┆ none                     │
│ moderate                 ┆ none                     │
│ moderate                 ┆ none                     │
│ …                        ┆ …                        │
│ partial                  ┆ none                     │
│ moderate                 ┆ none                     │
│ moderate                 ┆ none                     │
│ moderate                 ┆ none                     │
│ moderate                 ┆ none                     │
└──────────────────────────┴──────────────────────────┘

In [27]:
precip_summary_cols = [
    "weighted_precipitation_mean",
    "weighted_precipitation_median",
    "weighted_precipitation_max",
    "weighted_precipitation_min",
    "weighted_precipitation_range",
    "weighted_precipitation_p10",
    "weighted_precipitation_p25",
    "weighted_precipitation_p75",
    "weighted_precipitation_p90",
    "weighted_precipitation_std",
    "weighted_precipitation_cv",
]

missing_precip = df.filter(
    pl.any_horizontal([pl.col(c).is_null() for c in precip_summary_cols])
).select(["tract", "year", "quarter", "lcdv2_sanitization_level"] + precip_summary_cols)

missing_precip

shape: (14, 15)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┬───────┬───────┬───────┐
│ tra ┆ yea ┆ qua ┆ lcd ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ weight ┆ weigh ┆ weigh ┆ weigh │
│ ct  ┆ r   ┆ rte ┆ v2_ ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ed_pre ┆ ted_p ┆ ted_p ┆ ted_p │
│ --- ┆ --- ┆ r   ┆ san ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ cipita ┆ recip ┆ recip ┆ recip │
│ str ┆ i32 ┆ --- ┆ iti ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ tion_p ┆ itati ┆ itati ┆ itati │
│     ┆     ┆ str ┆ zat ┆ cip ┆ cip ┆ cip ┆ cip ┆ cip ┆ cip ┆ cip ┆ 75     ┆ on_p9 ┆ on_st ┆ on_cv │
│     ┆     ┆     ┆ ion ┆ ita ┆ ita ┆ ita ┆ ita ┆ ita ┆ ita ┆ ita ┆ ---    ┆ 0     ┆ d     ┆ ---   │
│     ┆     ┆     ┆ _le ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ f64    ┆ ---   ┆ ---   ┆ f64   │
│     ┆     ┆     ┆ vel ┆ n_m ┆ n_m ┆ n_m ┆ n_m ┆ n_r ┆ n_p ┆ n_p ┆        ┆ f64   ┆ f64   ┆       │
│     ┆     ┆     ┆ --- ┆ ean ┆ edi ┆ ax  ┆ in  ┆ ang ┆ 10  ┆ 25  ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆ str ┆ --- ┆ an  ┆ --- ┆ --- ┆ e   ┆ --- ┆ --- ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ f64 ┆ f64 ┆ --- ┆ f64 ┆ f64 ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆ f64 ┆     ┆     ┆        ┆       ┆       ┆       │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╪═══════╪═══════╪═══════╡
│ 550 ┆ 202 ┆ Q4  ┆ mod ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ null   ┆ null  ┆ null  ┆ null  │
│ 371 ┆ 4   ┆     ┆ era ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆        ┆       ┆       ┆       │
│ 902 ┆     ┆     ┆ te  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 550 ┆ 202 ┆ Q1  ┆ mod ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ null   ┆ null  ┆ null  ┆ null  │
│ 371 ┆ 5   ┆     ┆ era ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆        ┆       ┆       ┆       │
│ 902 ┆     ┆     ┆ te  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 550 ┆ 202 ┆ Q4  ┆ mod ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ null   ┆ null  ┆ null  ┆ null  │
│ 371 ┆ 4   ┆     ┆ era ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆        ┆       ┆       ┆       │
│ 901 ┆     ┆     ┆ te  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 02  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 550 ┆ 202 ┆ Q4  ┆ mod ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ null   ┆ null  ┆ null  ┆ null  │
│ 371 ┆ 4   ┆     ┆ era ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆        ┆       ┆       ┆       │
│ 901 ┆     ┆     ┆ te  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 01  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 550 ┆ 202 ┆ Q2  ┆ mod ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ null   ┆ null  ┆ null  ┆ null  │
│ 371 ┆ 5   ┆     ┆ era ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆        ┆       ┆       ┆       │
│ 901 ┆     ┆     ┆ te  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 02  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …      ┆ …     ┆ …     ┆ …     │
│ 550 ┆ 202 ┆ Q1  ┆ par ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.01   ┆ 0.01  ┆ null  ┆ null  │
│ 119 ┆ 4   ┆     ┆ tia ┆ 1   ┆ 1   ┆ 1   ┆ 1   ┆     ┆ 1   ┆ 1   ┆        ┆       ┆       ┆       │
│ 604 ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 550 ┆ 202 ┆ Q3  ┆ mod ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ null   ┆ null  ┆ null  ┆ null  │
│ 371 ┆ 5   ┆     ┆ era ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆        ┆       ┆       ┆       │
│ 901 ┆     ┆     ┆ te  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 01  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 550 ┆ 202 ┆ Q3  ┆ mod ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ null   ┆ null  ┆ null  ┆ null  │
│ 371 ┆ 5   ┆     ┆ era ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆        ┆       ┆       ┆       │
│ 902 ┆     ┆     ┆ te  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 550 ┆ 202 ┆ Q2  ┆ mod ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ null   ┆ null  ┆ null  ┆ null  │
│ 371 ┆ 5   ┆     ┆ era ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆        ┆       ┆       ┆       │
│ 901 ┆     ┆     ┆ te  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 01  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 550 ┆ 202 ┆ Q3  ┆ mod ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ null   ┆ null  ┆ null  ┆ null  │
│ 371 ┆ 5   ┆     ┆ era ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆        ┆       ┆       ┆       │
│ 901 ┆     ┆     ┆ te  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 02  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴────────┴───────┴───────┴───────┘

The null values are the result of tracts having stations that never report precipitation. Null precipitation values were converted to a value of 0 and with all 0 values the summary of such inputs results in null summary stat values. No remediation needed for modeling later.

In [24]:
missing_target = df.filter(pl.col("reliability_index").is_null())
missing_target.select(["tract", "year", "quarter"]).head(20)
missing_target.shape

(144, 593)

In [25]:
san_cols = [c for c in df.columns if "sanitization" in c]

missing_target.select(["tract", "year", "quarter"] + san_cols).head(20)

shape: (20, 5)
┌─────────────┬──────┬─────────┬──────────────────────────┬──────────────────────────┐
│ tract       ┆ year ┆ quarter ┆ lcdv2_sanitization_level ┆ tract_sanitization_level │
│ ---         ┆ ---  ┆ ---     ┆ ---                      ┆ ---                      │
│ str         ┆ i32  ┆ str     ┆ str                      ┆ str                      │
╞═════════════╪══════╪═════════╪══════════════════════════╪══════════════════════════╡
│ 55075990000 ┆ 2025 ┆ Q1      ┆ none                     ┆ none                     │
│ 55061990000 ┆ 2024 ┆ Q2      ┆ none                     ┆ none                     │
│ 55003990000 ┆ 2025 ┆ Q3      ┆ none                     ┆ none                     │
│ 55079014300 ┆ 2024 ┆ Q4      ┆ none                     ┆ none                     │
│ 55009980000 ┆ 2024 ┆ Q2      ┆ none                     ┆ none                     │
│ …           ┆ …    ┆ …       ┆ …                        ┆ …                        │
│ 55101990000 ┆ 2025 ┆ Q1      ┆ none                     ┆ none                     │
│ 55079006700 ┆ 2025 ┆ Q3      ┆ none                     ┆ none                     │
│ 55009980000 ┆ 2024 ┆ Q3      ┆ none                     ┆ none                     │
│ 55079008900 ┆ 2024 ┆ Q2      ┆ none                     ┆ none                     │
│ 55079010600 ┆ 2025 ┆ Q3      ┆ none                     ┆ none                     │
└─────────────┴──────┴─────────┴──────────────────────────┴──────────────────────────┘

In [26]:
missing_target.head(10)

shape: (10, 593)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ tra ┆ yea ┆ qua ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ tem ┆ tem ┆ gus ┆ gus ┆ gus ┆ gus ┆ pre ┆ pre ┆ pre ┆ pre ┆ vis ┆ low ┆ wet ┆ col ┆ hot ┆ sto ┆ obs ┆ exp ┆ cov ┆ win ┆ win ┆ sus ┆ sev ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ lcd ┆ lcd ┆ lcd ┆ rel ┆ pop ┆ pop ┆ pop ┆ mal ┆ mal ┆ mal ┆ mal ┆ mal ┆ mal ┆ fem ┆ fem ┆ fem ┆ fem ┆ fem ┆ fem ┆ mal ┆ fem ┆ med ┆ dis ┆ dis ┆ dis ┆ edu ┆ edu ┆ edu ┆ edu ┆ edu ┆ pov ┆ pov ┆ med ┆ lab ┆ lab ┆ une ┆ hou ┆ hou ┆ hou ┆ med ┆ med ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ lan ┆ lim ┆ lim ┆ lim ┆ no_ ┆ no_ ┆ no_ ┆ veh ┆ veh ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ ele ┆ cen ┆ cen ┆ bbo ┆ bbo ┆ bbo ┆ bbo ┆ tra ┆ tra ┆ tra ┆ pop ┆ pop ┆ dis ┆ edu ┆ lim ┆ no_ ┆ pct ┆ pct ┆ sex ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pop ┆ pop ┆ pop ┆ mal ┆ mal ┆ mal ┆ mal ┆ mal ┆ mal ┆ fem ┆ fem ┆ fem ┆ fem ┆ fem ┆ fem ┆ mal ┆ fem ┆ med ┆ dis ┆ dis ┆ dis ┆ edu ┆ edu ┆ edu ┆ edu ┆ edu ┆ pov ┆ pov ┆ med ┆ lab ┆ lab ┆ une ┆ hou ┆ hou ┆ hou ┆ med ┆ med ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ lan ┆ lim ┆ lim ┆ lim ┆ no_ ┆ no_ ┆ no_ ┆ veh ┆ veh ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ ele ┆ cen ┆ cen ┆ bbo ┆ bbo ┆ bbo ┆ bbo ┆ tra ┆ tra ┆ tra ┆ pop ┆ pop ┆ dis ┆ edu ┆ lim ┆ no_ ┆ pct ┆ pct ┆ sex ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ tra ┆ tra ┆ tra │
│ ct  ┆ r   ┆ rte ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ p_b ┆ p_a ┆ t_g ┆ t_g ┆ t_g ┆ t_g ┆ cip ┆ cip ┆ cip ┆ cip ┆ ibi ┆ _pr ┆ _wi ┆ d_w ┆ _hu ┆ rm_ ┆ erv ┆ ect ┆ era ┆ d_d ┆ d_d ┆ tai ┆ ere ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ v2_ ┆ v2_ ┆ v2_ ┆ iab ┆ ula ┆ ula ┆ ula ┆ e_6 ┆ e_6 ┆ e_7 ┆ e_7 ┆ e_8 ┆ e_8 ┆ ale ┆ ale ┆ ale ┆ ale ┆ ale ┆ ale ┆ e_u ┆ ale ┆ ian ┆ abi ┆ abi ┆ abi ┆ _hi ┆ _ba ┆ _ma ┆ _pr ┆ _do ┆ ert ┆ ert ┆ ian ┆ or_ ┆ or_ ┆ mpl ┆ sin ┆ sin ┆ sin ┆ ian ┆ ian ┆ e_u ┆ e_w ┆ e_b ┆ e_a ┆ e_a ┆ e_p ┆ e_h ┆ e_o ┆ gua ┆ ite ┆ ite ┆ ite ┆ eng ┆ eng ┆ eng ┆ icl ┆ icl ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ vat ┆ tro ┆ tro ┆ x_m ┆ x_m ┆ x_m ┆ x_m ┆ ct_ ┆ ct_ ┆ ct_ ┆ ula ┆ ula ┆ abi ┆ _to ┆ ite ┆ eng ┆ _ma ┆ _fe ┆ _ra ┆ _65 ┆ _un ┆ _di ┆ _hi ┆ _ba ┆ _gr ┆ _po ┆ _un ┆ _ho ┆ _ho ┆ _wh ┆ _bl ┆ _as ┆ _hi ┆ _am ┆ _pa ┆ _ra ┆ _li ┆ _no ┆ _ve ┆ _si ┆ _sm ┆ _la ┆ _mo ┆ ula ┆ ula ┆ ula ┆ e_6 ┆ e_6 ┆ e_7 ┆ e_7 ┆ e_8 ┆ e_8 ┆ ale ┆ ale ┆ ale ┆ ale ┆ ale ┆ ale ┆ e_u ┆ ale ┆ ian ┆ abi ┆ abi ┆ abi ┆ _hi ┆ _ba ┆ _ma ┆ _pr ┆ _do ┆ ert ┆ ert ┆ ian ┆ or_ ┆ or_ ┆ mpl ┆ sin ┆ sin ┆ sin ┆ ian ┆ ian ┆ e_u ┆ e_w ┆ e_b ┆ e_a ┆ e_a ┆ e_p ┆ e_h ┆ e_o ┆ gua ┆ ite ┆ ite ┆ ite ┆ eng ┆ eng ┆ eng ┆ icl ┆ icl ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ vat ┆ tro ┆ tro ┆ x_m ┆ x_m ┆ x_m ┆ x_m ┆ ct_ ┆ ct_ ┆ ct_ ┆ ula ┆ ula ┆ abi ┆ _to ┆ ite ┆ eng ┆ _ma ┆ _fe ┆ _ra ┆ _65 ┆ _un ┆ _di ┆ _hi ┆ _ba ┆ _gr ┆ _po ┆ _un ┆ _ho ┆ _ho ┆ _wh ┆ _bl ┆ _as ┆ _hi ┆ _am ┆ _pa ┆ _ra ┆ _li ┆ _no ┆ _ve ┆ _si ┆ _sm ┆ _la ┆ _mo ┆ ct_ ┆ ct_ ┆ ct_ │
│ --- ┆ --- ┆ r   ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ elo ┆ bov ┆ t_2 ┆ t_3 ┆ t_4 ┆ t_5 ┆ _gt ┆ _gt ┆ _gt ┆ _gt ┆ lit ┆ ess ┆ ndy ┆ ind ┆ mid ┆ eve ┆ ed_ ┆ ed_ ┆ ge_ ┆ ir_ ┆ ir_ ┆ ned ┆ _we ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ num ┆ is_ ┆ san ┆ ili ┆ tio ┆ tio ┆ tio ┆ 5_6 ┆ 7_6 ┆ 0_7 ┆ 5_7 ┆ 0_8 ┆ 5_p ┆ _65 ┆ _67 ┆ _70 ┆ _75 ┆ _80 ┆ _85 ┆ nde ┆ _un ┆ _ag ┆ lit ┆ lit ┆ lit ┆ gh_ ┆ che ┆ ste ┆ ofe ┆ cto ┆ y_u ┆ y_b ┆ _ho ┆ for ┆ for ┆ oym ┆ g_u ┆ g_o ┆ g_v ┆ _ho ┆ _gr ┆ niv ┆ hit ┆ lac ┆ mer ┆ sia ┆ aci ┆ isp ┆ the ┆ ge_ ┆ d_e ┆ d_e ┆ d_e ┆ lis ┆ lis ┆ lis ┆ e_u ┆ e_n ┆ g_s ┆ g_1 ┆ g_2 ┆ g_3 ┆ g_5 ┆ g_1 ┆ g_2 ┆ g_5 ┆ g_m ┆ ion ┆ id_ ┆ id_ ┆ inx ┆ iny ┆ axx ┆ axy ┆ are ┆ per ┆ com ┆ tio ┆ tio ┆ lit ┆ tal ┆ d_e ┆ lis ┆ le  ┆ mal ┆ tio ┆ _pl ┆ der ┆ sab ┆ gh_ ┆ che ┆ ad_ ┆ ver ┆ emp ┆ usi ┆ usi ┆ ite ┆ ack ┆ ian ┆ spa ┆ eri ┆ cif ┆ ce_ ┆ mit ┆ _en ┆ hic ┆ ngl ┆ all ┆ rge ┆ bil ┆ tio ┆ tio ┆ tio ┆ 5_6 ┆ 7_6 ┆ 0_7 ┆ 5_7 ┆ 0_8 ┆ 5_p ┆ _65 ┆ _67 ┆ _70 ┆ _75 ┆ _80 ┆ _85 ┆ nde ┆ _un ┆ _ag ┆ lit ┆ lit ┆ lit ┆ gh_ ┆ che ┆ ste ┆ ofe ┆ cto ┆ y_u ┆ y_b ┆ _ho ┆ for ┆ for ┆ oym ┆ g_u ┆ g_o ┆ g_v ┆ _ho ┆ _gr ┆ niv ┆ hit ┆ lac ┆ mer ┆ sia ┆ aci ┆ isp ┆ the ┆ ge_ ┆ d_e ┆ d_e ┆ d_e ┆ lis ┆ lis ┆ lis ┆ e_u ┆ e_n ┆ g_s ┆ g_1 ┆ g_2 ┆ g_3 ┆ g_5 ┆ g_1 ┆ g_2 ┆ g_5 ┆ g_m ┆ ion ┆ id_ ┆ id_ ┆ inx ┆ iny ┆ axx ┆ axy ┆ are ┆ per ┆ com ┆ tio ┆ tio ┆ lit ┆ tal ┆ d_e ┆ lis ┆ le_ ┆ mal ┆ tio ┆ _pl ┆ der ┆ sab ┆ gh_ ┆ che ┆ ad_ ┆ ver ┆ emp ┆ usi ┆ usi ┆ ite ┆ ack ┆ ian ┆ spa ┆ eri ┆ cif ┆ ce_ ┆ mit ┆ _en ┆ hic ┆ ngl ┆ all ┆ rge ┆ bil ┆ num ┆ is_ ┆ san │
│ str ┆ i32 ┆ --- ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ w_f ┆ e_9 ┆ 0_h ┆ 0_h ┆ 0_h ┆ 0_h ┆ _0_ ┆ _0_ ┆ _0_ ┆ _0_ ┆ y_l ┆ ure ┆ _ho ┆ y_h ┆ _ho ┆ nt_ ┆ hou ┆ hou ┆ rat ┆ res ┆ cir ┆ _hi ┆ ath ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ _sa ┆ san ┆ iti ┆ ty_ ┆ n_t ┆ n_m ┆ n_f ┆ 6   ┆ 9   ┆ 4   ┆ 9   ┆ 4   ┆ lus ┆ _66 ┆ _69 ┆ _74 ┆ _79 ┆ _84 ┆ _pl ┆ r_5 ┆ der ┆ e   ┆ y_u ┆ y_1 ┆ y_6 ┆ sch ┆ lor ┆ rs  ┆ ssi ┆ rat ┆ niv ┆ elo ┆ use ┆ ce  ┆ ce_ ┆ ent ┆ nit ┆ ccu ┆ aca ┆ me_ ┆ oss ┆ ers ┆ e   ┆ k   ┆ ica ┆ n   ┆ fic ┆ ani ┆ r   ┆ uni ┆ ngl ┆ ngl ┆ ngl ┆ h_5 ┆ h_1 ┆ h_6 ┆ niv ┆ one ┆ tru ┆ _un ┆ _un ┆ _4_ ┆ _9_ ┆ 0_1 ┆ 0_4 ┆ 0_p ┆ obi ┆ _m  ┆ lat ┆ lon ┆ --- ┆ --- ┆ --- ┆ --- ┆ a   ┆ ime ┆ pac ┆ n_6 ┆ n_u ┆ y_t ┆ --- ┆ ngl ┆ h_t ┆ --- ┆ e   ┆ --- ┆ us  ┆ _5  ┆ ili ┆ sch ┆ lor ┆ deg ┆ ty  ┆ loy ┆ ng_ ┆ ng_ ┆ --- ┆ --- ┆ --- ┆ nic ┆ can ┆ ic_ ┆ oth ┆ ed_ ┆ gli ┆ le_ ┆ e_f ┆ _mu ┆ _mu ┆ e_h ┆ n_t ┆ n_m ┆ n_f ┆ 6_w ┆ 9_w ┆ 4_w ┆ 9_w ┆ 4_w ┆ lus ┆ _66 ┆ _69 ┆ _74 ┆ _79 ┆ _84 ┆ _pl ┆ r_5 ┆ der ┆ e_w ┆ y_u ┆ y_1 ┆ y_6 ┆ sch ┆ lor ┆ rs_ ┆ ssi ┆ rat ┆ niv ┆ elo ┆ use ┆ ce_ ┆ ce_ ┆ ent ┆ nit ┆ ccu ┆ aca ┆ me_ ┆ oss ┆ ers ┆ e_w ┆ k_w ┆ ica ┆ n_w ┆ fic ┆ ani ┆ r_w ┆ uni ┆ ngl ┆ ngl ┆ ngl ┆ h_5 ┆ h_1 ┆ h_6 ┆ niv ┆ one ┆ tru ┆ _un ┆ _un ┆ _4_ ┆ _9_ ┆ 0_1 ┆ 0_4 ┆ 0_p ┆ obi ┆ _m_ ┆ lat ┆ lon ┆ _wa ┆ _wa ┆ _wa ┆ _wa ┆ a_w ┆ ime ┆ pac ┆ n_6 ┆ n_u ┆ y_t ┆ _wa ┆ ngl ┆ h_t ┆ was ┆ e_w ┆ _wa ┆ us_ ┆ _5_ ┆ ili ┆ sch ┆ lor ┆ deg ┆ ty_ ┆ loy ┆ ng_ ┆ ng_ ┆ _wa ┆ _wa ┆ _wa ┆ nic ┆ can ┆ ic_ ┆ oth ┆ ed_ ┆ gli ┆ le_ ┆ e_f ┆ _mu ┆ _mu ┆ e_h ┆ _sa ┆ san ┆ iti │

In [35]:
# Temporarily increase row display limit
pl.Config.set_tbl_rows(500)

missing_target_tracts = (
    df.filter(pl.col("reliability_index").is_null())
      .select(["tract"])
      .unique()
      .sort(["tract"])
)

missing_target_tracts

shape: (32, 1)
┌─────────────┐
│ tract       │
│ ---         │
│ str         │
╞═════════════╡
│ 55003990000 │
│ 55007990000 │
│ 55009980000 │
│ 55025001603 │
│ 55029990000 │
│ 55031990000 │
│ 55051990000 │
│ 55059990000 │
│ 55061990000 │
│ 55071990000 │
│ 55075990000 │
│ 55079006500 │
│ 55079006600 │
│ 55079006700 │
│ 55079008100 │
│ 55079008500 │
│ 55079008700 │
│ 55079008900 │
│ 55079009000 │
│ 55079010600 │
│ 55079011100 │
│ 55079013400 │
│ 55079013700 │
│ 55079014300 │
│ 55079014900 │
│ 55079017400 │
│ 55079185800 │
│ 55079990000 │
│ 55083990000 │
│ 55101980000 │
│ 55101990000 │
│ 55117990000 │
└─────────────┘

In [37]:

# Make sure all rows and columns are displayed
pl.Config.set_tbl_cols(-1)
pl.Config.set_tbl_rows(500)

# Load the Ookla target engineering dataset
ookla = pl.read_parquet(
    "../../data/processed/feature_engineering/ookla_tract_quarter_target_features.parquet"
)

# Convert to a Python list for filtering
tract_list = missing_target_tracts["tract"].to_list()

# Filter the Ookla dataset to only those tracts
ookla_missing = (
    ookla.filter(pl.col("tract").is_in(tract_list))
         .sort(["tract", "year", "quarter"])
)

ookla_missing

shape: (80, 80)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ tra ┆ yea ┆ qua ┆ dow ┆ dow ┆ upl ┆ upl ┆ lat ┆ lat ┆ dow ┆ dow ┆ dow ┆ upl ┆ upl ┆ upl ┆ lat ┆ lat ┆ lat ┆ tes ┆ dev ┆ til ┆ dow ┆ dow ┆ dow ┆ dow ┆ upl ┆ upl ┆ upl ┆ upl ┆ lat ┆ lat ┆ lat ┆ lat ┆ dow ┆ upl ┆ lat ┆ dow ┆ upl ┆ lat ┆ tes ┆ dev ┆ dow ┆ dow ┆ upl ┆ upl ┆ lat ┆ lat ┆ lat ┆ dow ┆ upl ┆ lat ┆ dow ┆ upl ┆ lat ┆ dow ┆ dow ┆ dow ┆ dow ┆ upl ┆ upl ┆ upl ┆ upl ┆ lat ┆ lat ┆ lat ┆ lat ┆ dow ┆ dow ┆ upl ┆ upl ┆ lat ┆ lat ┆ lat ┆ tes ┆ dev ┆ tes ┆ num ┆ is_ ┆ san ┆ rel │
│ ct  ┆ r   ┆ rte ┆ nlo ┆ nlo ┆ oad ┆ oad ┆ enc ┆ enc ┆ nlo ┆ nlo ┆ nlo ┆ oad ┆ oad ┆ oad ┆ enc ┆ enc ┆ enc ┆ ts_ ┆ ice ┆ e_c ┆ nlo ┆ nlo ┆ nlo ┆ nlo ┆ oad ┆ oad ┆ oad ┆ oad ┆ enc ┆ enc ┆ enc ┆ enc ┆ nlo ┆ oad ┆ enc ┆ nlo ┆ oad ┆ enc ┆ ts_ ┆ ice ┆ nlo ┆ nlo ┆ oad ┆ oad ┆ enc ┆ enc ┆ enc ┆ nlo ┆ oad ┆ enc ┆ nlo ┆ oad ┆ enc ┆ nlo ┆ nlo ┆ nlo ┆ nlo ┆ oad ┆ oad ┆ oad ┆ oad ┆ enc ┆ enc ┆ enc ┆ enc ┆ nlo ┆ nlo ┆ oad ┆ oad ┆ enc ┆ enc ┆ enc ┆ ts_ ┆ ice ┆ ts_ ┆ _sa ┆ san ┆ iti ┆ iab │
│ --- ┆ --- ┆ r   ┆ ad_ ┆ ad_ ┆ _me ┆ _me ┆ y_m ┆ y_m ┆ ad_ ┆ ad_ ┆ ad_ ┆ _st ┆ _mi ┆ _ma ┆ y_s ┆ y_m ┆ y_m ┆ tot ┆ s_t ┆ oun ┆ ad_ ┆ ad_ ┆ ad_ ┆ ad_ ┆ _p1 ┆ _p2 ┆ _p7 ┆ _p9 ┆ y_p ┆ y_p ┆ y_p ┆ y_p ┆ ad_ ┆ _ra ┆ y_r ┆ ad_ ┆ _cv ┆ y_c ┆ per ┆ s_p ┆ ad_ ┆ ad_ ┆ _lt ┆ _lt ┆ y_g ┆ y_g ┆ y_p ┆ ad_ ┆ _cv ┆ y_c ┆ ad_ ┆ _ra ┆ y_r ┆ ad_ ┆ ad_ ┆ ad_ ┆ ad_ ┆ _p1 ┆ _p2 ┆ _p7 ┆ _p9 ┆ y_p ┆ y_p ┆ y_p ┆ y_p ┆ ad_ ┆ ad_ ┆ _lt ┆ _lt ┆ y_g ┆ y_g ┆ y_p ┆ per ┆ s_p ┆ tot ┆ nit ┆ iti ┆ zat ┆ ili │
│ str ┆ i32 ┆ --- ┆ mea ┆ med ┆ an  ┆ dia ┆ ean ┆ edi ┆ std ┆ min ┆ max ┆ d   ┆ n   ┆ x   ┆ td  ┆ in  ┆ ax  ┆ al  ┆ ota ┆ t   ┆ p10 ┆ p25 ┆ p75 ┆ p90 ┆ 0   ┆ 5   ┆ 5   ┆ 0   ┆ 10  ┆ 25  ┆ 75  ┆ 90  ┆ ran ┆ nge ┆ ang ┆ cv  ┆ --- ┆ v   ┆ _ti ┆ er_ ┆ lt_ ┆ lt_ ┆ _3_ ┆ _20 ┆ t_1 ┆ t_1 ┆ 90_ ┆ cv_ ┆ _wa ┆ v_w ┆ ran ┆ nge ┆ ang ┆ p10 ┆ p25 ┆ p75 ┆ p90 ┆ 0_w ┆ 5_w ┆ 5_w ┆ 0_w ┆ 10_ ┆ 25_ ┆ 75_ ┆ 90_ ┆ lt_ ┆ lt_ ┆ _3_ ┆ _20 ┆ t_1 ┆ t_1 ┆ 90_ ┆ _ti ┆ er_ ┆ al_ ┆ ize ┆ zed ┆ ion ┆ ty_ │
│     ┆     ┆ str ┆ n   ┆ ian ┆ --- ┆ n   ┆ --- ┆ an  ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ l   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ ge  ┆ --- ┆ e   ┆ --- ┆ f64 ┆ --- ┆ le  ┆ til ┆ 25_ ┆ 100 ┆ fla ┆ _fl ┆ 00_ ┆ 50_ ┆ gt_ ┆ was ┆ s_n ┆ as_ ┆ ge_ ┆ _wa ┆ e_w ┆ _wa ┆ _wa ┆ _wa ┆ _wa ┆ as_ ┆ as_ ┆ as_ ┆ as_ ┆ was ┆ was ┆ was ┆ was ┆ 25_ ┆ 100 ┆ fla ┆ _fl ┆ 00_ ┆ 50_ ┆ gt_ ┆ le_ ┆ til ┆ was ┆ d_f ┆ --- ┆ _le ┆ ind │
│     ┆     ┆     ┆ --- ┆ --- ┆ f64 ┆ --- ┆ f64 ┆ --- ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ i64 ┆ i64 ┆ i64 ┆ --- ┆ u32 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ f64 ┆ --- ┆ f64 ┆     ┆ f64 ┆ --- ┆ e   ┆ fla ┆ _fl ┆ g   ┆ ag  ┆ fla ┆ fla ┆ 200 ┆ _nu ┆ ull ┆ nul ┆ was ┆ s_n ┆ as_ ┆ s_n ┆ s_n ┆ s_n ┆ s_n ┆ nul ┆ nul ┆ nul ┆ nul ┆ _nu ┆ _nu ┆ _nu ┆ _nu ┆ fla ┆ _fl ┆ g_w ┆ ag_ ┆ fla ┆ fla ┆ 200 ┆ was ┆ e_w ┆ _nu ┆ iel ┆ boo ┆ vel ┆ ex  │
│     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆ f64 ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆ i64 ┆     ┆     ┆     ┆ f64 ┆ --- ┆ g   ┆ ag  ┆ --- ┆ --- ┆ g   ┆ g   ┆ _fl ┆ ll  ┆ --- ┆ l   ┆ _nu ┆ ull ┆ nul ┆ ull ┆ ull ┆ ull ┆ ull ┆ l   ┆ l   ┆ l   ┆ l   ┆ ll  ┆ ll  ┆ ll  ┆ ll  ┆ g_w ┆ ag_ ┆ as_ ┆ was ┆ g_w ┆ g_w ┆ _fl ┆ _nu ┆ as_ ┆ ll  ┆ ds  ┆ l   ┆ --- ┆ --- │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ --- ┆ boo ┆ boo ┆ --- ┆ --- ┆ ag  ┆ --- ┆ boo ┆ --- ┆ ll  ┆ --- ┆ l   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ as_ ┆ was ┆ nul ┆ _nu ┆ as_ ┆ as_ ┆ ag_ ┆ ll  ┆ nul ┆ --- ┆ --- ┆     ┆ str ┆ f64 │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ boo ┆ boo ┆ l   ┆ l   ┆ boo ┆ boo ┆ --- ┆ boo ┆ l   ┆ boo ┆ --- ┆ boo ┆ --- ┆ boo ┆ boo ┆ boo ┆ boo ┆ boo ┆ boo ┆ boo ┆ boo ┆ boo ┆ boo ┆ boo ┆ boo ┆ nul ┆ _nu ┆ l   ┆ ll  ┆ nul ┆ nul ┆ was ┆ --- ┆ l   ┆ boo ┆ u32 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆     ┆     ┆ l   ┆ l   ┆ boo ┆ l   ┆     ┆ l   ┆ boo ┆ l   ┆ boo ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ ll  ┆ --- ┆ --- ┆ l   ┆ l   ┆ _nu ┆ boo ┆ --- ┆ l   ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆ l   ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ boo ┆ boo ┆ --- ┆ --- ┆ …   ┆ l   ┆ boo ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ boo ┆ boo ┆ l   ┆ l   ┆ boo ┆ boo ┆ --- ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆     ┆     ┆ l   ┆ l   ┆ boo ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 550 ┆ 202 ┆ Q2  ┆ 87. ┆ 87. ┆ 94. ┆ 94. ┆ 6.0 ┆ 6.0 ┆ nul ┆ 87. ┆ 87. ┆ nul ┆ 94. ┆ 94. ┆ nul ┆ 6   ┆ 6   ┆ 1   ┆ 1   ┆ 1   ┆ 87. ┆ 87. ┆ 87. ┆ 87. ┆ 94. ┆ 94. ┆ 94. ┆ 94. ┆ 6.0 ┆ 6.0 ┆ 6.0 ┆ 6.0 ┆ 0.0 ┆ 0.0 ┆ 0   ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 1.0 ┆ fal ┆ tru ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ 0   ┆ fal ┆ non ┆ 67. │
│ 079 ┆ 4   ┆     ┆ 476 ┆ 476 ┆ 08  ┆ 08  ┆     ┆     ┆ l   ┆ 476 ┆ 476 ┆ l   ┆ 08  ┆ 08  ┆ l   ┆     ┆     ┆     ┆     ┆     ┆ 476 ┆ 476 ┆ 476 ┆ 476 ┆ 08  ┆ 08  ┆ 08  ┆ 08  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ e   ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆     ┆ se  ┆ e   ┆ 356 │
│ 900 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 931 │
│ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 550 ┆ 202 ┆ Q3  ┆ 16. ┆ 16. ┆ 19. ┆ 19. ┆ 8.0 ┆ 8.0 ┆ nul ┆ 16. ┆ 16. ┆ nul ┆ 19. ┆ 19. ┆ nul ┆ 8   ┆ 8   ┆ 1   ┆ 1   ┆ 1   ┆ 16. ┆ 16. ┆ 16. ┆ 16. ┆ 19. ┆ 19. ┆ 19. ┆ 19. ┆ 8.0 ┆ 8.0 ┆ 8.0 ┆ 8.0 ┆ 0.0 ┆ 0.0 ┆ 0   ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 1.0 ┆ tru ┆ tru ┆ fal ┆ tru ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ 0   ┆ fal ┆ non ┆ 27. │
│ 079 ┆ 4   ┆     ┆ 001 ┆ 001 ┆ 146 ┆ 146 ┆     ┆     ┆ l   ┆ 001 ┆ 001 ┆ l   ┆ 146 ┆ 146 ┆ l   ┆     ┆     ┆     ┆     ┆     ┆ 001 ┆ 001 ┆ 001 ┆ 001 ┆ 146 ┆ 146 ┆ 146 ┆ 146 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆ e   ┆ se  ┆ e   ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆     ┆ se  ┆ e   ┆ 546 │
│ 900 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 951 │
│ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 550 ┆ 202 ┆ Q2  ┆ 53. ┆ 53. ┆ 3.4 ┆ 3.4 ┆ 99. ┆ 99. ┆ nul ┆ 53. ┆ 53. ┆ nul ┆ 3.4 ┆ 3.4 ┆ nul ┆ 99  ┆ 99  ┆ 1   ┆ 1   ┆ 1   ┆ 53. ┆ 53. ┆ 53. ┆ 53. ┆ 3.4 ┆ 3.4 ┆ 3.4 ┆ 3.4 ┆ 99. ┆ 99. ┆ 99. ┆ 99. ┆ 0.0 ┆ 0.0 ┆ 0   ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 1.0 ┆ fal ┆ tru ┆ fal ┆ tru ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ 0   ┆ fal ┆ non ┆ 23. │
│ 299 ┆ 4   ┆     ┆ 608 ┆ 608 ┆ 6   ┆ 6   ┆ 0   ┆ 0   ┆ l   ┆ 608 ┆ 608 ┆ l   ┆ 6   ┆ 6   ┆ l   ┆     ┆     ┆     ┆     ┆     ┆ 608 ┆ 608 ┆ 608 ┆ 608 ┆ 6   ┆ 6   ┆ 6   ┆ 6   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ e   ┆ se  ┆ e   ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆     ┆ se  ┆ e   ┆ 908 │
│ 900 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 347 │
│ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 550 ┆ 202 ┆ Q3  ┆ 58. ┆ 58. ┆ 30. ┆ 30. ┆ 26. ┆ 26. ┆ nul ┆ 58. ┆ 58. ┆ nul ┆ 30. ┆ 30. ┆ nul ┆ 26  ┆ 26  ┆ 1   ┆ 1   ┆ 1   ┆ 58. ┆ 58. ┆ 58. ┆ 58. ┆ 30. ┆ 30. ┆ 30. ┆ 30. ┆ 26. ┆ 26. ┆ 26. ┆ 26. ┆ 0.0 ┆ 0.0 ┆ 0   ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 1.0 ┆ fal ┆ tru ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ 0   ┆ fal ┆ non ┆ 50. │
│ 299 ┆ 4   ┆     ┆ 098 ┆ 098 ┆ 691 ┆ 691 ┆ 0   ┆ 0   ┆ l   ┆ 098 ┆ 098 ┆ l   ┆ 691 ┆ 691 ┆ l   ┆     ┆     ┆     ┆     ┆     ┆ 098 ┆ 098 ┆ 098 ┆ 098 ┆ 691 ┆ 691 ┆ 691 ┆ 691 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ e   ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆     ┆ se  ┆ e   ┆ 174 │
│ 900 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 931 │
│ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 550 ┆ 202 ┆ Q1  ┆ 133 ┆ 133 ┆ 25. ┆ 25. ┆ 27. ┆ 27. ┆ 23. ┆ 117 ┆ 150 ┆ 2.6 ┆ 23. ┆ 27. ┆ 5.6 ┆ 23  ┆ 31  ┆ 2   ┆ 2   ┆ 2   ┆ 117 ┆ 117 ┆ 150 ┆ 150 ┆ 23. ┆ 23. ┆ 27. ┆ 27. ┆ 23. ┆ 23. ┆ 31. ┆ 31. ┆ 33. ┆ 3.7 ┆ 8   ┆ 0.1 ┆ 0.1 ┆ 0.2 ┆ 1.0 ┆ 1.0 ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ 0   ┆ fal ┆ non ┆ 73. │
│ 299 ┆ 5   ┆     ┆ .68 ┆ .68 ┆ 142 ┆ 142 ┆ 0   ┆ 0   ┆ 445 ┆ .10 ┆ .25 ┆ 516 ┆ 267 ┆ 017 ┆ 568 ┆     ┆     ┆     ┆     ┆     ┆ .10 ┆ .10 ┆ .25 ┆ .25 ┆ 267 ┆ 267 ┆ 017 ┆ 017 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 157 ┆ 5   ┆     ┆ 753 ┆ 054 ┆ 095 ┆     ┆     ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆     ┆ se  ┆ e   ┆ 949 │
│ 900 ┆     ┆     ┆ 05  ┆ 05  ┆     ┆     ┆     ┆     ┆ 54  ┆ 2   ┆ 9   ┆ 5   ┆     ┆     ┆ 54  ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆ 2   ┆ 9   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 85  ┆ 67  ┆ 13  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 432 │
│ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 550 ┆ 202 ┆ Q3  ┆ 308 ┆ 308 ┆ 18. ┆ 18. ┆ 29. ┆ 29. ┆ nul ┆ 308 ┆ 308 ┆ nul ┆ 18. ┆ 18. ┆ nul ┆ 29  ┆ 29  ┆ 1   ┆ 1   ┆ 1   ┆ 308 ┆ 308 ┆ 308 ┆ 308 ┆ 18. ┆ 18. ┆ 18. ┆ 18. ┆ 29. ┆ 29. ┆ 29. ┆ 29. ┆ 0.0 ┆ 0.0 ┆ 0   ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 1.0 ┆ fal ┆ fal ┆ fal ┆ tru ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ 0   ┆ fal ┆ non ┆ 74. │
│ 299 ┆ 5   ┆     ┆ .77 ┆ .77 ┆ 819 ┆ 819 ┆ 0   ┆ 0   ┆ l   ┆ .77 ┆ .77 ┆ l   ┆ 819 ┆ 819 ┆ l   ┆     ┆     ┆     ┆     ┆     ┆ .77 ┆ .77 ┆ .77 ┆ .77 ┆ 819 ┆ 819 ┆ 819 ┆ 819 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ se  ┆ se  ┆ e   ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆ se  ┆     ┆ se  ┆ e   ┆ 735 │
│ 900 ┆     ┆     ┆ 1   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ 1   ┆ 1   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 056 │
│ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 550 ┆ 202 ┆ Q4  ┆ 84. ┆ 84. ┆ 11. ┆ 11. ┆ 70. ┆ 70. ┆ nul ┆ 84. ┆ 84. ┆ nul ┆ 11. ┆ 11. ┆ nul ┆ 70  ┆ 70  ┆ 1   ┆ 1   ┆ 1   ┆ 84. ┆ 84. ┆ 84. ┆ 84. ┆ 11. ┆ 11. ┆ 11. ┆ 11. ┆ 70. ┆ 70. ┆ 70. ┆ 70. ┆ 0.0 ┆ 0.0 ┆ 0   ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 1.0 ┆ fal ┆ tru ┆ fal ┆ tru ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ fal ┆ 0   ┆ fal ┆ non ┆ 36. │

In [40]:
# Rows missing reliability_index in unified dataset
missing_target_full = (
    df.filter(pl.col("reliability_index").is_null())
      .select(["tract", "year", "quarter"])
      .unique()
)

# Keys present in Ookla
ookla_keys = (
    ookla.select(["tract", "year", "quarter"])
         .unique()
)

# Inner join: only rows that exist in BOTH datasets
missing_that_exist_in_ookla = (
    missing_target_full.join(
        ookla_keys,
        on=["tract", "year", "quarter"],
        how="inner"
    )
)

missing_that_exist_in_ookla

shape: (0, 3)
┌───────┬──────┬─────────┐
│ tract ┆ year ┆ quarter │
│ ---   ┆ ---  ┆ ---     │
│ str   ┆ i32  ┆ str     │
╞═══════╪══════╪═════════╡
└───────┴──────┴─────────┘

In [41]:
missing_that_do_not_exist_in_ookla = (
    missing_target_full.join(
        ookla_keys,
        on=["tract", "year", "quarter"],
        how="anti"
    )
)

missing_that_do_not_exist_in_ookla

shape: (144, 3)
┌─────────────┬──────┬─────────┐
│ tract       ┆ year ┆ quarter │
│ ---         ┆ ---  ┆ ---     │
│ str         ┆ i32  ┆ str     │
╞═════════════╪══════╪═════════╡
│ 55101990000 ┆ 2024 ┆ Q3      │
│ 55079017400 ┆ 2024 ┆ Q2      │
│ 55079008700 ┆ 2025 ┆ Q1      │
│ 55009980000 ┆ 2025 ┆ Q2      │
│ 55079008900 ┆ 2025 ┆ Q3      │
│ 55007990000 ┆ 2025 ┆ Q1      │
│ 55025001603 ┆ 2025 ┆ Q1      │
│ 55025001603 ┆ 2024 ┆ Q3      │
│ 55079010600 ┆ 2024 ┆ Q1      │
│ 55079008700 ┆ 2025 ┆ Q3      │
│ 55079017400 ┆ 2025 ┆ Q1      │
│ 55079008100 ┆ 2025 ┆ Q3      │
│ 55009980000 ┆ 2024 ┆ Q2      │
│ 55079014300 ┆ 2025 ┆ Q2      │
│ 55101990000 ┆ 2024 ┆ Q4      │
│ 55079008900 ┆ 2024 ┆ Q1      │
│ 55051990000 ┆ 2025 ┆ Q2      │
│ 55031990000 ┆ 2024 ┆ Q2      │
│ 55083990000 ┆ 2024 ┆ Q1      │
│ 55079014300 ┆ 2024 ┆ Q2      │
│ 55079008500 ┆ 2025 ┆ Q3      │
│ 55079008900 ┆ 2024 ┆ Q2      │
│ 55009980000 ┆ 2025 ┆ Q1      │
│ 55083990000 ┆ 2025 ┆ Q3      │
│ 55079013400 ┆ 2025 ┆ Q1      │
│ 55079008700 ┆ 2024 ┆ Q4      │
│ 55079008100 ┆ 2024 ┆ Q3      │
│ 55083990000 ┆ 2024 ┆ Q3      │
│ 55079014300 ┆ 2025 ┆ Q1      │
│ 55009980000 ┆ 2024 ┆ Q3      │
│ 55079017400 ┆ 2024 ┆ Q3      │
│ 55079008100 ┆ 2024 ┆ Q4      │
│ 55051990000 ┆ 2024 ┆ Q1      │
│ 55025001603 ┆ 2024 ┆ Q2      │
│ 55059990000 ┆ 2025 ┆ Q2      │
│ 55079017400 ┆ 2025 ┆ Q2      │
│ 55025001603 ┆ 2024 ┆ Q1      │
│ 55029990000 ┆ 2025 ┆ Q2      │
│ 55009980000 ┆ 2024 ┆ Q4      │
│ 55079013700 ┆ 2024 ┆ Q4      │
│ 55007990000 ┆ 2024 ┆ Q1      │
│ 55079008100 ┆ 2025 ┆ Q2      │
│ 55079008100 ┆ 2025 ┆ Q1      │
│ 55075990000 ┆ 2024 ┆ Q4      │
│ 55079006600 ┆ 2025 ┆ Q3      │
│ 55061990000 ┆ 2024 ┆ Q4      │
│ 55079010600 ┆ 2024 ┆ Q2      │
│ 55071990000 ┆ 2024 ┆ Q1      │
│ 55079008700 ┆ 2024 ┆ Q2      │
│ 55051990000 ┆ 2025 ┆ Q3      │
│ 55059990000 ┆ 2025 ┆ Q1      │
│ 55051990000 ┆ 2024 ┆ Q4      │
│ 55079011100 ┆ 2025 ┆ Q3      │
│ 55083990000 ┆ 2024 ┆ Q2      │
│ 55061990000 ┆ 2024 ┆ Q2      │
│ 55079011100 ┆ 2024 ┆ Q3      │
│ 55101980000 ┆ 2024 ┆ Q3      │
│ 55079014300 ┆ 2025 ┆ Q3      │
│ 55101990000 ┆ 2025 ┆ Q1      │
│ 55079990000 ┆ 2024 ┆ Q1      │
│ 55051990000 ┆ 2024 ┆ Q3      │
│ 55079008700 ┆ 2025 ┆ Q2      │
│ 55079008100 ┆ 2024 ┆ Q1      │
│ 55029990000 ┆ 2024 ┆ Q1      │
│ 55079017400 ┆ 2025 ┆ Q3      │
│ 55101980000 ┆ 2025 ┆ Q2      │
│ 55079011100 ┆ 2024 ┆ Q4      │
│ 55079010600 ┆ 2024 ┆ Q4      │
│ 55079011100 ┆ 2024 ┆ Q2      │
│ 55101980000 ┆ 2025 ┆ Q1      │
│ 55079013700 ┆ 2024 ┆ Q2      │
│ 55051990000 ┆ 2024 ┆ Q2      │
│ 55079014900 ┆ 2024 ┆ Q2      │
│ 55031990000 ┆ 2024 ┆ Q3      │
│ 55079185800 ┆ 2024 ┆ Q4      │
│ 55101990000 ┆ 2024 ┆ Q1      │
│ 55101980000 ┆ 2024 ┆ Q4      │
│ 55003990000 ┆ 2025 ┆ Q1      │
│ 55079010600 ┆ 2025 ┆ Q1      │
│ 55079011100 ┆ 2025 ┆ Q1      │
│ 55079013700 ┆ 2024 ┆ Q1      │
│ 55059990000 ┆ 2024 ┆ Q4      │
│ 55079008500 ┆ 2024 ┆ Q4      │
│ 55079014300 ┆ 2024 ┆ Q3      │
│ 55079010600 ┆ 2024 ┆ Q3      │
│ 55075990000 ┆ 2024 ┆ Q3      │
│ 55079017400 ┆ 2024 ┆ Q4      │
│ 55079014300 ┆ 2024 ┆ Q4      │
│ 55079008900 ┆ 2025 ┆ Q2      │
│ 55079009000 ┆ 2024 ┆ Q2      │
│ 55079013700 ┆ 2024 ┆ Q3      │
│ 55003990000 ┆ 2025 ┆ Q3      │
│ 55059990000 ┆ 2024 ┆ Q3      │
│ 55051990000 ┆ 2025 ┆ Q1      │
│ 55059990000 ┆ 2024 ┆ Q2      │
│ 55025001603 ┆ 2025 ┆ Q3      │
│ 55079008700 ┆ 2024 ┆ Q3      │
│ 55031990000 ┆ 2024 ┆ Q1      │
│ 55079008100 ┆ 2024 ┆ Q2      │
│ 55079014900 ┆ 2024 ┆ Q3      │
│ 55007990000 ┆ 2024 ┆ Q4      │
│ 55007990000 ┆ 2025 ┆ Q2      │
│ 55117990000 ┆ 2024 ┆ Q2      │
│ 55079011100 ┆ 2024 ┆ Q1      │
│ 55079017400 ┆ 2024 ┆ Q1      │
│ 55079006700 ┆ 2024 ┆ Q1      │
│ 55079008900 ┆ 2024 ┆ Q3      │
│ 55061990000 ┆ 2025 ┆ Q1      │
│ 55079990000 ┆ 2025 ┆ Q1      │
│ 55079013700 ┆ 2025 ┆ Q1      │
│ 55079013700 ┆ 2025 ┆ Q2      │
│ 55061990000 ┆ 2024 ┆ Q1      │
│ 55059990000 ┆ 2024 ┆ Q1      │
│ 55079010600 ┆ 2025 ┆ Q2      │
│ 55025001603 ┆ 2025 ┆ Q2      │
│ 55079014300 ┆ 2024 ┆ Q1      │
│ 55003990000 ┆ 2024 ┆ Q2      │
│ 55083990000 ┆ 2025 ┆ Q1      │
│ 55007990000 ┆ 2025 ┆ Q3      │
│ 55025001603 ┆ 2024 ┆ Q4      │
│ 55101980000 ┆ 2024 ┆ Q1      │
│ 55003990000 ┆ 2024 ┆ Q1      │
│ 55003990000 ┆ 2025 ┆ Q2      │
│ 55075990000 ┆ 2025 ┆ Q1      │
│ 55079008700 ┆ 2024 ┆ Q1      │
│ 55075990000 ┆ 2025 ┆ Q2      │
│ 55079013700 ┆ 2025 ┆ Q3      │
│ 55009980000 ┆ 2025 ┆ Q3      │
│ 55079011100 ┆ 2025 ┆ Q2      │
│ 55003990000 ┆ 2024 ┆ Q4      │
│ 55117990000 ┆ 2024 ┆ Q1      │
│ 55003990000 ┆ 2024 ┆ Q3      │
│ 55079006500 ┆ 2024 ┆ Q3      │
│ 55009980000 ┆ 2024 ┆ Q1      │
│ 55031990000 ┆ 2025 ┆ Q1      │
│ 55117990000 ┆ 2024 ┆ Q4      │
│ 55079006700 ┆ 2025 ┆ Q3      │
│ 55079013400 ┆ 2024 ┆ Q4      │
│ 55071990000 ┆ 2025 ┆ Q2      │
│ 55071990000 ┆ 2025 ┆ Q1      │
│ 55079010600 ┆ 2025 ┆ Q3      │
│ 55101980000 ┆ 2025 ┆ Q3      │
│ 55083990000 ┆ 2025 ┆ Q2      │
│ 55029990000 ┆ 2024 ┆ Q4      │
└─────────────┴──────┴─────────┘

The 144 records with null reliability index values are the result of tract, year, quarter combinations for which no Ookla speed tests were performed, meaning no reliability_index value may be computed for those tract, year, quarter records. Updated unified_tract_quarter_candidate_features to exclude 1) tracts having a tract_code starting with 99, for those tracts that are unpopulated and 2) any records having a null reliability_index, for those tract, year, quarters without Ookla speed test data.

In [22]:
# check for variance among numeric features, those with no variance are not of use for modeling

numeric_cols = [
    name for name, dtype in zip(df.columns, df.dtypes)
    if dtype.is_numeric()
]

variance = df.select([
    pl.var(col).alias(f"{col}_var")
    for col in numeric_cols
    if col != "reliability_index"
])
variance

shape: (1, 370)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ yea ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ wei ┆ tem ┆ tem ┆ gus ┆ gus ┆ gus ┆ gus ┆ pre ┆ pre ┆ pre ┆ pre ┆ vis ┆ low ┆ wet ┆ col ┆ hot ┆ sto ┆ obs ┆ exp ┆ cov ┆ win ┆ win ┆ sus ┆ sev ┆ lcd ┆ pop ┆ pop ┆ pop ┆ mal ┆ mal ┆ mal ┆ mal ┆ mal ┆ mal ┆ fem ┆ fem ┆ fem ┆ fem ┆ fem ┆ fem ┆ mal ┆ fem ┆ med ┆ dis ┆ dis ┆ dis ┆ edu ┆ edu ┆ edu ┆ edu ┆ edu ┆ pov ┆ pov ┆ med ┆ lab ┆ lab ┆ une ┆ hou ┆ hou ┆ hou ┆ med ┆ med ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ rac ┆ lan ┆ lim ┆ lim ┆ lim ┆ no_ ┆ no_ ┆ no_ ┆ veh ┆ veh ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ hou ┆ ele ┆ cen ┆ cen ┆ bbo ┆ bbo ┆ bbo ┆ bbo ┆ tra ┆ tra ┆ tra ┆ pop ┆ pop ┆ dis ┆ edu ┆ lim ┆ no_ ┆ pct ┆ pct ┆ sex ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ pct ┆ tra │
│ r_v ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ ght ┆ p_b ┆ p_a ┆ t_g ┆ t_g ┆ t_g ┆ t_g ┆ cip ┆ cip ┆ cip ┆ cip ┆ ibi ┆ _pr ┆ _wi ┆ d_w ┆ _hu ┆ rm_ ┆ erv ┆ ect ┆ era ┆ d_d ┆ d_d ┆ tai ┆ ere ┆ v2_ ┆ ula ┆ ula ┆ ula ┆ e_6 ┆ e_6 ┆ e_7 ┆ e_7 ┆ e_8 ┆ e_8 ┆ ale ┆ ale ┆ ale ┆ ale ┆ ale ┆ ale ┆ e_u ┆ ale ┆ ian ┆ abi ┆ abi ┆ abi ┆ _hi ┆ _ba ┆ _ma ┆ _pr ┆ _do ┆ ert ┆ ert ┆ ian ┆ or_ ┆ or_ ┆ mpl ┆ sin ┆ sin ┆ sin ┆ ian ┆ ian ┆ e_u ┆ e_w ┆ e_b ┆ e_a ┆ e_a ┆ e_p ┆ e_h ┆ e_o ┆ gua ┆ ite ┆ ite ┆ ite ┆ eng ┆ eng ┆ eng ┆ icl ┆ icl ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ sin ┆ vat ┆ tro ┆ tro ┆ x_m ┆ x_m ┆ x_m ┆ x_m ┆ ct_ ┆ ct_ ┆ ct_ ┆ ula ┆ ula ┆ abi ┆ _to ┆ ite ┆ eng ┆ _ma ┆ _fe ┆ _ra ┆ _65 ┆ _un ┆ _di ┆ _hi ┆ _ba ┆ _gr ┆ _po ┆ _un ┆ _ho ┆ _ho ┆ _wh ┆ _bl ┆ _as ┆ _hi ┆ _am ┆ _pa ┆ _ra ┆ _li ┆ _no ┆ _ve ┆ _si ┆ _sm ┆ _la ┆ _mo ┆ ct_ │
│ ar  ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ ed_ ┆ elo ┆ bov ┆ t_2 ┆ t_3 ┆ t_4 ┆ t_5 ┆ _gt ┆ _gt ┆ _gt ┆ _gt ┆ lit ┆ ess ┆ ndy ┆ ind ┆ mid ┆ eve ┆ ed_ ┆ ed_ ┆ ge_ ┆ ir_ ┆ ir_ ┆ ned ┆ _we ┆ num ┆ tio ┆ tio ┆ tio ┆ 5_6 ┆ 7_6 ┆ 0_7 ┆ 5_7 ┆ 0_8 ┆ 5_p ┆ _65 ┆ _67 ┆ _70 ┆ _75 ┆ _80 ┆ _85 ┆ nde ┆ _un ┆ _ag ┆ lit ┆ lit ┆ lit ┆ gh_ ┆ che ┆ ste ┆ ofe ┆ cto ┆ y_u ┆ y_b ┆ _ho ┆ for ┆ for ┆ oym ┆ g_u ┆ g_o ┆ g_v ┆ _ho ┆ _gr ┆ niv ┆ hit ┆ lac ┆ mer ┆ sia ┆ aci ┆ isp ┆ the ┆ ge_ ┆ d_e ┆ d_e ┆ d_e ┆ lis ┆ lis ┆ lis ┆ e_u ┆ e_n ┆ g_s ┆ g_1 ┆ g_2 ┆ g_3 ┆ g_5 ┆ g_1 ┆ g_2 ┆ g_5 ┆ g_m ┆ ion ┆ id_ ┆ id_ ┆ inx ┆ iny ┆ axx ┆ axy ┆ are ┆ per ┆ com ┆ tio ┆ tio ┆ lit ┆ tal ┆ d_e ┆ lis ┆ le_ ┆ mal ┆ tio ┆ _pl ┆ der ┆ sab ┆ gh_ ┆ che ┆ ad_ ┆ ver ┆ emp ┆ usi ┆ usi ┆ ite ┆ ack ┆ ian ┆ spa ┆ eri ┆ cif ┆ ce_ ┆ mit ┆ _en ┆ hic ┆ ngl ┆ all ┆ rge ┆ bil ┆ num │
│ --- ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ dry ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ wet ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ dew ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ rel ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ pre ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ vis ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ sta ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ bar ┆ w_f ┆ e_9 ┆ 0_h ┆ 0_h ┆ 0_h ┆ 0_h ┆ _0_ ┆ _0_ ┆ _0_ ┆ _0_ ┆ y_l ┆ ure ┆ _ho ┆ y_h ┆ _ho ┆ nt_ ┆ hou ┆ hou ┆ rat ┆ res ┆ cir ┆ _hi ┆ ath ┆ _sa ┆ n_t ┆ n_m ┆ n_f ┆ 6_v ┆ 9_v ┆ 4_v ┆ 9_v ┆ 4_v ┆ lus ┆ _66 ┆ _69 ┆ _74 ┆ _79 ┆ _84 ┆ _pl ┆ r_5 ┆ der ┆ e_v ┆ y_u ┆ y_1 ┆ y_6 ┆ sch ┆ lor ┆ rs_ ┆ ssi ┆ rat ┆ niv ┆ elo ┆ use ┆ ce_ ┆ ce_ ┆ ent ┆ nit ┆ ccu ┆ aca ┆ me_ ┆ oss ┆ ers ┆ e_v ┆ k_v ┆ ica ┆ n_v ┆ fic ┆ ani ┆ r_v ┆ uni ┆ ngl ┆ ngl ┆ ngl ┆ h_5 ┆ h_1 ┆ h_6 ┆ niv ┆ one ┆ tru ┆ _un ┆ _un ┆ _4_ ┆ _9_ ┆ 0_1 ┆ 0_4 ┆ 0_p ┆ obi ┆ _m_ ┆ lat ┆ lon ┆ _va ┆ _va ┆ _va ┆ _va ┆ a_v ┆ ime ┆ pac ┆ n_6 ┆ n_u ┆ y_t ┆ _va ┆ ngl ┆ h_t ┆ var ┆ e_v ┆ _va ┆ us_ ┆ _5_ ┆ ili ┆ sch ┆ lor ┆ deg ┆ ty_ ┆ loy ┆ ng_ ┆ ng_ ┆ _va ┆ _va ┆ _va ┆ nic ┆ can ┆ ic_ ┆ oth ┆ ed_ ┆ gli ┆ le_ ┆ e_f ┆ _mu ┆ _mu ┆ e_h ┆ _sa │
│ f64 ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _bu ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ _po ┆ ati ┆ ati ┆ ati ┆ ati ┆ ati ┆ ati ┆ ati ┆ ati ┆ ati ┆ ati ┆ ati ┆ ati ┆ ati ┆ ati ┆ ati ┆ ati ┆ ati ┆ ati ┆ ati ┆ ati ┆ ati ┆ d_s ┆ d_s ┆ d_s ┆ d_s ┆ d_s ┆ d_s ┆ d_s ┆ d_s ┆ d_s ┆ d_s ┆ d_s ┆ d_s ┆ d_s ┆ d_s ┆ d_s ┆ d_s ┆ d_s ┆ d_s ┆ d_s ┆ d_s ┆ d_s ┆ d_s ┆ d_s ┆ d_g ┆ d_g ┆ d_g ┆ d_g ┆ d_g ┆ d_g ┆ d_g ┆ d_g ┆ d_g ┆ d_g ┆ d_g ┆ d_g ┆ d_g ┆ d_g ┆ d_g ┆ d_g ┆ d_g ┆ d_g ┆ d_g ┆ d_g ┆ d_g ┆ cip ┆ cip ┆ cip ┆ cip ┆ cip ┆ cip ┆ cip ┆ cip ┆ cip ┆ cip ┆ cip ┆ cip ┆ cip ┆ cip ┆ cip ┆ cip ┆ cip ┆ cip ┆ cip ┆ cip ┆ cip ┆ cip ┆ cip ┆ ibi ┆ ibi ┆ ibi ┆ ibi ┆ ibi ┆ ibi ┆ ibi ┆ ibi ┆ ibi ┆ ibi ┆ ibi ┆ ibi ┆ ibi ┆ ibi ┆ ibi ┆ ibi ┆ ibi ┆ ibi ┆ ibi ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ ome ┆ ome ┆ ome ┆ ome ┆ ome ┆ ome ┆ ome ┆ ome ┆ ome ┆ ome ┆ ome ┆ ome ┆ ome ┆ ome ┆ ome ┆ ome ┆ ome ┆ ome ┆ ome ┆ ree ┆ 0_h ┆ our ┆ our ┆ our ┆ our ┆ 01_ ┆ 10_ ┆ 25_ ┆ 50_ ┆ t_1 ┆ _ho ┆ urs ┆ our ┆ urs ┆ hou ┆ rs_ ┆ rs_ ┆ io_ ┆ ult ┆ cul ┆ gh_ ┆ er_ ┆ nit ┆ ota ┆ ale ┆ ema ┆ ar  ┆ ar  ┆ ar  ┆ ar  ┆ ar  ┆ _va ┆ _va ┆ _va ┆ _va ┆ _va ┆ _va ┆ us_ ┆ _va ┆ _5_ ┆ ar  ┆ nde ┆ 8_6 ┆ 5_p ┆ ool ┆ s_v ┆ var ┆ ona ┆ e_v ┆ ers ┆ w_v ┆ hol ┆ var ┆ civ ┆ _ci ┆ s_v ┆ pie ┆ nt_ ┆ val ┆ _re ┆ e_v ┆ ar  ┆ ar  ┆ n_i ┆ ar  ┆ _is ┆ c_v ┆ ar  ┆ ver ┆ ish ┆ ish ┆ ish ┆ _17 ┆ 8_6 ┆ 5_p ┆ ers ┆ _va ┆ ctu ┆ it_ ┆ it_ ┆ uni ┆ uni ┆ 9_u ┆ 9_u ┆ lus ┆ le_ ┆ var ┆ _va ┆ _va ┆ r   ┆ r   ┆ r   ┆ r   ┆ ar  ┆ ter ┆ tne ┆ 5_p ┆ nde ┆ ota ┆ r   ┆ ish ┆ ota ┆ --- ┆ ar  ┆ r   ┆ var ┆ var ┆ ty_ ┆ ool ┆ s_v ┆ ree ┆ var ┆ men ┆ occ ┆ vac ┆ r   ┆ r   ┆ r   ┆ _va ┆ _in ┆ isl ┆ er_ ┆ eng ┆ sh_ ┆ non ┆ ami ┆ lti ┆ lti ┆ ome ┆ nit │
│     ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ lb_ ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ int ┆ ve_ ┆ ve_ ┆ ve_ ┆ ve_ ┆ ve_ ┆ ve_ ┆ ve_ ┆ ve_ ┆ ve_ ┆ ve_ ┆ ve_ ┆ ve_ ┆ ve_ ┆ ve_ ┆ ve_ ┆ ve_ ┆ ve_ ┆ ve_ ┆ ve_ ┆ ve_ ┆ ve_ ┆ pee ┆ pee ┆ pee ┆ pee ┆ pee ┆ pee ┆ pee ┆ pee ┆ pee ┆ pee ┆ pee ┆ pee ┆ pee ┆ pee ┆ pee ┆ pee ┆ pee ┆ pee ┆ pee ┆ pee ┆ pee ┆ pee ┆ pee ┆ ust ┆ ust ┆ ust ┆ ust ┆ ust ┆ ust ┆ ust ┆ ust ┆ ust ┆ ust ┆ ust ┆ ust ┆ ust ┆ ust ┆ ust ┆ ust ┆ ust ┆ ust ┆ ust ┆ ust ┆ ust ┆ ita ┆ ita ┆ ita ┆ ita ┆ ita ┆ ita ┆ ita ┆ ita ┆ ita ┆ ita ┆ ita ┆ ita ┆ ita ┆ ita ┆ ita ┆ ita ┆ ita ┆ ita ┆ ita ┆ ita ┆ ita ┆ ita ┆ ita ┆ lit ┆ lit ┆ lit ┆ lit ┆ lit ┆ lit ┆ lit ┆ lit ┆ lit ┆ lit ┆ lit ┆ lit ┆ lit ┆ lit ┆ lit ┆ lit ┆ lit ┆ lit ┆ lit ┆ n_p ┆ n_p ┆ n_p ┆ n_p ┆ n_p ┆ n_p ┆ n_p ┆ n_p ┆ n_p ┆ n_p ┆ n_p ┆ n_p ┆ n_p ┆ n_p ┆ n_p ┆ n_p ┆ n_p ┆ n_p ┆ n_p ┆ tri ┆ tri ┆ tri ┆ tri ┆ tri ┆ tri ┆ tri ┆ tri ┆ tri ┆ tri ┆ tri ┆ tri ┆ tri ┆ tri ┆ tri ┆ tri ┆ tri ┆ tri ┆ tri ┆ zin ┆ our ┆ s_v ┆ s_v ┆ s_v ┆ s_v ┆ hou ┆ hou ┆ hou ┆ hou ┆ _ho ┆ urs ┆ _va ┆ s_v ┆ _va ┆ rs_ ┆ var ┆ var ┆ var ┆ ant ┆ ar_ ┆ win ┆ clu ┆ ize ┆ l_v ┆ _va ┆ le_ ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ r   ┆ r   ┆ r   ┆ r   ┆ r   ┆ r   ┆ var ┆ r   ┆ var ┆ --- ┆ r_1 ┆ 4_v ┆ lus ┆ _va ┆ ar  ┆ --- ┆ l_v ┆ ar  ┆ e_v ┆ ar  ┆ d_i ┆ --- ┆ ili ┆ vil ┆ ar  ┆ d_v ┆ var ┆ ue_ ┆ nt_ ┆ ar  ┆ --- ┆ --- ┆ ndi ┆ --- ┆ lan ┆ ar  ┆ --- ┆ se_ ┆ _5_ ┆ _18 ┆ _65 ┆ _va ┆ 4_v ┆ lus ┆ e_v ┆ r   ┆ re_ ┆ var ┆ var ┆ t_v ┆ t_v ┆ nit ┆ nit ┆ _un ┆ hom ┆ --- ┆ r   ┆ r   ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ _va ┆ ss_ ┆ lus ┆ r_5 ┆ l_v ┆ --- ┆ _to ┆ l_v ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ var ┆ _va ┆ ar  ┆ _va ┆ --- ┆ t_v ┆ upi ┆ ant ┆ --- ┆ --- ┆ --- ┆ r   ┆ dia ┆ and ┆ var ┆ lis ┆ var ┆ e_v ┆ ly_ ┆ _fa ┆ _fa ┆ _va ┆ ize │
│     ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ tem ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ _te ┆ hum ┆ hum ┆ hum ┆ hum ┆ hum ┆ hum ┆ hum ┆ hum ┆ hum ┆ hum ┆ hum ┆ hum ┆ hum ┆ hum ┆ hum ┆ hum ┆ hum ┆ hum ┆ hum ┆ hum ┆ hum ┆ d_m ┆ d_m ┆ d_s ┆ d_m ┆ d_m ┆ d_r ┆ d_c ┆ d_p ┆ d_p ┆ d_p ┆ d_p ┆ d_b ┆ d_b ┆ d_b ┆ d_b ┆ d_b ┆ d_b ┆ d_b ┆ d_b ┆ d_b ┆ d_b ┆ d_b ┆ d_b ┆ _sp ┆ _sp ┆ _sp ┆ _sp ┆ _sp ┆ _sp ┆ _sp ┆ _sp ┆ _sp ┆ _sp ┆ _sp ┆ _sp ┆ _sp ┆ _sp ┆ _sp ┆ _sp ┆ _sp ┆ _sp ┆ _sp ┆ _sp ┆ _sp ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ tio ┆ y_m ┆ y_m ┆ y_s ┆ y_m ┆ y_m ┆ y_r ┆ y_c ┆ y_p ┆ y_p ┆ y_p ┆ y_p ┆ y_b ┆ y_b ┆ y_b ┆ y_b ┆ y_b ┆ y_b ┆ y_b ┆ y_b ┆ res ┆ res ┆ res ┆ res ┆ res ┆ res ┆ res ┆ res ┆ res ┆ res ┆ res ┆ res ┆ res ┆ res ┆ res ┆ res ┆ res ┆ res ┆ res ┆ c_p ┆ c_p ┆ c_p ┆ c_p ┆ c_p ┆ c_p ┆ c_p ┆ c_p ┆ c_p ┆ c_p ┆ c_p ┆ c_p ┆ c_p ┆ c_p ┆ c_p ┆ c_p ┆ c_p ┆ c_p ┆ c_p ┆ g_h ┆ s_v ┆ ar  ┆ ar  ┆ ar  ┆ ar  ┆ rs_ ┆ rs_ ┆ rs_ ┆ rs_ ┆ urs ┆ _va ┆ r   ┆ ar  ┆ r   ┆ var ┆ --- ┆ --- ┆ --- ┆ _le ┆ var ┆ d_p ┆ ste ┆ d_f ┆ ar  ┆ r   ┆ var ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ f32 ┆ 8_v ┆ ar  ┆ _va ┆ r   ┆ --- ┆ f64 ┆ ar  ┆ --- ┆ ar  ┆ --- ┆ nco ┆ f64 ┆ an_ ┆ ian ┆ --- ┆ ar  ┆ --- ┆ var ┆ var ┆ --- ┆ f64 ┆ f64 ┆ an_ ┆ f64 ┆ der ┆ --- ┆ f64 ┆ var ┆ 17_ ┆ _64 ┆ _pl ┆ r   ┆ ar  ┆ _va ┆ ar  ┆ --- ┆ uni ┆ --- ┆ --- ┆ ar  ┆ ar  ┆ _va ┆ _va ┆ it_ ┆ e_v ┆ f32 ┆ --- ┆ --- ┆ f32 ┆ f32 ┆ f32 ┆ f32 ┆ f64 ┆ r   ┆ var ┆ _va ┆ _va ┆ ar  ┆ f64 ┆ tal ┆ ar  ┆     ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ r   ┆ --- ┆ r   ┆ f64 ┆ ar  ┆ ed_ ┆ _va ┆ f64 ┆ f64 ┆ f64 ┆ --- ┆ n_v ┆ er_ ┆ --- ┆ h_v ┆ --- ┆ ar  ┆ var ┆ mil ┆ mil ┆ r   ┆ d_f │

High level variance check indicates the presence of features that are both dynamic and close to or fully static. Those indicating close to or full static ranges will likely later be dropped during feature selection, the remaining are frequent and varied enough to support robust cross-sectional modeling.